// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgb "github.com/khoale-2804/pgb/core"
)

// ActiveUsers is the table descriptor for public.active_users; immutable, safe for
// concurrent use.
var ActiveUsers = ActiveUserTable{pgb.NewTableMeta("public", "active_users")}

// ActiveUserTable provides typed column accessors and statement entry points.
type ActiveUserTable struct{ pgb.TableMeta }

// ID returns the typed accessor for column id.
func (t ActiveUserTable) ID() ActiveUserIDCol {
	return ActiveUserIDCol{pgb.Col{Table: "active_users", Name: "id"}}
}

// ActiveUserIDCol is the typed column active_users.id.
type ActiveUserIDCol struct{ pgb.Col }

func (c ActiveUserIDCol) Eq(v int64) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserIDCol) Ne(v int64) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserIDCol) In(vs ...int64) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "int8[]" + ")", Args: []any{vs}}
}

func (c ActiveUserIDCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ActiveUserIDCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ActiveUserIDCol) Gt(v int64) pgb.Expr {
	return pgb.Bin{Op: ">", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserIDCol) Lt(v int64) pgb.Expr {
	return pgb.Bin{Op: "<", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserIDCol) Gte(v int64) pgb.Expr {
	return pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserIDCol) Lte(v int64) pgb.Expr {
	return pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserIDCol) Between(a, b int64) pgb.Expr {
	return pgb.And{Parts: []pgb.Expr{
		pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: a}},
		pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: b}},
	}}
}

// Email returns the typed accessor for column email.
func (t ActiveUserTable) Email() ActiveUserEmailCol {
	return ActiveUserEmailCol{pgb.Col{Table: "active_users", Name: "email"}}
}

// ActiveUserEmailCol is the typed column active_users.email.
type ActiveUserEmailCol struct{ pgb.Col }

func (c ActiveUserEmailCol) Eq(v string) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserEmailCol) Ne(v string) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserEmailCol) In(vs ...string) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c ActiveUserEmailCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ActiveUserEmailCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ActiveUserEmailCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c ActiveUserEmailCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c ActiveUserEmailCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c ActiveUserEmailCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// Name returns the typed accessor for column name.
func (t ActiveUserTable) Name() ActiveUserNameCol {
	return ActiveUserNameCol{pgb.Col{Table: "active_users", Name: "name"}}
}

// ActiveUserNameCol is the typed column active_users.name.
type ActiveUserNameCol struct{ pgb.Col }

func (c ActiveUserNameCol) Eq(v string) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserNameCol) Ne(v string) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserNameCol) In(vs ...string) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c ActiveUserNameCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ActiveUserNameCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ActiveUserNameCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c ActiveUserNameCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c ActiveUserNameCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c ActiveUserNameCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// CreatedAt returns the typed accessor for column created_at.
func (t ActiveUserTable) CreatedAt() ActiveUserCreatedAtCol {
	return ActiveUserCreatedAtCol{pgb.Col{Table: "active_users", Name: "created_at"}}
}

// ActiveUserCreatedAtCol is the typed column active_users.created_at.
type ActiveUserCreatedAtCol struct{ pgb.Col }

func (c ActiveUserCreatedAtCol) Eq(v pgtype.Timestamptz) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserCreatedAtCol) Ne(v pgtype.Timestamptz) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserCreatedAtCol) In(vs ...pgtype.Timestamptz) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "timestamptz[]" + ")", Args: []any{vs}}
}

func (c ActiveUserCreatedAtCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ActiveUserCreatedAtCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ActiveUserCreatedAtCol) Gt(v pgtype.Timestamptz) pgb.Expr {
	return pgb.Bin{Op: ">", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserCreatedAtCol) Lt(v pgtype.Timestamptz) pgb.Expr {
	return pgb.Bin{Op: "<", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserCreatedAtCol) Gte(v pgtype.Timestamptz) pgb.Expr {
	return pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserCreatedAtCol) Lte(v pgtype.Timestamptz) pgb.Expr {
	return pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ActiveUserCreatedAtCol) Between(a, b pgtype.Timestamptz) pgb.Expr {
	return pgb.And{Parts: []pgb.Expr{
		pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: a}},
		pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: b}},
	}}
}

// Select starts a SELECT of every column; chain Where/OrderBy/Limit/...
// and terminate with Run (or a static function).
func (t ActiveUserTable) Select() *pgb.Select {
	return pgb.NewSelect("public.active_users", pgb.Col{Table: "active_users", Name: "id"}, pgb.Col{Table: "active_users", Name: "email"}, pgb.Col{Table: "active_users", Name: "name"}, pgb.Col{Table: "active_users", Name: "created_at"})
}
