// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	core "github.com/khoale-2804/pgb/core"
)

// ActiveUsers is the table descriptor for public.active_users; immutable, safe for
// concurrent use.
var ActiveUsers = ActiveUserTable{core.NewTableMeta("public", "active_users")}

// ActiveUserTable provides typed column accessors and statement entry points.
type ActiveUserTable struct{ core.TableMeta }

// ID returns the typed accessor for column id.
func (t ActiveUserTable) ID() ActiveUserIDCol {
	return ActiveUserIDCol{core.Col{Table: "active_users", Name: "id"}}
}

// ActiveUserIDCol is the typed column active_users.id.
type ActiveUserIDCol struct{ core.Col }

func (c ActiveUserIDCol) Eq(v int64) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserIDCol) Ne(v int64) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserIDCol) In(vs ...int64) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "bigserial[]"}}
}

func (c ActiveUserIDCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ActiveUserIDCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ActiveUserIDCol) Gt(v int64) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserIDCol) Lt(v int64) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserIDCol) Gte(v int64) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserIDCol) Lte(v int64) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserIDCol) Between(a, b int64) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// Email returns the typed accessor for column email.
func (t ActiveUserTable) Email() ActiveUserEmailCol {
	return ActiveUserEmailCol{core.Col{Table: "active_users", Name: "email"}}
}

// ActiveUserEmailCol is the typed column active_users.email.
type ActiveUserEmailCol struct{ core.Col }

func (c ActiveUserEmailCol) Eq(v string) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserEmailCol) Ne(v string) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserEmailCol) In(vs ...string) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "text[]"}}
}

func (c ActiveUserEmailCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ActiveUserEmailCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ActiveUserEmailCol) Like(p string) core.Expr {
	return core.Bin{Op: "LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ActiveUserEmailCol) ILike(p string) core.Expr {
	return core.Bin{Op: "ILIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ActiveUserEmailCol) NotLike(p string) core.Expr {
	return core.Bin{Op: "NOT LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ActiveUserEmailCol) NotILike(p string) core.Expr {
	return core.Bin{Op: "NOT ILIKE", L: c.Col, R: core.Lit{V: p}}
}

// Name returns the typed accessor for column name.
func (t ActiveUserTable) Name() ActiveUserNameCol {
	return ActiveUserNameCol{core.Col{Table: "active_users", Name: "name"}}
}

// ActiveUserNameCol is the typed column active_users.name.
type ActiveUserNameCol struct{ core.Col }

func (c ActiveUserNameCol) Eq(v string) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserNameCol) Ne(v string) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserNameCol) In(vs ...string) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "text[]"}}
}

func (c ActiveUserNameCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ActiveUserNameCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ActiveUserNameCol) Like(p string) core.Expr {
	return core.Bin{Op: "LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ActiveUserNameCol) ILike(p string) core.Expr {
	return core.Bin{Op: "ILIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ActiveUserNameCol) NotLike(p string) core.Expr {
	return core.Bin{Op: "NOT LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ActiveUserNameCol) NotILike(p string) core.Expr {
	return core.Bin{Op: "NOT ILIKE", L: c.Col, R: core.Lit{V: p}}
}

// CreatedAt returns the typed accessor for column created_at.
func (t ActiveUserTable) CreatedAt() ActiveUserCreatedAtCol {
	return ActiveUserCreatedAtCol{core.Col{Table: "active_users", Name: "created_at"}}
}

// ActiveUserCreatedAtCol is the typed column active_users.created_at.
type ActiveUserCreatedAtCol struct{ core.Col }

func (c ActiveUserCreatedAtCol) Eq(v pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserCreatedAtCol) Ne(v pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserCreatedAtCol) In(vs ...pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "timestamptz[]"}}
}

func (c ActiveUserCreatedAtCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ActiveUserCreatedAtCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ActiveUserCreatedAtCol) Gt(v pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserCreatedAtCol) Lt(v pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserCreatedAtCol) Gte(v pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserCreatedAtCol) Lte(v pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c ActiveUserCreatedAtCol) Between(a, b pgtype.Timestamptz) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// Select starts a SELECT of every column; chain Where/OrderBy/Limit/...
// and terminate with Run (or a static function).
func (t ActiveUserTable) Select() *core.Select {
	return core.NewSelect("public.active_users", core.Col{Table: "active_users", Name: "id"}, core.Col{Table: "active_users", Name: "email"}, core.Col{Table: "active_users", Name: "name"}, core.Col{Table: "active_users", Name: "created_at"})
}
