// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	core "github.com/khoale-2804/pgb/core"
)

// AppUsers is the table descriptor for app.users; immutable, safe for
// concurrent use.
var AppUsers = AppUserTable{core.NewTableMeta("app", "users")}

// AppUserTable provides typed column accessors and statement entry points.
type AppUserTable struct{ core.TableMeta }

// ID returns the typed accessor for column id.
func (t AppUserTable) ID() AppUserIDCol {
	return AppUserIDCol{core.Col{Table: "users", Name: "id"}}
}

// AppUserIDCol is the typed column users.id.
type AppUserIDCol struct{ core.Col }

func (c AppUserIDCol) Eq(v int64) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserIDCol) Ne(v int64) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserIDCol) In(vs ...int64) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "bigserial[]"}}
}

func (c AppUserIDCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c AppUserIDCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c AppUserIDCol) Gt(v int64) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserIDCol) Lt(v int64) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserIDCol) Gte(v int64) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserIDCol) Lte(v int64) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserIDCol) Between(a, b int64) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// Login returns the typed accessor for column login.
func (t AppUserTable) Login() AppUserLoginCol {
	return AppUserLoginCol{core.Col{Table: "users", Name: "login"}}
}

// AppUserLoginCol is the typed column users.login.
type AppUserLoginCol struct{ core.Col }

func (c AppUserLoginCol) Eq(v string) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserLoginCol) Ne(v string) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserLoginCol) In(vs ...string) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "text[]"}}
}

func (c AppUserLoginCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c AppUserLoginCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c AppUserLoginCol) Like(p string) core.Expr {
	return core.Bin{Op: "LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c AppUserLoginCol) ILike(p string) core.Expr {
	return core.Bin{Op: "ILIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c AppUserLoginCol) NotLike(p string) core.Expr {
	return core.Bin{Op: "NOT LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c AppUserLoginCol) NotILike(p string) core.Expr {
	return core.Bin{Op: "NOT ILIKE", L: c.Col, R: core.Lit{V: p}}
}

// PersonID returns the typed accessor for column person_id.
func (t AppUserTable) PersonID() AppUserPersonIDCol {
	return AppUserPersonIDCol{core.Col{Table: "users", Name: "person_id"}}
}

// AppUserPersonIDCol is the typed column users.person_id.
type AppUserPersonIDCol struct{ core.Col }

func (c AppUserPersonIDCol) Eq(v pgtype.Int8) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserPersonIDCol) Ne(v pgtype.Int8) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserPersonIDCol) In(vs ...pgtype.Int8) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "int8[]"}}
}

func (c AppUserPersonIDCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c AppUserPersonIDCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c AppUserPersonIDCol) Gt(v pgtype.Int8) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserPersonIDCol) Lt(v pgtype.Int8) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserPersonIDCol) Gte(v pgtype.Int8) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserPersonIDCol) Lte(v pgtype.Int8) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserPersonIDCol) Between(a, b pgtype.Int8) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// Display returns the typed accessor for column display.
func (t AppUserTable) Display() AppUserDisplayCol {
	return AppUserDisplayCol{core.Col{Table: "users", Name: "display"}}
}

// AppUserDisplayCol is the typed column users.display.
type AppUserDisplayCol struct{ core.Col }

func (c AppUserDisplayCol) Eq(v pgtype.Text) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserDisplayCol) Ne(v pgtype.Text) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c AppUserDisplayCol) In(vs ...pgtype.Text) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "text[]"}}
}

func (c AppUserDisplayCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c AppUserDisplayCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c AppUserDisplayCol) Like(p string) core.Expr {
	return core.Bin{Op: "LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c AppUserDisplayCol) ILike(p string) core.Expr {
	return core.Bin{Op: "ILIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c AppUserDisplayCol) NotLike(p string) core.Expr {
	return core.Bin{Op: "NOT LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c AppUserDisplayCol) NotILike(p string) core.Expr {
	return core.Bin{Op: "NOT ILIKE", L: c.Col, R: core.Lit{V: p}}
}

// Select starts a SELECT of every column; chain Where/OrderBy/Limit/...
// and terminate with Run (or a static function).
func (t AppUserTable) Select() *core.Select {
	return core.NewSelect("app.users", core.Col{Table: "users", Name: "id"}, core.Col{Table: "users", Name: "login"}, core.Col{Table: "users", Name: "person_id"}, core.Col{Table: "users", Name: "display"})
}

// Update starts an UPDATE; an empty WHERE fails with core.ErrNoWhere.
func (t AppUserTable) Update() *core.Update { return core.NewUpdate("app.users") }

// Delete starts a DELETE; an empty WHERE fails with core.ErrNoWhere.
func (t AppUserTable) Delete() *core.Delete { return core.NewDelete("app.users") }
