// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"errors"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	core "github.com/khoale-2804/pgb/core"
)

// AppUserFilter narrows ListAppUsers and CountAppUsers:
// nil / zero fields are ignored; Extra composes raw predicates.
type AppUserFilter struct {
	ID           *int64
	IDIn         []int64
	IDGt         *int64
	IDLt         *int64
	IDGte        *int64
	IDLte        *int64
	Login        *string
	LoginIn      []string
	LoginLike    *string
	LoginILike   *string
	PersonID     *pgtype.Int8
	PersonIDIn   []pgtype.Int8
	PersonIDGt   *pgtype.Int8
	PersonIDLt   *pgtype.Int8
	PersonIDGte  *pgtype.Int8
	PersonIDLte  *pgtype.Int8
	Display      *pgtype.Text
	DisplayIn    []pgtype.Text
	DisplayLike  *string
	DisplayILike *string
	Extra        []core.Expr
}

// appUsersFilterWhere compiles f into the ANDed predicate list; an empty
// filter yields an empty list (no WHERE).
func appUsersFilterWhere(f AppUserFilter) []core.Expr {
	var w []core.Expr
	if f.ID != nil {
		w = append(w, AppUsers.ID().Eq(*f.ID))
	}
	if len(f.IDIn) > 0 {
		w = append(w, AppUsers.ID().In(f.IDIn...))
	}
	if f.IDGt != nil {
		w = append(w, AppUsers.ID().Gt(*f.IDGt))
	}
	if f.IDLt != nil {
		w = append(w, AppUsers.ID().Lt(*f.IDLt))
	}
	if f.IDGte != nil {
		w = append(w, AppUsers.ID().Gte(*f.IDGte))
	}
	if f.IDLte != nil {
		w = append(w, AppUsers.ID().Lte(*f.IDLte))
	}
	if f.Login != nil {
		w = append(w, AppUsers.Login().Eq(*f.Login))
	}
	if len(f.LoginIn) > 0 {
		w = append(w, AppUsers.Login().In(f.LoginIn...))
	}
	if f.LoginLike != nil {
		w = append(w, AppUsers.Login().Like(*f.LoginLike))
	}
	if f.LoginILike != nil {
		w = append(w, AppUsers.Login().ILike(*f.LoginILike))
	}
	if f.PersonID != nil {
		w = append(w, AppUsers.PersonID().Eq(*f.PersonID))
	}
	if len(f.PersonIDIn) > 0 {
		w = append(w, AppUsers.PersonID().In(f.PersonIDIn...))
	}
	if f.PersonIDGt != nil {
		w = append(w, AppUsers.PersonID().Gt(*f.PersonIDGt))
	}
	if f.PersonIDLt != nil {
		w = append(w, AppUsers.PersonID().Lt(*f.PersonIDLt))
	}
	if f.PersonIDGte != nil {
		w = append(w, AppUsers.PersonID().Gte(*f.PersonIDGte))
	}
	if f.PersonIDLte != nil {
		w = append(w, AppUsers.PersonID().Lte(*f.PersonIDLte))
	}
	if f.Display != nil {
		w = append(w, AppUsers.Display().Eq(*f.Display))
	}
	if len(f.DisplayIn) > 0 {
		w = append(w, AppUsers.Display().In(f.DisplayIn...))
	}
	if f.DisplayLike != nil {
		w = append(w, AppUsers.Display().Like(*f.DisplayLike))
	}
	if f.DisplayILike != nil {
		w = append(w, AppUsers.Display().ILike(*f.DisplayILike))
	}
	w = append(w, f.Extra...)
	return w
}

// AppUserSet is the three-state UPDATE payload: a zero Set field
// skips its column, SetOf writes a value, SetNull writes NULL.
type AppUserSet struct {
	Login    Set[string]
	PersonID Set[pgtype.Int8]
	Display  Set[pgtype.Text]
}

// InsertAppUserParams carries the INSERT column values: generated
// and serial columns are out, default-bearing columns join only with
// the include_defaults option.
type InsertAppUserParams struct {
	Login    string
	PersonID pgtype.Int8
	Display  pgtype.Text
}

// scanAppUser scans one row positionally over every column in
// catalog order — the single scan path for all generated reads.
func scanAppUser(row pgx.CollectableRow) (AppUser, error) {
	var m AppUser
	if err := row.Scan(&m.ID, &m.Login, &m.PersonID, &m.Display); err != nil {
		return AppUser{}, err
	}
	return m, nil
}

// GetAppUser returns one row by id; core.ErrNotFound when absent
// (pgx.ErrNoRows mapped — errors.Is keeps working for both).
func GetAppUser(ctx context.Context, exec core.DBTX, id int64) (AppUser, error) {
	sql, args := AppUsers.Select().Where(AppUsers.ID().Eq(id)).SQL()
	var m AppUser
	err := exec.QueryRow(ctx, sql, args...).Scan(&m.ID, &m.Login, &m.PersonID, &m.Display)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return AppUser{}, core.ErrNotFound
		}
		return AppUser{}, err
	}
	return m, nil
}

// ListAppUsers returns the rows matching f; limit <= 0 means no LIMIT.
func ListAppUsers(ctx context.Context, exec core.DBTX, f AppUserFilter, limit int) ([]AppUser, error) {
	rows, err := AppUsers.Select().Where(appUsersFilterWhere(f)...).Limit(limit).Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanAppUser)
}

// CountAppUsers counts the rows matching f.
func CountAppUsers(ctx context.Context, exec core.DBTX, f AppUserFilter) (int64, error) {
	sql, args := core.NewSelect("app.users", core.Raw{SQL: "count(*)"}).Where(appUsersFilterWhere(f)...).SQL()
	var n int64
	if err := exec.QueryRow(ctx, sql, args...).Scan(&n); err != nil {
		return 0, err
	}
	return n, nil
}

// InsertAppUser inserts one row and returns it (RETURNING every
// column, defaults included).
func InsertAppUser(ctx context.Context, exec core.DBTX, p InsertAppUserParams) (AppUser, error) {
	rows, err := core.NewInsert("app.users",
		[]string{"login", "person_id", "display"},
		[]core.Expr{core.Lit{V: p.Login}, core.Lit{V: p.PersonID}, core.Lit{V: p.Display}},
	).Returning(core.Col{Table: "users", Name: "id"}, core.Col{Table: "users", Name: "login"}, core.Col{Table: "users", Name: "person_id"}, core.Col{Table: "users", Name: "display"}).Run(ctx, exec)
	if err != nil {
		return AppUser{}, err
	}
	us, err := pgx.CollectRows(rows, scanAppUser)
	if err != nil {
		return AppUser{}, err
	}
	if len(us) == 0 {
		return AppUser{}, core.ErrNotFound
	}
	return us[0], nil
}

const insertAppUsersSQL = "INSERT INTO app.users (login, person_id, display) SELECT * FROM unnest($1::text[], $2::int8[], $3::text[]) RETURNING id, login, person_id, display"

// InsertAppUsers inserts a whole batch in one round trip via
// unnest and returns every inserted row.
func InsertAppUsers(ctx context.Context, exec core.DBTX, ps []InsertAppUserParams) ([]AppUser, error) {
	if len(ps) == 0 {
		return nil, nil
	}
	colLogin := make([]string, len(ps))
	colPersonID := make([]pgtype.Int8, len(ps))
	colDisplay := make([]pgtype.Text, len(ps))
	for i, p := range ps {
		colLogin[i] = p.Login
		colPersonID[i] = p.PersonID
		colDisplay[i] = p.Display
	}
	args := make([]any, 0, 3*len(ps))
	args = append(args, colLogin, colPersonID, colDisplay)
	rows, err := exec.Query(ctx, insertAppUsersSQL, args...)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanAppUser)
}

// UpdateAppUser applies the non-zero fields of s to one row and
// returns the updated row; core.ErrNotFound when absent.
func UpdateAppUser(ctx context.Context, exec core.DBTX, id int64, s AppUserSet) (AppUser, error) {
	u := AppUsers.Update()
	n := 0
	if s.Login.Valid {
		n++
		if s.Login.Null {
			u.Set("login", core.Lit{V: nil})
		} else {
			u.Set("login", core.Lit{V: s.Login.V})
		}
	}
	if s.PersonID.Valid {
		n++
		if s.PersonID.Null {
			u.Set("person_id", core.Lit{V: nil})
		} else {
			u.Set("person_id", core.Lit{V: s.PersonID.V})
		}
	}
	if s.Display.Valid {
		n++
		if s.Display.Null {
			u.Set("display", core.Lit{V: nil})
		} else {
			u.Set("display", core.Lit{V: s.Display.V})
		}
	}
	if n == 0 {
		return GetAppUser(ctx, exec, id)
	}
	u.Where(AppUsers.ID().Eq(id)).Returning(core.Col{Table: "users", Name: "id"}, core.Col{Table: "users", Name: "login"}, core.Col{Table: "users", Name: "person_id"}, core.Col{Table: "users", Name: "display"})
	rows, err := u.Run(ctx, exec)
	if err != nil {
		return AppUser{}, err
	}
	us, err := pgx.CollectRows(rows, scanAppUser)
	if err != nil {
		return AppUser{}, err
	}
	if len(us) == 0 {
		return AppUser{}, core.ErrNotFound
	}
	return us[0], nil
}

// UpdateAppUsers applies s to every row matching where and
// returns the affected count; an empty where is refused with
// core.ErrNoWhere before any SQL is sent.
func UpdateAppUsers(ctx context.Context, exec core.DBTX, where []core.Expr, s AppUserSet) (int64, error) {
	u := AppUsers.Update()
	n := 0
	if s.Login.Valid {
		n++
		if s.Login.Null {
			u.Set("login", core.Lit{V: nil})
		} else {
			u.Set("login", core.Lit{V: s.Login.V})
		}
	}
	if s.PersonID.Valid {
		n++
		if s.PersonID.Null {
			u.Set("person_id", core.Lit{V: nil})
		} else {
			u.Set("person_id", core.Lit{V: s.PersonID.V})
		}
	}
	if s.Display.Valid {
		n++
		if s.Display.Null {
			u.Set("display", core.Lit{V: nil})
		} else {
			u.Set("display", core.Lit{V: s.Display.V})
		}
	}
	if n == 0 {
		return 0, nil
	}
	if len(where) == 0 {
		return 0, core.ErrNoWhere
	}
	u.Where(where...)
	tag, err := u.Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// UpsertAppUser inserts p under id, or on conflict updates
// every settable column from the proposed row (EXCLUDED.*) and returns
// the resulting row; core.ErrNotFound when DO NOTHING matched.
func UpsertAppUser(ctx context.Context, exec core.DBTX, id int64, p InsertAppUserParams) (AppUser, error) {
	rows, err := core.NewInsert("app.users",
		[]string{"id", "login", "person_id", "display"},
		[]core.Expr{core.Lit{V: id}, core.Lit{V: p.Login}, core.Lit{V: p.PersonID}, core.Lit{V: p.Display}},
	).OnConflict(core.OnConflict{
		Target: []string{"id"},
		Sets: []core.SetClause{
			{Col: "login", E: core.Col{Table: "excluded", Name: "login"}},
			{Col: "person_id", E: core.Col{Table: "excluded", Name: "person_id"}},
			{Col: "display", E: core.Col{Table: "excluded", Name: "display"}},
		},
	}).Returning(core.Col{Table: "users", Name: "id"}, core.Col{Table: "users", Name: "login"}, core.Col{Table: "users", Name: "person_id"}, core.Col{Table: "users", Name: "display"}).Run(ctx, exec)
	if err != nil {
		return AppUser{}, err
	}
	us, err := pgx.CollectRows(rows, scanAppUser)
	if err != nil {
		return AppUser{}, err
	}
	if len(us) == 0 {
		return AppUser{}, core.ErrNotFound
	}
	return us[0], nil
}

// DeleteAppUser removes one row by id.
func DeleteAppUser(ctx context.Context, exec core.DBTX, id int64) error {
	_, err := AppUsers.Delete().Where(AppUsers.ID().Eq(id)).Exec(ctx, exec)
	return err
}

// DeleteAppUsers removes every row matching where and returns the
// affected count; an empty where is refused with core.ErrNoWhere.
func DeleteAppUsers(ctx context.Context, exec core.DBTX, where []core.Expr) (int64, error) {
	if len(where) == 0 {
		return 0, core.ErrNoWhere
	}
	tag, err := AppUsers.Delete().Where(where...).Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
