// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"errors"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	pgb "github.com/khoale-2804/pgb/core"
)

// CacheBlobFilter narrows ListCacheBlobs and CountCacheBlobs:
// nil / zero fields are ignored; Extra composes raw predicates.
type CacheBlobFilter struct {
	Key          *string
	KeyIn        []string
	KeyLike      *string
	KeyILike     *string
	Value        *[]byte
	ValueIn      [][]byte
	ExpiresAt    *pgtype.Timestamptz
	ExpiresAtIn  []pgtype.Timestamptz
	ExpiresAtGt  *pgtype.Timestamptz
	ExpiresAtLt  *pgtype.Timestamptz
	ExpiresAtGte *pgtype.Timestamptz
	ExpiresAtLte *pgtype.Timestamptz
	Extra        []pgb.Expr
}

// cacheBlobsFilterWhere compiles f into the ANDed predicate list; an empty
// filter yields an empty list (no WHERE).
func cacheBlobsFilterWhere(f CacheBlobFilter) []pgb.Expr {
	var w []pgb.Expr
	if f.Key != nil {
		w = append(w, CacheBlobs.Key().Eq(*f.Key))
	}
	if len(f.KeyIn) > 0 {
		w = append(w, CacheBlobs.Key().In(f.KeyIn...))
	}
	if f.KeyLike != nil {
		w = append(w, CacheBlobs.Key().Like(*f.KeyLike))
	}
	if f.KeyILike != nil {
		w = append(w, CacheBlobs.Key().ILike(*f.KeyILike))
	}
	if f.Value != nil {
		w = append(w, CacheBlobs.Value().Eq(*f.Value))
	}
	if len(f.ValueIn) > 0 {
		w = append(w, CacheBlobs.Value().In(f.ValueIn...))
	}
	if f.ExpiresAt != nil {
		w = append(w, CacheBlobs.ExpiresAt().Eq(*f.ExpiresAt))
	}
	if len(f.ExpiresAtIn) > 0 {
		w = append(w, CacheBlobs.ExpiresAt().In(f.ExpiresAtIn...))
	}
	if f.ExpiresAtGt != nil {
		w = append(w, CacheBlobs.ExpiresAt().Gt(*f.ExpiresAtGt))
	}
	if f.ExpiresAtLt != nil {
		w = append(w, CacheBlobs.ExpiresAt().Lt(*f.ExpiresAtLt))
	}
	if f.ExpiresAtGte != nil {
		w = append(w, CacheBlobs.ExpiresAt().Gte(*f.ExpiresAtGte))
	}
	if f.ExpiresAtLte != nil {
		w = append(w, CacheBlobs.ExpiresAt().Lte(*f.ExpiresAtLte))
	}
	w = append(w, f.Extra...)
	return w
}

// CacheBlobSet is the three-state UPDATE payload: a zero Set field
// skips its column, SetOf writes a value, SetNull writes NULL.
type CacheBlobSet struct {
	Value     Set[[]byte]
	ExpiresAt Set[pgtype.Timestamptz]
}

// InsertCacheBlobParams carries the INSERT column values: generated
// and serial columns are out, default-bearing columns join only with
// the include_defaults option.
type InsertCacheBlobParams struct {
	Key       string
	Value     []byte
	ExpiresAt pgtype.Timestamptz
}

// scanCacheBlob scans one row positionally over every column in
// catalog order — the single scan path for all generated reads.
func scanCacheBlob(row pgx.CollectableRow) (CacheBlob, error) {
	var m CacheBlob
	if err := row.Scan(&m.Key, &m.Value, &m.ExpiresAt); err != nil {
		return CacheBlob{}, err
	}
	return m, nil
}

// GetCacheBlob returns one row by key; pgb.ErrNotFound when absent
// (pgx.ErrNoRows mapped — errors.Is keeps working for both).
func GetCacheBlob(ctx context.Context, exec pgb.DBTX, key string) (CacheBlob, error) {
	sql, args := CacheBlobs.Select().Where(CacheBlobs.Key().Eq(key)).SQL()
	var m CacheBlob
	err := exec.QueryRow(ctx, sql, args...).Scan(&m.Key, &m.Value, &m.ExpiresAt)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return CacheBlob{}, pgb.ErrNotFound
		}
		return CacheBlob{}, err
	}
	return m, nil
}

// ListCacheBlobs returns the rows matching f; limit <= 0 means no LIMIT.
func ListCacheBlobs(ctx context.Context, exec pgb.DBTX, f CacheBlobFilter, opts ...pgb.ListOpt) ([]CacheBlob, error) {
	sel := CacheBlobs.Select().Where(cacheBlobsFilterWhere(f)...).ApplyList(opts...)
	rows, err := sel.Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanCacheBlob)
}

// CountCacheBlobs counts the rows matching f.
func CountCacheBlobs(ctx context.Context, exec pgb.DBTX, f CacheBlobFilter) (int64, error) {
	sql, args := pgb.NewSelect("public.cache_blob", pgb.Raw{SQL: "count(*)"}).Where(cacheBlobsFilterWhere(f)...).SQL()
	var n int64
	if err := exec.QueryRow(ctx, sql, args...).Scan(&n); err != nil {
		return 0, err
	}
	return n, nil
}

// InsertCacheBlob inserts one row and returns it (RETURNING every
// column, defaults included).
func InsertCacheBlob(ctx context.Context, exec pgb.DBTX, p InsertCacheBlobParams) (CacheBlob, error) {
	rows, err := pgb.NewInsert("public.cache_blob",
		[]string{"key", "value", "expires_at"},
		[]pgb.Expr{pgb.Lit{V: p.Key}, pgb.Lit{V: p.Value}, pgb.Lit{V: p.ExpiresAt}},
	).Returning(pgb.Col{Table: "cache_blob", Name: "key"}, pgb.Col{Table: "cache_blob", Name: "value"}, pgb.Col{Table: "cache_blob", Name: "expires_at"}).Run(ctx, exec)
	if err != nil {
		return CacheBlob{}, err
	}
	us, err := pgx.CollectRows(rows, scanCacheBlob)
	if err != nil {
		return CacheBlob{}, err
	}
	if len(us) == 0 {
		return CacheBlob{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// UpdateCacheBlob applies the non-zero fields of s to one row and
// returns the updated row; pgb.ErrNotFound when absent.
func UpdateCacheBlob(ctx context.Context, exec pgb.DBTX, key string, s CacheBlobSet) (CacheBlob, error) {
	u := CacheBlobs.Update()
	n := 0
	if s.Value.Valid {
		n++
		if s.Value.Null {
			u.Set("value", pgb.Lit{V: nil})
		} else {
			u.Set("value", pgb.Lit{V: s.Value.V})
		}
	}
	if s.ExpiresAt.Valid {
		n++
		if s.ExpiresAt.Null {
			u.Set("expires_at", pgb.Lit{V: nil})
		} else {
			u.Set("expires_at", pgb.Lit{V: s.ExpiresAt.V})
		}
	}
	if n == 0 {
		return GetCacheBlob(ctx, exec, key)
	}
	u.Where(CacheBlobs.Key().Eq(key)).Returning(pgb.Col{Table: "cache_blob", Name: "key"}, pgb.Col{Table: "cache_blob", Name: "value"}, pgb.Col{Table: "cache_blob", Name: "expires_at"})
	rows, err := u.Run(ctx, exec)
	if err != nil {
		return CacheBlob{}, err
	}
	us, err := pgx.CollectRows(rows, scanCacheBlob)
	if err != nil {
		return CacheBlob{}, err
	}
	if len(us) == 0 {
		return CacheBlob{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// UpdateCacheBlobs applies s to every row matching where and
// returns the affected count; an empty where is refused with
// pgb.ErrNoWhere before any SQL is sent.
func UpdateCacheBlobs(ctx context.Context, exec pgb.DBTX, where []pgb.Expr, s CacheBlobSet) (int64, error) {
	u := CacheBlobs.Update()
	n := 0
	if s.Value.Valid {
		n++
		if s.Value.Null {
			u.Set("value", pgb.Lit{V: nil})
		} else {
			u.Set("value", pgb.Lit{V: s.Value.V})
		}
	}
	if s.ExpiresAt.Valid {
		n++
		if s.ExpiresAt.Null {
			u.Set("expires_at", pgb.Lit{V: nil})
		} else {
			u.Set("expires_at", pgb.Lit{V: s.ExpiresAt.V})
		}
	}
	if n == 0 {
		return 0, nil
	}
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	u.Where(where...)
	tag, err := u.Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// UpsertCacheBlob inserts p under key, or on conflict updates
// every settable column from the proposed row (EXCLUDED.*) and returns
// the resulting row; pgb.ErrNotFound when DO NOTHING matched.
func UpsertCacheBlob(ctx context.Context, exec pgb.DBTX, key string, p InsertCacheBlobParams) (CacheBlob, error) {
	rows, err := pgb.NewInsert("public.cache_blob",
		[]string{"key", "value", "expires_at"},
		[]pgb.Expr{pgb.Lit{V: key}, pgb.Lit{V: p.Value}, pgb.Lit{V: p.ExpiresAt}},
	).OnConflict(pgb.OnConflict{
		Target: []string{"key"},
		Sets: []pgb.SetClause{
			{Col: "value", E: pgb.Col{Table: "excluded", Name: "value"}},
			{Col: "expires_at", E: pgb.Col{Table: "excluded", Name: "expires_at"}},
		},
	}).Returning(pgb.Col{Table: "cache_blob", Name: "key"}, pgb.Col{Table: "cache_blob", Name: "value"}, pgb.Col{Table: "cache_blob", Name: "expires_at"}).Run(ctx, exec)
	if err != nil {
		return CacheBlob{}, err
	}
	us, err := pgx.CollectRows(rows, scanCacheBlob)
	if err != nil {
		return CacheBlob{}, err
	}
	if len(us) == 0 {
		return CacheBlob{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// DeleteCacheBlob removes one row by key.
func DeleteCacheBlob(ctx context.Context, exec pgb.DBTX, key string) error {
	_, err := CacheBlobs.Delete().Where(CacheBlobs.Key().Eq(key)).Exec(ctx, exec)
	return err
}

// DeleteCacheBlobs removes every row matching where and returns the
// affected count; an empty where is refused with pgb.ErrNoWhere.
func DeleteCacheBlobs(ctx context.Context, exec pgb.DBTX, where []pgb.Expr) (int64, error) {
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	tag, err := CacheBlobs.Delete().Where(where...).Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
