// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgb "github.com/khoale-2804/pgb/core"
)

// CaseCols is the table descriptor for public.case_cols; immutable, safe for
// concurrent use.
var CaseCols = CaseColTable{pgb.NewTableMeta("public", "case_cols")}

// CaseColTable provides typed column accessors and statement entry points.
type CaseColTable struct{ pgb.TableMeta }

// ID returns the typed accessor for column id.
func (t CaseColTable) ID() CaseColIDCol {
	return CaseColIDCol{pgb.Col{Table: "case_cols", Name: "id"}}
}

// CaseColIDCol is the typed column case_cols.id.
type CaseColIDCol struct{ pgb.Col }

func (c CaseColIDCol) Eq(v int64) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColIDCol) Ne(v int64) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColIDCol) In(vs ...int64) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "int8[]" + ")", Args: []any{vs}}
}

func (c CaseColIDCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c CaseColIDCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c CaseColIDCol) Gt(v int64) pgb.Expr {
	return pgb.Bin{Op: ">", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColIDCol) Lt(v int64) pgb.Expr {
	return pgb.Bin{Op: "<", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColIDCol) Gte(v int64) pgb.Expr {
	return pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColIDCol) Lte(v int64) pgb.Expr {
	return pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColIDCol) Between(a, b int64) pgb.Expr {
	return pgb.And{Parts: []pgb.Expr{
		pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: a}},
		pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: b}},
	}}
}

// Email returns the typed accessor for column Email.
func (t CaseColTable) Email() CaseColEmailCol {
	return CaseColEmailCol{pgb.Col{Table: "case_cols", Name: "Email"}}
}

// CaseColEmailCol is the typed column case_cols.Email.
type CaseColEmailCol struct{ pgb.Col }

func (c CaseColEmailCol) Eq(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColEmailCol) Ne(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColEmailCol) In(vs ...pgtype.Text) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c CaseColEmailCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c CaseColEmailCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c CaseColEmailCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c CaseColEmailCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c CaseColEmailCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c CaseColEmailCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// Mixedcase returns the typed accessor for column mixedcase.
func (t CaseColTable) Mixedcase() CaseColMixedcaseCol {
	return CaseColMixedcaseCol{pgb.Col{Table: "case_cols", Name: "mixedcase"}}
}

// CaseColMixedcaseCol is the typed column case_cols.mixedcase.
type CaseColMixedcaseCol struct{ pgb.Col }

func (c CaseColMixedcaseCol) Eq(v pgtype.Int4) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColMixedcaseCol) Ne(v pgtype.Int4) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColMixedcaseCol) In(vs ...pgtype.Int4) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "int4[]" + ")", Args: []any{vs}}
}

func (c CaseColMixedcaseCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c CaseColMixedcaseCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c CaseColMixedcaseCol) Gt(v pgtype.Int4) pgb.Expr {
	return pgb.Bin{Op: ">", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColMixedcaseCol) Lt(v pgtype.Int4) pgb.Expr {
	return pgb.Bin{Op: "<", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColMixedcaseCol) Gte(v pgtype.Int4) pgb.Expr {
	return pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColMixedcaseCol) Lte(v pgtype.Int4) pgb.Expr {
	return pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColMixedcaseCol) Between(a, b pgtype.Int4) pgb.Expr {
	return pgb.And{Parts: []pgb.Expr{
		pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: a}},
		pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: b}},
	}}
}

// Caf returns the typed accessor for column café.
func (t CaseColTable) Caf() CaseColCafCol {
	return CaseColCafCol{pgb.Col{Table: "case_cols", Name: "café"}}
}

// CaseColCafCol is the typed column case_cols.café.
type CaseColCafCol struct{ pgb.Col }

func (c CaseColCafCol) Eq(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColCafCol) Ne(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColCafCol) In(vs ...pgtype.Text) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c CaseColCafCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c CaseColCafCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c CaseColCafCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c CaseColCafCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c CaseColCafCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c CaseColCafCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// PlainCol returns the typed accessor for column plain_col.
func (t CaseColTable) PlainCol() CaseColPlainColCol {
	return CaseColPlainColCol{pgb.Col{Table: "case_cols", Name: "plain_col"}}
}

// CaseColPlainColCol is the typed column case_cols.plain_col.
type CaseColPlainColCol struct{ pgb.Col }

func (c CaseColPlainColCol) Eq(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColPlainColCol) Ne(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CaseColPlainColCol) In(vs ...pgtype.Text) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c CaseColPlainColCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c CaseColPlainColCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c CaseColPlainColCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c CaseColPlainColCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c CaseColPlainColCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c CaseColPlainColCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// Select starts a SELECT of every column; chain Where/OrderBy/Limit/...
// and terminate with Run (or a static function).
func (t CaseColTable) Select() *pgb.Select {
	return pgb.NewSelect("public.case_cols", pgb.Col{Table: "case_cols", Name: "id"}, pgb.Col{Table: "case_cols", Name: "Email"}, pgb.Col{Table: "case_cols", Name: "mixedcase"}, pgb.Col{Table: "case_cols", Name: "café"}, pgb.Col{Table: "case_cols", Name: "plain_col"})
}

// Update starts an UPDATE; an empty WHERE fails with pgb.ErrNoWhere.
func (t CaseColTable) Update() *pgb.Update { return pgb.NewUpdate("public.case_cols") }

// Delete starts a DELETE; an empty WHERE fails with pgb.ErrNoWhere.
func (t CaseColTable) Delete() *pgb.Delete { return pgb.NewDelete("public.case_cols") }
