// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"errors"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	core "github.com/khoale-2804/pgb/core"
)

// CaseColFilter narrows ListCaseCols and CountCaseCols:
// nil / zero fields are ignored; Extra composes raw predicates.
type CaseColFilter struct {
	ID            *int64
	IDIn          []int64
	IDGt          *int64
	IDLt          *int64
	IDGte         *int64
	IDLte         *int64
	Email         *pgtype.Text
	EmailIn       []pgtype.Text
	EmailLike     *string
	EmailILike    *string
	Mixedcase     *pgtype.Int4
	MixedcaseIn   []pgtype.Int4
	MixedcaseGt   *pgtype.Int4
	MixedcaseLt   *pgtype.Int4
	MixedcaseGte  *pgtype.Int4
	MixedcaseLte  *pgtype.Int4
	Caf           *pgtype.Text
	CafIn         []pgtype.Text
	CafLike       *string
	CafILike      *string
	PlainCol      *pgtype.Text
	PlainColIn    []pgtype.Text
	PlainColLike  *string
	PlainColILike *string
	Extra         []core.Expr
}

// caseColsFilterWhere compiles f into the ANDed predicate list; an empty
// filter yields an empty list (no WHERE).
func caseColsFilterWhere(f CaseColFilter) []core.Expr {
	var w []core.Expr
	if f.ID != nil {
		w = append(w, CaseCols.ID().Eq(*f.ID))
	}
	if len(f.IDIn) > 0 {
		w = append(w, CaseCols.ID().In(f.IDIn...))
	}
	if f.IDGt != nil {
		w = append(w, CaseCols.ID().Gt(*f.IDGt))
	}
	if f.IDLt != nil {
		w = append(w, CaseCols.ID().Lt(*f.IDLt))
	}
	if f.IDGte != nil {
		w = append(w, CaseCols.ID().Gte(*f.IDGte))
	}
	if f.IDLte != nil {
		w = append(w, CaseCols.ID().Lte(*f.IDLte))
	}
	if f.Email != nil {
		w = append(w, CaseCols.Email().Eq(*f.Email))
	}
	if len(f.EmailIn) > 0 {
		w = append(w, CaseCols.Email().In(f.EmailIn...))
	}
	if f.EmailLike != nil {
		w = append(w, CaseCols.Email().Like(*f.EmailLike))
	}
	if f.EmailILike != nil {
		w = append(w, CaseCols.Email().ILike(*f.EmailILike))
	}
	if f.Mixedcase != nil {
		w = append(w, CaseCols.Mixedcase().Eq(*f.Mixedcase))
	}
	if len(f.MixedcaseIn) > 0 {
		w = append(w, CaseCols.Mixedcase().In(f.MixedcaseIn...))
	}
	if f.MixedcaseGt != nil {
		w = append(w, CaseCols.Mixedcase().Gt(*f.MixedcaseGt))
	}
	if f.MixedcaseLt != nil {
		w = append(w, CaseCols.Mixedcase().Lt(*f.MixedcaseLt))
	}
	if f.MixedcaseGte != nil {
		w = append(w, CaseCols.Mixedcase().Gte(*f.MixedcaseGte))
	}
	if f.MixedcaseLte != nil {
		w = append(w, CaseCols.Mixedcase().Lte(*f.MixedcaseLte))
	}
	if f.Caf != nil {
		w = append(w, CaseCols.Caf().Eq(*f.Caf))
	}
	if len(f.CafIn) > 0 {
		w = append(w, CaseCols.Caf().In(f.CafIn...))
	}
	if f.CafLike != nil {
		w = append(w, CaseCols.Caf().Like(*f.CafLike))
	}
	if f.CafILike != nil {
		w = append(w, CaseCols.Caf().ILike(*f.CafILike))
	}
	if f.PlainCol != nil {
		w = append(w, CaseCols.PlainCol().Eq(*f.PlainCol))
	}
	if len(f.PlainColIn) > 0 {
		w = append(w, CaseCols.PlainCol().In(f.PlainColIn...))
	}
	if f.PlainColLike != nil {
		w = append(w, CaseCols.PlainCol().Like(*f.PlainColLike))
	}
	if f.PlainColILike != nil {
		w = append(w, CaseCols.PlainCol().ILike(*f.PlainColILike))
	}
	w = append(w, f.Extra...)
	return w
}

// CaseColSet is the three-state UPDATE payload: a zero Set field
// skips its column, SetOf writes a value, SetNull writes NULL.
type CaseColSet struct {
	Email     Set[pgtype.Text]
	Mixedcase Set[pgtype.Int4]
	Caf       Set[pgtype.Text]
	PlainCol  Set[pgtype.Text]
}

// InsertCaseColParams carries the INSERT column values: generated
// and serial columns are out, default-bearing columns join only with
// the include_defaults option.
type InsertCaseColParams struct {
	Email     pgtype.Text
	Mixedcase pgtype.Int4
	Caf       pgtype.Text
	PlainCol  pgtype.Text
}

// scanCaseCol scans one row positionally over every column in
// catalog order — the single scan path for all generated reads.
func scanCaseCol(row pgx.CollectableRow) (CaseCol, error) {
	var m CaseCol
	if err := row.Scan(&m.ID, &m.Email, &m.Mixedcase, &m.Caf, &m.PlainCol); err != nil {
		return CaseCol{}, err
	}
	return m, nil
}

// GetCaseCol returns one row by id; core.ErrNotFound when absent
// (pgx.ErrNoRows mapped — errors.Is keeps working for both).
func GetCaseCol(ctx context.Context, exec core.DBTX, id int64) (CaseCol, error) {
	sql, args := CaseCols.Select().Where(CaseCols.ID().Eq(id)).SQL()
	var m CaseCol
	err := exec.QueryRow(ctx, sql, args...).Scan(&m.ID, &m.Email, &m.Mixedcase, &m.Caf, &m.PlainCol)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return CaseCol{}, core.ErrNotFound
		}
		return CaseCol{}, err
	}
	return m, nil
}

// ListCaseCols returns the rows matching f; limit <= 0 means no LIMIT.
func ListCaseCols(ctx context.Context, exec core.DBTX, f CaseColFilter, limit int) ([]CaseCol, error) {
	rows, err := CaseCols.Select().Where(caseColsFilterWhere(f)...).Limit(limit).Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanCaseCol)
}

// CountCaseCols counts the rows matching f.
func CountCaseCols(ctx context.Context, exec core.DBTX, f CaseColFilter) (int64, error) {
	sql, args := core.NewSelect("public.case_cols", core.Raw{SQL: "count(*)"}).Where(caseColsFilterWhere(f)...).SQL()
	var n int64
	if err := exec.QueryRow(ctx, sql, args...).Scan(&n); err != nil {
		return 0, err
	}
	return n, nil
}

// InsertCaseCol inserts one row and returns it (RETURNING every
// column, defaults included).
func InsertCaseCol(ctx context.Context, exec core.DBTX, p InsertCaseColParams) (CaseCol, error) {
	rows, err := core.NewInsert("public.case_cols",
		[]string{"Email", "mixedcase", "café", "plain_col"},
		[]core.Expr{core.Lit{V: p.Email}, core.Lit{V: p.Mixedcase}, core.Lit{V: p.Caf}, core.Lit{V: p.PlainCol}},
	).Returning(core.Col{Table: "case_cols", Name: "id"}, core.Col{Table: "case_cols", Name: "Email"}, core.Col{Table: "case_cols", Name: "mixedcase"}, core.Col{Table: "case_cols", Name: "café"}, core.Col{Table: "case_cols", Name: "plain_col"}).Run(ctx, exec)
	if err != nil {
		return CaseCol{}, err
	}
	us, err := pgx.CollectRows(rows, scanCaseCol)
	if err != nil {
		return CaseCol{}, err
	}
	if len(us) == 0 {
		return CaseCol{}, core.ErrNotFound
	}
	return us[0], nil
}

const insertCaseColsSQL = "INSERT INTO public.case_cols (\"Email\", mixedcase, \"café\", plain_col) SELECT * FROM unnest($1::text[], $2::int4[], $3::text[], $4::text[]) RETURNING id, \"Email\", mixedcase, \"café\", plain_col"

// InsertCaseCols inserts a whole batch in one round trip via
// unnest and returns every inserted row.
func InsertCaseCols(ctx context.Context, exec core.DBTX, ps []InsertCaseColParams) ([]CaseCol, error) {
	if len(ps) == 0 {
		return nil, nil
	}
	colEmail := make([]pgtype.Text, len(ps))
	colMixedcase := make([]pgtype.Int4, len(ps))
	colCaf := make([]pgtype.Text, len(ps))
	colPlainCol := make([]pgtype.Text, len(ps))
	for i, p := range ps {
		colEmail[i] = p.Email
		colMixedcase[i] = p.Mixedcase
		colCaf[i] = p.Caf
		colPlainCol[i] = p.PlainCol
	}
	args := make([]any, 0, 4*len(ps))
	args = append(args, colEmail, colMixedcase, colCaf, colPlainCol)
	rows, err := exec.Query(ctx, insertCaseColsSQL, args...)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanCaseCol)
}

// UpdateCaseCol applies the non-zero fields of s to one row and
// returns the updated row; core.ErrNotFound when absent.
func UpdateCaseCol(ctx context.Context, exec core.DBTX, id int64, s CaseColSet) (CaseCol, error) {
	u := CaseCols.Update()
	n := 0
	if s.Email.Valid {
		n++
		if s.Email.Null {
			u.Set("Email", core.Lit{V: nil})
		} else {
			u.Set("Email", core.Lit{V: s.Email.V})
		}
	}
	if s.Mixedcase.Valid {
		n++
		if s.Mixedcase.Null {
			u.Set("mixedcase", core.Lit{V: nil})
		} else {
			u.Set("mixedcase", core.Lit{V: s.Mixedcase.V})
		}
	}
	if s.Caf.Valid {
		n++
		if s.Caf.Null {
			u.Set("café", core.Lit{V: nil})
		} else {
			u.Set("café", core.Lit{V: s.Caf.V})
		}
	}
	if s.PlainCol.Valid {
		n++
		if s.PlainCol.Null {
			u.Set("plain_col", core.Lit{V: nil})
		} else {
			u.Set("plain_col", core.Lit{V: s.PlainCol.V})
		}
	}
	if n == 0 {
		return GetCaseCol(ctx, exec, id)
	}
	u.Where(CaseCols.ID().Eq(id)).Returning(core.Col{Table: "case_cols", Name: "id"}, core.Col{Table: "case_cols", Name: "Email"}, core.Col{Table: "case_cols", Name: "mixedcase"}, core.Col{Table: "case_cols", Name: "café"}, core.Col{Table: "case_cols", Name: "plain_col"})
	rows, err := u.Run(ctx, exec)
	if err != nil {
		return CaseCol{}, err
	}
	us, err := pgx.CollectRows(rows, scanCaseCol)
	if err != nil {
		return CaseCol{}, err
	}
	if len(us) == 0 {
		return CaseCol{}, core.ErrNotFound
	}
	return us[0], nil
}

// UpdateCaseCols applies s to every row matching where and
// returns the affected count; an empty where is refused with
// core.ErrNoWhere before any SQL is sent.
func UpdateCaseCols(ctx context.Context, exec core.DBTX, where []core.Expr, s CaseColSet) (int64, error) {
	u := CaseCols.Update()
	n := 0
	if s.Email.Valid {
		n++
		if s.Email.Null {
			u.Set("Email", core.Lit{V: nil})
		} else {
			u.Set("Email", core.Lit{V: s.Email.V})
		}
	}
	if s.Mixedcase.Valid {
		n++
		if s.Mixedcase.Null {
			u.Set("mixedcase", core.Lit{V: nil})
		} else {
			u.Set("mixedcase", core.Lit{V: s.Mixedcase.V})
		}
	}
	if s.Caf.Valid {
		n++
		if s.Caf.Null {
			u.Set("café", core.Lit{V: nil})
		} else {
			u.Set("café", core.Lit{V: s.Caf.V})
		}
	}
	if s.PlainCol.Valid {
		n++
		if s.PlainCol.Null {
			u.Set("plain_col", core.Lit{V: nil})
		} else {
			u.Set("plain_col", core.Lit{V: s.PlainCol.V})
		}
	}
	if n == 0 {
		return 0, nil
	}
	if len(where) == 0 {
		return 0, core.ErrNoWhere
	}
	u.Where(where...)
	tag, err := u.Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// UpsertCaseCol inserts p under id, or on conflict updates
// every settable column from the proposed row (EXCLUDED.*) and returns
// the resulting row; core.ErrNotFound when DO NOTHING matched.
func UpsertCaseCol(ctx context.Context, exec core.DBTX, id int64, p InsertCaseColParams) (CaseCol, error) {
	rows, err := core.NewInsert("public.case_cols",
		[]string{"id", "Email", "mixedcase", "café", "plain_col"},
		[]core.Expr{core.Lit{V: id}, core.Lit{V: p.Email}, core.Lit{V: p.Mixedcase}, core.Lit{V: p.Caf}, core.Lit{V: p.PlainCol}},
	).OnConflict(core.OnConflict{
		Target: []string{"id"},
		Sets: []core.SetClause{
			{Col: "Email", E: core.Col{Table: "excluded", Name: "Email"}},
			{Col: "mixedcase", E: core.Col{Table: "excluded", Name: "mixedcase"}},
			{Col: "café", E: core.Col{Table: "excluded", Name: "café"}},
			{Col: "plain_col", E: core.Col{Table: "excluded", Name: "plain_col"}},
		},
	}).Returning(core.Col{Table: "case_cols", Name: "id"}, core.Col{Table: "case_cols", Name: "Email"}, core.Col{Table: "case_cols", Name: "mixedcase"}, core.Col{Table: "case_cols", Name: "café"}, core.Col{Table: "case_cols", Name: "plain_col"}).Run(ctx, exec)
	if err != nil {
		return CaseCol{}, err
	}
	us, err := pgx.CollectRows(rows, scanCaseCol)
	if err != nil {
		return CaseCol{}, err
	}
	if len(us) == 0 {
		return CaseCol{}, core.ErrNotFound
	}
	return us[0], nil
}

// DeleteCaseCol removes one row by id.
func DeleteCaseCol(ctx context.Context, exec core.DBTX, id int64) error {
	_, err := CaseCols.Delete().Where(CaseCols.ID().Eq(id)).Exec(ctx, exec)
	return err
}

// DeleteCaseCols removes every row matching where and returns the
// affected count; an empty where is refused with core.ErrNoWhere.
func DeleteCaseCols(ctx context.Context, exec core.DBTX, where []core.Expr) (int64, error) {
	if len(where) == 0 {
		return 0, core.ErrNoWhere
	}
	tag, err := CaseCols.Delete().Where(where...).Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
