// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"errors"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	pgb "github.com/khoale-2804/pgb/core"
)

// CategoryFilter narrows ListCategories and CountCategories:
// nil / zero fields are ignored; Extra composes raw predicates.
type CategoryFilter struct {
	ID          *int64
	IDIn        []int64
	IDGt        *int64
	IDLt        *int64
	IDGte       *int64
	IDLte       *int64
	Name        *string
	NameIn      []string
	NameLike    *string
	NameILike   *string
	ParentID    *pgtype.Int8
	ParentIDIn  []pgtype.Int8
	ParentIDGt  *pgtype.Int8
	ParentIDLt  *pgtype.Int8
	ParentIDGte *pgtype.Int8
	ParentIDLte *pgtype.Int8
	Extra       []pgb.Expr
}

// categoriesFilterWhere compiles f into the ANDed predicate list; an empty
// filter yields an empty list (no WHERE).
func categoriesFilterWhere(f CategoryFilter) []pgb.Expr {
	var w []pgb.Expr
	if f.ID != nil {
		w = append(w, Categories.ID().Eq(*f.ID))
	}
	if len(f.IDIn) > 0 {
		w = append(w, Categories.ID().In(f.IDIn...))
	}
	if f.IDGt != nil {
		w = append(w, Categories.ID().Gt(*f.IDGt))
	}
	if f.IDLt != nil {
		w = append(w, Categories.ID().Lt(*f.IDLt))
	}
	if f.IDGte != nil {
		w = append(w, Categories.ID().Gte(*f.IDGte))
	}
	if f.IDLte != nil {
		w = append(w, Categories.ID().Lte(*f.IDLte))
	}
	if f.Name != nil {
		w = append(w, Categories.Name().Eq(*f.Name))
	}
	if len(f.NameIn) > 0 {
		w = append(w, Categories.Name().In(f.NameIn...))
	}
	if f.NameLike != nil {
		w = append(w, Categories.Name().Like(*f.NameLike))
	}
	if f.NameILike != nil {
		w = append(w, Categories.Name().ILike(*f.NameILike))
	}
	if f.ParentID != nil {
		w = append(w, Categories.ParentID().Eq(*f.ParentID))
	}
	if len(f.ParentIDIn) > 0 {
		w = append(w, Categories.ParentID().In(f.ParentIDIn...))
	}
	if f.ParentIDGt != nil {
		w = append(w, Categories.ParentID().Gt(*f.ParentIDGt))
	}
	if f.ParentIDLt != nil {
		w = append(w, Categories.ParentID().Lt(*f.ParentIDLt))
	}
	if f.ParentIDGte != nil {
		w = append(w, Categories.ParentID().Gte(*f.ParentIDGte))
	}
	if f.ParentIDLte != nil {
		w = append(w, Categories.ParentID().Lte(*f.ParentIDLte))
	}
	w = append(w, f.Extra...)
	return w
}

// CategorySet is the three-state UPDATE payload: a zero Set field
// skips its column, SetOf writes a value, SetNull writes NULL.
type CategorySet struct {
	Name     Set[string]
	ParentID Set[pgtype.Int8]
}

// InsertCategoryParams carries the INSERT column values: generated
// and serial columns are out, default-bearing columns join only with
// the include_defaults option.
type InsertCategoryParams struct {
	Name     string
	ParentID pgtype.Int8
}

// scanCategory scans one row positionally over every column in
// catalog order — the single scan path for all generated reads.
func scanCategory(row pgx.CollectableRow) (Category, error) {
	var m Category
	if err := row.Scan(&m.ID, &m.Name, &m.ParentID); err != nil {
		return Category{}, err
	}
	return m, nil
}

// GetCategory returns one row by id; pgb.ErrNotFound when absent
// (pgx.ErrNoRows mapped — errors.Is keeps working for both).
func GetCategory(ctx context.Context, exec pgb.DBTX, id int64) (Category, error) {
	sql, args := Categories.Select().Where(Categories.ID().Eq(id)).SQL()
	var m Category
	err := exec.QueryRow(ctx, sql, args...).Scan(&m.ID, &m.Name, &m.ParentID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Category{}, pgb.ErrNotFound
		}
		return Category{}, err
	}
	return m, nil
}

// ListCategories returns the rows matching f; limit <= 0 means no LIMIT.
func ListCategories(ctx context.Context, exec pgb.DBTX, f CategoryFilter, opts ...pgb.ListOpt) ([]Category, error) {
	sel := Categories.Select().Where(categoriesFilterWhere(f)...).ApplyList(opts...)
	rows, err := sel.Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanCategory)
}

// CountCategories counts the rows matching f.
func CountCategories(ctx context.Context, exec pgb.DBTX, f CategoryFilter) (int64, error) {
	sql, args := pgb.NewSelect("public.categories", pgb.Raw{SQL: "count(*)"}).Where(categoriesFilterWhere(f)...).SQL()
	var n int64
	if err := exec.QueryRow(ctx, sql, args...).Scan(&n); err != nil {
		return 0, err
	}
	return n, nil
}

// InsertCategory inserts one row and returns it (RETURNING every
// column, defaults included).
func InsertCategory(ctx context.Context, exec pgb.DBTX, p InsertCategoryParams) (Category, error) {
	rows, err := pgb.NewInsert("public.categories",
		[]string{"name", "parent_id"},
		[]pgb.Expr{pgb.Lit{V: p.Name}, pgb.Lit{V: p.ParentID}},
	).Returning(pgb.Col{Table: "categories", Name: "id"}, pgb.Col{Table: "categories", Name: "name"}, pgb.Col{Table: "categories", Name: "parent_id"}).Run(ctx, exec)
	if err != nil {
		return Category{}, err
	}
	us, err := pgx.CollectRows(rows, scanCategory)
	if err != nil {
		return Category{}, err
	}
	if len(us) == 0 {
		return Category{}, pgb.ErrNotFound
	}
	return us[0], nil
}

const insertCategoriesSQL = "INSERT INTO public.categories (name, parent_id) SELECT * FROM unnest($1::text[], $2::int8[]) RETURNING id, name, parent_id"

// InsertCategories inserts a whole batch in one round trip via
// unnest and returns every inserted row.
func InsertCategories(ctx context.Context, exec pgb.DBTX, ps []InsertCategoryParams) ([]Category, error) {
	if len(ps) == 0 {
		return nil, nil
	}
	colName := make([]string, len(ps))
	colParentID := make([]pgtype.Int8, len(ps))
	for i, p := range ps {
		colName[i] = p.Name
		colParentID[i] = p.ParentID
	}
	args := make([]any, 0, 2*len(ps))
	args = append(args, colName, colParentID)
	rows, err := exec.Query(ctx, insertCategoriesSQL, args...)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanCategory)
}

// UpdateCategory applies the non-zero fields of s to one row and
// returns the updated row; pgb.ErrNotFound when absent.
func UpdateCategory(ctx context.Context, exec pgb.DBTX, id int64, s CategorySet) (Category, error) {
	u := Categories.Update()
	n := 0
	if s.Name.Valid {
		n++
		if s.Name.Null {
			u.Set("name", pgb.Lit{V: nil})
		} else {
			u.Set("name", pgb.Lit{V: s.Name.V})
		}
	}
	if s.ParentID.Valid {
		n++
		if s.ParentID.Null {
			u.Set("parent_id", pgb.Lit{V: nil})
		} else {
			u.Set("parent_id", pgb.Lit{V: s.ParentID.V})
		}
	}
	if n == 0 {
		return GetCategory(ctx, exec, id)
	}
	u.Where(Categories.ID().Eq(id)).Returning(pgb.Col{Table: "categories", Name: "id"}, pgb.Col{Table: "categories", Name: "name"}, pgb.Col{Table: "categories", Name: "parent_id"})
	rows, err := u.Run(ctx, exec)
	if err != nil {
		return Category{}, err
	}
	us, err := pgx.CollectRows(rows, scanCategory)
	if err != nil {
		return Category{}, err
	}
	if len(us) == 0 {
		return Category{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// UpdateCategories applies s to every row matching where and
// returns the affected count; an empty where is refused with
// pgb.ErrNoWhere before any SQL is sent.
func UpdateCategories(ctx context.Context, exec pgb.DBTX, where []pgb.Expr, s CategorySet) (int64, error) {
	u := Categories.Update()
	n := 0
	if s.Name.Valid {
		n++
		if s.Name.Null {
			u.Set("name", pgb.Lit{V: nil})
		} else {
			u.Set("name", pgb.Lit{V: s.Name.V})
		}
	}
	if s.ParentID.Valid {
		n++
		if s.ParentID.Null {
			u.Set("parent_id", pgb.Lit{V: nil})
		} else {
			u.Set("parent_id", pgb.Lit{V: s.ParentID.V})
		}
	}
	if n == 0 {
		return 0, nil
	}
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	u.Where(where...)
	tag, err := u.Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// UpsertCategory inserts p under id, or on conflict updates
// every settable column from the proposed row (EXCLUDED.*) and returns
// the resulting row; pgb.ErrNotFound when DO NOTHING matched.
func UpsertCategory(ctx context.Context, exec pgb.DBTX, id int64, p InsertCategoryParams) (Category, error) {
	rows, err := pgb.NewInsert("public.categories",
		[]string{"id", "name", "parent_id"},
		[]pgb.Expr{pgb.Lit{V: id}, pgb.Lit{V: p.Name}, pgb.Lit{V: p.ParentID}},
	).OnConflict(pgb.OnConflict{
		Target: []string{"id"},
		Sets: []pgb.SetClause{
			{Col: "name", E: pgb.Col{Table: "excluded", Name: "name"}},
			{Col: "parent_id", E: pgb.Col{Table: "excluded", Name: "parent_id"}},
		},
	}).Returning(pgb.Col{Table: "categories", Name: "id"}, pgb.Col{Table: "categories", Name: "name"}, pgb.Col{Table: "categories", Name: "parent_id"}).Run(ctx, exec)
	if err != nil {
		return Category{}, err
	}
	us, err := pgx.CollectRows(rows, scanCategory)
	if err != nil {
		return Category{}, err
	}
	if len(us) == 0 {
		return Category{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// DeleteCategory removes one row by id.
func DeleteCategory(ctx context.Context, exec pgb.DBTX, id int64) error {
	_, err := Categories.Delete().Where(Categories.ID().Eq(id)).Exec(ctx, exec)
	return err
}

// DeleteCategories removes every row matching where and returns the
// affected count; an empty where is refused with pgb.ErrNoWhere.
func DeleteCategories(ctx context.Context, exec pgb.DBTX, where []pgb.Expr) (int64, error) {
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	tag, err := Categories.Delete().Where(where...).Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
