// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	core "github.com/khoale-2804/pgb/core"
)

// Categories is the table descriptor for public.categories; immutable, safe for
// concurrent use.
var Categories = CategoryTable{core.NewTableMeta("public", "categories")}

// CategoryTable provides typed column accessors and statement entry points.
type CategoryTable struct{ core.TableMeta }

// ID returns the typed accessor for column id.
func (t CategoryTable) ID() CategoryIDCol {
	return CategoryIDCol{core.Col{Table: "categories", Name: "id"}}
}

// CategoryIDCol is the typed column categories.id.
type CategoryIDCol struct{ core.Col }

func (c CategoryIDCol) Eq(v int64) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryIDCol) Ne(v int64) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryIDCol) In(vs ...int64) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "bigserial[]"}}
}

func (c CategoryIDCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c CategoryIDCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c CategoryIDCol) Gt(v int64) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryIDCol) Lt(v int64) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryIDCol) Gte(v int64) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryIDCol) Lte(v int64) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryIDCol) Between(a, b int64) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// Name returns the typed accessor for column name.
func (t CategoryTable) Name() CategoryNameCol {
	return CategoryNameCol{core.Col{Table: "categories", Name: "name"}}
}

// CategoryNameCol is the typed column categories.name.
type CategoryNameCol struct{ core.Col }

func (c CategoryNameCol) Eq(v string) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryNameCol) Ne(v string) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryNameCol) In(vs ...string) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "text[]"}}
}

func (c CategoryNameCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c CategoryNameCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c CategoryNameCol) Like(p string) core.Expr {
	return core.Bin{Op: "LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c CategoryNameCol) ILike(p string) core.Expr {
	return core.Bin{Op: "ILIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c CategoryNameCol) NotLike(p string) core.Expr {
	return core.Bin{Op: "NOT LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c CategoryNameCol) NotILike(p string) core.Expr {
	return core.Bin{Op: "NOT ILIKE", L: c.Col, R: core.Lit{V: p}}
}

// ParentID returns the typed accessor for column parent_id.
func (t CategoryTable) ParentID() CategoryParentIDCol {
	return CategoryParentIDCol{core.Col{Table: "categories", Name: "parent_id"}}
}

// CategoryParentIDCol is the typed column categories.parent_id.
type CategoryParentIDCol struct{ core.Col }

func (c CategoryParentIDCol) Eq(v pgtype.Int8) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryParentIDCol) Ne(v pgtype.Int8) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryParentIDCol) In(vs ...pgtype.Int8) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "int8[]"}}
}

func (c CategoryParentIDCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c CategoryParentIDCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c CategoryParentIDCol) Gt(v pgtype.Int8) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryParentIDCol) Lt(v pgtype.Int8) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryParentIDCol) Gte(v pgtype.Int8) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryParentIDCol) Lte(v pgtype.Int8) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c CategoryParentIDCol) Between(a, b pgtype.Int8) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// Select starts a SELECT of every column; chain Where/OrderBy/Limit/...
// and terminate with Run (or a static function).
func (t CategoryTable) Select() *core.Select {
	return core.NewSelect("public.categories", core.Col{Table: "categories", Name: "id"}, core.Col{Table: "categories", Name: "name"}, core.Col{Table: "categories", Name: "parent_id"})
}

// Update starts an UPDATE; an empty WHERE fails with core.ErrNoWhere.
func (t CategoryTable) Update() *core.Update { return core.NewUpdate("public.categories") }

// Delete starts a DELETE; an empty WHERE fails with core.ErrNoWhere.
func (t CategoryTable) Delete() *core.Delete { return core.NewDelete("public.categories") }
