// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgb "github.com/khoale-2804/pgb/core"
)

// Categories is the table descriptor for public.categories; immutable, safe for
// concurrent use.
var Categories = CategoryTable{pgb.NewTableMeta("public", "categories")}

// CategoryTable provides typed column accessors and statement entry points.
type CategoryTable struct{ pgb.TableMeta }

// ID returns the typed accessor for column id.
func (t CategoryTable) ID() CategoryIDCol {
	return CategoryIDCol{pgb.Col{Table: "categories", Name: "id"}}
}

// CategoryIDCol is the typed column categories.id.
type CategoryIDCol struct{ pgb.Col }

func (c CategoryIDCol) Eq(v int64) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryIDCol) Ne(v int64) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryIDCol) In(vs ...int64) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "int8[]" + ")", Args: []any{vs}}
}

func (c CategoryIDCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c CategoryIDCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c CategoryIDCol) Gt(v int64) pgb.Expr {
	return pgb.Bin{Op: ">", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryIDCol) Lt(v int64) pgb.Expr {
	return pgb.Bin{Op: "<", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryIDCol) Gte(v int64) pgb.Expr {
	return pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryIDCol) Lte(v int64) pgb.Expr {
	return pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryIDCol) Between(a, b int64) pgb.Expr {
	return pgb.And{Parts: []pgb.Expr{
		pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: a}},
		pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: b}},
	}}
}

// Name returns the typed accessor for column name.
func (t CategoryTable) Name() CategoryNameCol {
	return CategoryNameCol{pgb.Col{Table: "categories", Name: "name"}}
}

// CategoryNameCol is the typed column categories.name.
type CategoryNameCol struct{ pgb.Col }

func (c CategoryNameCol) Eq(v string) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryNameCol) Ne(v string) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryNameCol) In(vs ...string) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c CategoryNameCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c CategoryNameCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c CategoryNameCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c CategoryNameCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c CategoryNameCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c CategoryNameCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// ParentID returns the typed accessor for column parent_id.
func (t CategoryTable) ParentID() CategoryParentIDCol {
	return CategoryParentIDCol{pgb.Col{Table: "categories", Name: "parent_id"}}
}

// CategoryParentIDCol is the typed column categories.parent_id.
type CategoryParentIDCol struct{ pgb.Col }

func (c CategoryParentIDCol) Eq(v pgtype.Int8) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryParentIDCol) Ne(v pgtype.Int8) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryParentIDCol) In(vs ...pgtype.Int8) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "int8[]" + ")", Args: []any{vs}}
}

func (c CategoryParentIDCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c CategoryParentIDCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c CategoryParentIDCol) Gt(v pgtype.Int8) pgb.Expr {
	return pgb.Bin{Op: ">", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryParentIDCol) Lt(v pgtype.Int8) pgb.Expr {
	return pgb.Bin{Op: "<", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryParentIDCol) Gte(v pgtype.Int8) pgb.Expr {
	return pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryParentIDCol) Lte(v pgtype.Int8) pgb.Expr {
	return pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c CategoryParentIDCol) Between(a, b pgtype.Int8) pgb.Expr {
	return pgb.And{Parts: []pgb.Expr{
		pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: a}},
		pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: b}},
	}}
}

// Select starts a SELECT of every column; chain Where/OrderBy/Limit/...
// and terminate with Run (or a static function).
func (t CategoryTable) Select() *pgb.Select {
	return pgb.NewSelect("public.categories", pgb.Col{Table: "categories", Name: "id"}, pgb.Col{Table: "categories", Name: "name"}, pgb.Col{Table: "categories", Name: "parent_id"})
}

// Update starts an UPDATE; an empty WHERE fails with pgb.ErrNoWhere.
func (t CategoryTable) Update() *pgb.Update { return pgb.NewUpdate("public.categories") }

// Delete starts a DELETE; an empty WHERE fails with pgb.ErrNoWhere.
func (t CategoryTable) Delete() *pgb.Delete { return pgb.NewDelete("public.categories") }
