// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	core "github.com/khoale-2804/pgb/core"
)

// Docs is the table descriptor for public.docs; immutable, safe for
// concurrent use.
var Docs = DocTable{core.NewTableMeta("public", "docs")}

// DocTable provides typed column accessors and statement entry points.
type DocTable struct{ core.TableMeta }

// ID returns the typed accessor for column id.
func (t DocTable) ID() DocIDCol {
	return DocIDCol{core.Col{Table: "docs", Name: "id"}}
}

// DocIDCol is the typed column docs.id.
type DocIDCol struct{ core.Col }

func (c DocIDCol) Eq(v uuid.UUID) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c DocIDCol) Ne(v uuid.UUID) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c DocIDCol) In(vs ...uuid.UUID) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "uuid[]"}}
}

func (c DocIDCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c DocIDCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

// Title returns the typed accessor for column title.
func (t DocTable) Title() DocTitleCol {
	return DocTitleCol{core.Col{Table: "docs", Name: "title"}}
}

// DocTitleCol is the typed column docs.title.
type DocTitleCol struct{ core.Col }

func (c DocTitleCol) Eq(v string) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c DocTitleCol) Ne(v string) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c DocTitleCol) In(vs ...string) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "text[]"}}
}

func (c DocTitleCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c DocTitleCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c DocTitleCol) Like(p string) core.Expr {
	return core.Bin{Op: "LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c DocTitleCol) ILike(p string) core.Expr {
	return core.Bin{Op: "ILIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c DocTitleCol) NotLike(p string) core.Expr {
	return core.Bin{Op: "NOT LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c DocTitleCol) NotILike(p string) core.Expr {
	return core.Bin{Op: "NOT ILIKE", L: c.Col, R: core.Lit{V: p}}
}

// Body returns the typed accessor for column body.
func (t DocTable) Body() DocBodyCol {
	return DocBodyCol{core.Col{Table: "docs", Name: "body"}}
}

// DocBodyCol is the typed column docs.body.
type DocBodyCol struct{ core.Col }

func (c DocBodyCol) Eq(v string) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c DocBodyCol) Ne(v string) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c DocBodyCol) In(vs ...string) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "text[]"}}
}

func (c DocBodyCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c DocBodyCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c DocBodyCol) Like(p string) core.Expr {
	return core.Bin{Op: "LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c DocBodyCol) ILike(p string) core.Expr {
	return core.Bin{Op: "ILIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c DocBodyCol) NotLike(p string) core.Expr {
	return core.Bin{Op: "NOT LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c DocBodyCol) NotILike(p string) core.Expr {
	return core.Bin{Op: "NOT ILIKE", L: c.Col, R: core.Lit{V: p}}
}

// Select starts a SELECT of every column; chain Where/OrderBy/Limit/...
// and terminate with Run (or a static function).
func (t DocTable) Select() *core.Select {
	return core.NewSelect("public.docs", core.Col{Table: "docs", Name: "id"}, core.Col{Table: "docs", Name: "title"}, core.Col{Table: "docs", Name: "body"})
}

// Update starts an UPDATE; an empty WHERE fails with core.ErrNoWhere.
func (t DocTable) Update() *core.Update { return core.NewUpdate("public.docs") }

// Delete starts a DELETE; an empty WHERE fails with core.ErrNoWhere.
func (t DocTable) Delete() *core.Delete { return core.NewDelete("public.docs") }
