// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"errors"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	pgb "github.com/khoale-2804/pgb/core"
)

// DocFilter narrows ListDocs and CountDocs:
// nil / zero fields are ignored; Extra composes raw predicates.
type DocFilter struct {
	ID         *uuid.UUID
	IDIn       []uuid.UUID
	Title      *string
	TitleIn    []string
	TitleLike  *string
	TitleILike *string
	Body       *string
	BodyIn     []string
	BodyLike   *string
	BodyILike  *string
	Extra      []pgb.Expr
}

// docsFilterWhere compiles f into the ANDed predicate list; an empty
// filter yields an empty list (no WHERE).
func docsFilterWhere(f DocFilter) []pgb.Expr {
	var w []pgb.Expr
	if f.ID != nil {
		w = append(w, Docs.ID().Eq(*f.ID))
	}
	if len(f.IDIn) > 0 {
		w = append(w, Docs.ID().In(f.IDIn...))
	}
	if f.Title != nil {
		w = append(w, Docs.Title().Eq(*f.Title))
	}
	if len(f.TitleIn) > 0 {
		w = append(w, Docs.Title().In(f.TitleIn...))
	}
	if f.TitleLike != nil {
		w = append(w, Docs.Title().Like(*f.TitleLike))
	}
	if f.TitleILike != nil {
		w = append(w, Docs.Title().ILike(*f.TitleILike))
	}
	if f.Body != nil {
		w = append(w, Docs.Body().Eq(*f.Body))
	}
	if len(f.BodyIn) > 0 {
		w = append(w, Docs.Body().In(f.BodyIn...))
	}
	if f.BodyLike != nil {
		w = append(w, Docs.Body().Like(*f.BodyLike))
	}
	if f.BodyILike != nil {
		w = append(w, Docs.Body().ILike(*f.BodyILike))
	}
	w = append(w, f.Extra...)
	return w
}

// DocSet is the three-state UPDATE payload: a zero Set field
// skips its column, SetOf writes a value, SetNull writes NULL.
type DocSet struct {
	Title Set[string]
	Body  Set[string]
}

// InsertDocParams carries the INSERT column values: generated
// and serial columns are out, default-bearing columns join only with
// the include_defaults option.
type InsertDocParams struct {
	ID    uuid.UUID
	Title string
	Body  string
}

// scanDoc scans one row positionally over every column in
// catalog order — the single scan path for all generated reads.
func scanDoc(row pgx.CollectableRow) (Doc, error) {
	var m Doc
	if err := row.Scan(&m.ID, &m.Title, &m.Body); err != nil {
		return Doc{}, err
	}
	return m, nil
}

// GetDoc returns one row by id; pgb.ErrNotFound when absent
// (pgx.ErrNoRows mapped — errors.Is keeps working for both).
func GetDoc(ctx context.Context, exec pgb.DBTX, id uuid.UUID) (Doc, error) {
	sql, args := Docs.Select().Where(Docs.ID().Eq(id)).SQL()
	var m Doc
	err := exec.QueryRow(ctx, sql, args...).Scan(&m.ID, &m.Title, &m.Body)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Doc{}, pgb.ErrNotFound
		}
		return Doc{}, err
	}
	return m, nil
}

// ListDocs returns the rows matching f; limit <= 0 means no LIMIT.
func ListDocs(ctx context.Context, exec pgb.DBTX, f DocFilter, opts ...pgb.ListOpt) ([]Doc, error) {
	sel := Docs.Select().Where(docsFilterWhere(f)...).ApplyList(opts...)
	rows, err := sel.Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanDoc)
}

// CountDocs counts the rows matching f.
func CountDocs(ctx context.Context, exec pgb.DBTX, f DocFilter) (int64, error) {
	sql, args := pgb.NewSelect("public.docs", pgb.Raw{SQL: "count(*)"}).Where(docsFilterWhere(f)...).SQL()
	var n int64
	if err := exec.QueryRow(ctx, sql, args...).Scan(&n); err != nil {
		return 0, err
	}
	return n, nil
}

// InsertDoc inserts one row and returns it (RETURNING every
// column, defaults included).
func InsertDoc(ctx context.Context, exec pgb.DBTX, p InsertDocParams) (Doc, error) {
	rows, err := pgb.NewInsert("public.docs",
		[]string{"id", "title", "body"},
		[]pgb.Expr{pgb.Lit{V: p.ID}, pgb.Lit{V: p.Title}, pgb.Lit{V: p.Body}},
	).Returning(pgb.Col{Table: "docs", Name: "id"}, pgb.Col{Table: "docs", Name: "title"}, pgb.Col{Table: "docs", Name: "body"}).Run(ctx, exec)
	if err != nil {
		return Doc{}, err
	}
	us, err := pgx.CollectRows(rows, scanDoc)
	if err != nil {
		return Doc{}, err
	}
	if len(us) == 0 {
		return Doc{}, pgb.ErrNotFound
	}
	return us[0], nil
}

const insertDocsSQL = "INSERT INTO public.docs (id, title, body) SELECT * FROM unnest($1::uuid[], $2::text[], $3::text[]) RETURNING id, title, body"

// InsertDocs inserts a whole batch in one round trip via
// unnest and returns every inserted row.
func InsertDocs(ctx context.Context, exec pgb.DBTX, ps []InsertDocParams) ([]Doc, error) {
	if len(ps) == 0 {
		return nil, nil
	}
	colID := make([]uuid.UUID, len(ps))
	colTitle := make([]string, len(ps))
	colBody := make([]string, len(ps))
	for i, p := range ps {
		colID[i] = p.ID
		colTitle[i] = p.Title
		colBody[i] = p.Body
	}
	args := make([]any, 0, 3*len(ps))
	args = append(args, colID, colTitle, colBody)
	rows, err := exec.Query(ctx, insertDocsSQL, args...)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanDoc)
}

// UpdateDoc applies the non-zero fields of s to one row and
// returns the updated row; pgb.ErrNotFound when absent.
func UpdateDoc(ctx context.Context, exec pgb.DBTX, id uuid.UUID, s DocSet) (Doc, error) {
	u := Docs.Update()
	n := 0
	if s.Title.Valid {
		n++
		if s.Title.Null {
			u.Set("title", pgb.Lit{V: nil})
		} else {
			u.Set("title", pgb.Lit{V: s.Title.V})
		}
	}
	if s.Body.Valid {
		n++
		if s.Body.Null {
			u.Set("body", pgb.Lit{V: nil})
		} else {
			u.Set("body", pgb.Lit{V: s.Body.V})
		}
	}
	if n == 0 {
		return GetDoc(ctx, exec, id)
	}
	u.Where(Docs.ID().Eq(id)).Returning(pgb.Col{Table: "docs", Name: "id"}, pgb.Col{Table: "docs", Name: "title"}, pgb.Col{Table: "docs", Name: "body"})
	rows, err := u.Run(ctx, exec)
	if err != nil {
		return Doc{}, err
	}
	us, err := pgx.CollectRows(rows, scanDoc)
	if err != nil {
		return Doc{}, err
	}
	if len(us) == 0 {
		return Doc{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// UpdateDocs applies s to every row matching where and
// returns the affected count; an empty where is refused with
// pgb.ErrNoWhere before any SQL is sent.
func UpdateDocs(ctx context.Context, exec pgb.DBTX, where []pgb.Expr, s DocSet) (int64, error) {
	u := Docs.Update()
	n := 0
	if s.Title.Valid {
		n++
		if s.Title.Null {
			u.Set("title", pgb.Lit{V: nil})
		} else {
			u.Set("title", pgb.Lit{V: s.Title.V})
		}
	}
	if s.Body.Valid {
		n++
		if s.Body.Null {
			u.Set("body", pgb.Lit{V: nil})
		} else {
			u.Set("body", pgb.Lit{V: s.Body.V})
		}
	}
	if n == 0 {
		return 0, nil
	}
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	u.Where(where...)
	tag, err := u.Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// UpsertDoc inserts p under id, or on conflict updates
// every settable column from the proposed row (EXCLUDED.*) and returns
// the resulting row; pgb.ErrNotFound when DO NOTHING matched.
func UpsertDoc(ctx context.Context, exec pgb.DBTX, id uuid.UUID, p InsertDocParams) (Doc, error) {
	rows, err := pgb.NewInsert("public.docs",
		[]string{"id", "title", "body"},
		[]pgb.Expr{pgb.Lit{V: id}, pgb.Lit{V: p.Title}, pgb.Lit{V: p.Body}},
	).OnConflict(pgb.OnConflict{
		Target: []string{"id"},
		Sets: []pgb.SetClause{
			{Col: "title", E: pgb.Col{Table: "excluded", Name: "title"}},
			{Col: "body", E: pgb.Col{Table: "excluded", Name: "body"}},
		},
	}).Returning(pgb.Col{Table: "docs", Name: "id"}, pgb.Col{Table: "docs", Name: "title"}, pgb.Col{Table: "docs", Name: "body"}).Run(ctx, exec)
	if err != nil {
		return Doc{}, err
	}
	us, err := pgx.CollectRows(rows, scanDoc)
	if err != nil {
		return Doc{}, err
	}
	if len(us) == 0 {
		return Doc{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// DeleteDoc removes one row by id.
func DeleteDoc(ctx context.Context, exec pgb.DBTX, id uuid.UUID) error {
	_, err := Docs.Delete().Where(Docs.ID().Eq(id)).Exec(ctx, exec)
	return err
}

// DeleteDocs removes every row matching where and returns the
// affected count; an empty where is refused with pgb.ErrNoWhere.
func DeleteDocs(ctx context.Context, exec pgb.DBTX, where []pgb.Expr) (int64, error) {
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	tag, err := Docs.Delete().Where(where...).Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
