// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	core "github.com/khoale-2804/pgb/core"
)

// Search surface for public.docs (index docs_search, key field id): predicate methods only
// on the columns the USING paradedb index covers, plus the scored document
// query. Every value stays a bound parameter; operator shapes live in
// core/search.go (the pg_search canon).
// Score ranks by the index key field: pdb.score(docs.id).
func (t DocTable) Score() core.Expr {
	return core.Score(core.Col{Table: "docs", Name: "id"})
}

func (c DocIDCol) Match(q string) core.Expr {
	return core.Match(c.Col, q)
}

func (c DocIDCol) MatchAll(q string) core.Expr {
	return core.MatchAll(c.Col, q)
}

func (c DocIDCol) Phrase(q string, slop int) core.Expr {
	return core.Phrase(c.Col, q, slop)
}

func (c DocIDCol) Exact(v any) core.Expr {
	return core.Exact(c.Col, v)
}

func (c DocIDCol) Fuzzy(q string, dist int, prefix bool) core.Expr {
	return core.Fuzzy(c.Col, q, dist, prefix)
}

func (c DocIDCol) Regex(pattern string) core.Expr {
	return core.Regex(c.Col, pattern)
}

func (c DocIDCol) Parse(q string) core.Expr {
	return core.Parse(c.Col, q, false)
}

func (c DocIDCol) MatchB(q string, b float64) core.Expr {
	return core.Boost(core.Match(c.Col, q), b)
}

func (c DocIDCol) Snippet(startTag, endTag string, maxChars int) core.Expr {
	return core.Snippet(c.Col, startTag, endTag, maxChars)
}

func (c DocIDCol) Snippets(limitN, offsetN int, sortBy string) core.Expr {
	return core.Snippets(c.Col, limitN, offsetN, sortBy)
}

func (c DocIDCol) Highlight() core.Expr {
	return core.Highlight(c.Col)
}

func (c DocTitleCol) Match(q string) core.Expr {
	return core.Match(c.Col, q)
}

func (c DocTitleCol) MatchAll(q string) core.Expr {
	return core.MatchAll(c.Col, q)
}

func (c DocTitleCol) Phrase(q string, slop int) core.Expr {
	return core.Phrase(c.Col, q, slop)
}

func (c DocTitleCol) Exact(v any) core.Expr {
	return core.Exact(c.Col, v)
}

func (c DocTitleCol) ExactAny(vs []string) core.Expr {
	return core.ExactAny(c.Col, vs, "text")
}

func (c DocTitleCol) Fuzzy(q string, dist int, prefix bool) core.Expr {
	return core.Fuzzy(c.Col, q, dist, prefix)
}

func (c DocTitleCol) Regex(pattern string) core.Expr {
	return core.Regex(c.Col, pattern)
}

func (c DocTitleCol) Parse(q string) core.Expr {
	return core.Parse(c.Col, q, false)
}

func (c DocTitleCol) MatchB(q string, b float64) core.Expr {
	return core.Boost(core.Match(c.Col, q), b)
}

func (c DocTitleCol) Snippet(startTag, endTag string, maxChars int) core.Expr {
	return core.Snippet(c.Col, startTag, endTag, maxChars)
}

func (c DocTitleCol) Snippets(limitN, offsetN int, sortBy string) core.Expr {
	return core.Snippets(c.Col, limitN, offsetN, sortBy)
}

func (c DocTitleCol) Highlight() core.Expr {
	return core.Highlight(c.Col)
}

func (c DocBodyCol) Match(q string) core.Expr {
	return core.Match(c.Col, q)
}

func (c DocBodyCol) MatchAll(q string) core.Expr {
	return core.MatchAll(c.Col, q)
}

func (c DocBodyCol) Phrase(q string, slop int) core.Expr {
	return core.Phrase(c.Col, q, slop)
}

func (c DocBodyCol) Exact(v any) core.Expr {
	return core.Exact(c.Col, v)
}

func (c DocBodyCol) ExactAny(vs []string) core.Expr {
	return core.ExactAny(c.Col, vs, "text")
}

func (c DocBodyCol) Fuzzy(q string, dist int, prefix bool) core.Expr {
	return core.Fuzzy(c.Col, q, dist, prefix)
}

func (c DocBodyCol) Regex(pattern string) core.Expr {
	return core.Regex(c.Col, pattern)
}

func (c DocBodyCol) Parse(q string) core.Expr {
	return core.Parse(c.Col, q, false)
}

func (c DocBodyCol) MatchB(q string, b float64) core.Expr {
	return core.Boost(core.Match(c.Col, q), b)
}

func (c DocBodyCol) Snippet(startTag, endTag string, maxChars int) core.Expr {
	return core.Snippet(c.Col, startTag, endTag, maxChars)
}

func (c DocBodyCol) Snippets(limitN, offsetN int, sortBy string) core.Expr {
	return core.Snippets(c.Col, limitN, offsetN, sortBy)
}

func (c DocBodyCol) Highlight() core.Expr {
	return core.Highlight(c.Col)
}

// SearchDocsOpts keeps the search entry surface small: Limit caps the
// result (<= 0 falls back to 20 — every generated search ends in an
// ordered LIMIT so ParadeDB can push Top-K down); SnippetCol optionally
// names one indexed column to project a pdb.snippet fragment for.
type SearchDocsOpts struct {
	Limit      int
	SnippetCol string
}

// DocHit is one SearchDocs result row: the full model, the BM25 score,
// and the snippet fragment (populated only when SearchDocsOpts.SnippetCol
// selected one, NULL/zero otherwise).
type DocHit struct {
	Product Doc
	Score   float64
	Snippet pgtype.Text
}

// ScanDocs scans one SearchDocs row positionally: every docs column
// in catalog order, then the score. Rows requested with a snippet
// projection carry one extra trailing column — SearchDocs scans those
// rows itself.
func ScanDocs(row pgx.CollectableRow) (DocHit, error) {
	var h DocHit
	var p Doc
	if err := row.Scan(&p.ID, &p.Title, &p.Body, &h.Score); err != nil {
		return DocHit{}, err
	}
	h.Product = p
	return h, nil
}

// SearchDocs runs the generic document query against the index key
// field: WHERE id @@@ pdb.parse($1) — pdb.parse carries ParadeDB's full
// query-string syntax — selecting every column plus pdb.score(id),
// optionally one pdb.snippet fragment, ordered pdb.score(id) DESC,
// id ASC and LIMIT-bounded.
func SearchDocs(ctx context.Context, exec core.DBTX, q string, o SearchDocsOpts) ([]DocHit, error) {
	limit := o.Limit
	if limit <= 0 {
		limit = 20
	}
	key := core.Col{Table: "docs", Name: "id"}
	cols := []core.Expr{core.Col{Table: "docs", Name: "id"}, core.Col{Table: "docs", Name: "title"}, core.Col{Table: "docs", Name: "body"}, core.Score(key)}
	if o.SnippetCol != "" {
		cols = append(cols, core.Snippet(core.Col{Table: "docs", Name: o.SnippetCol}, "", "", 0))
	}
	rows, err := core.NewSelect("public.docs", cols...).
		WhereExpr(core.Parse(key, q, false)).
		OrderBy(core.Desc(core.Score(key)), core.Asc(key)).
		Limit(limit).
		Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	if o.SnippetCol == "" {
		return pgx.CollectRows(rows, ScanDocs)
	}
	return pgx.CollectRows(rows, func(row pgx.CollectableRow) (DocHit, error) {
		var h DocHit
		var p Doc
		if err := row.Scan(&p.ID, &p.Title, &p.Body, &h.Score, &h.Snippet); err != nil {
			return DocHit{}, err
		}
		h.Product = p
		return h, nil
	})
}
