// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"errors"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	pgb "github.com/khoale-2804/pgb/core"
)

// EventsV2026H1Filter narrows ListEventsV2026H1s and CountEventsV2026H1s:
// nil / zero fields are ignored; Extra composes raw predicates.
type EventsV2026H1Filter struct {
	ID            *int64
	IDIn          []int64
	IDGt          *int64
	IDLt          *int64
	IDGte         *int64
	IDLte         *int64
	UserID        *int64
	UserIDIn      []int64
	UserIDGt      *int64
	UserIDLt      *int64
	UserIDGte     *int64
	UserIDLte     *int64
	Kind          *string
	KindIn        []string
	KindLike      *string
	KindILike     *string
	Payload       *[]byte
	OccurredAt    *pgtype.Timestamptz
	OccurredAtIn  []pgtype.Timestamptz
	OccurredAtGt  *pgtype.Timestamptz
	OccurredAtLt  *pgtype.Timestamptz
	OccurredAtGte *pgtype.Timestamptz
	OccurredAtLte *pgtype.Timestamptz
	Extra         []pgb.Expr
}

// eventsV2026H1sFilterWhere compiles f into the ANDed predicate list; an empty
// filter yields an empty list (no WHERE).
func eventsV2026H1sFilterWhere(f EventsV2026H1Filter) []pgb.Expr {
	var w []pgb.Expr
	if f.ID != nil {
		w = append(w, EventsV2026H1s.ID().Eq(*f.ID))
	}
	if len(f.IDIn) > 0 {
		w = append(w, EventsV2026H1s.ID().In(f.IDIn...))
	}
	if f.IDGt != nil {
		w = append(w, EventsV2026H1s.ID().Gt(*f.IDGt))
	}
	if f.IDLt != nil {
		w = append(w, EventsV2026H1s.ID().Lt(*f.IDLt))
	}
	if f.IDGte != nil {
		w = append(w, EventsV2026H1s.ID().Gte(*f.IDGte))
	}
	if f.IDLte != nil {
		w = append(w, EventsV2026H1s.ID().Lte(*f.IDLte))
	}
	if f.UserID != nil {
		w = append(w, EventsV2026H1s.UserID().Eq(*f.UserID))
	}
	if len(f.UserIDIn) > 0 {
		w = append(w, EventsV2026H1s.UserID().In(f.UserIDIn...))
	}
	if f.UserIDGt != nil {
		w = append(w, EventsV2026H1s.UserID().Gt(*f.UserIDGt))
	}
	if f.UserIDLt != nil {
		w = append(w, EventsV2026H1s.UserID().Lt(*f.UserIDLt))
	}
	if f.UserIDGte != nil {
		w = append(w, EventsV2026H1s.UserID().Gte(*f.UserIDGte))
	}
	if f.UserIDLte != nil {
		w = append(w, EventsV2026H1s.UserID().Lte(*f.UserIDLte))
	}
	if f.Kind != nil {
		w = append(w, EventsV2026H1s.Kind().Eq(*f.Kind))
	}
	if len(f.KindIn) > 0 {
		w = append(w, EventsV2026H1s.Kind().In(f.KindIn...))
	}
	if f.KindLike != nil {
		w = append(w, EventsV2026H1s.Kind().Like(*f.KindLike))
	}
	if f.KindILike != nil {
		w = append(w, EventsV2026H1s.Kind().ILike(*f.KindILike))
	}
	if f.Payload != nil {
		w = append(w, EventsV2026H1s.Payload().Eq(*f.Payload))
	}
	if f.OccurredAt != nil {
		w = append(w, EventsV2026H1s.OccurredAt().Eq(*f.OccurredAt))
	}
	if len(f.OccurredAtIn) > 0 {
		w = append(w, EventsV2026H1s.OccurredAt().In(f.OccurredAtIn...))
	}
	if f.OccurredAtGt != nil {
		w = append(w, EventsV2026H1s.OccurredAt().Gt(*f.OccurredAtGt))
	}
	if f.OccurredAtLt != nil {
		w = append(w, EventsV2026H1s.OccurredAt().Lt(*f.OccurredAtLt))
	}
	if f.OccurredAtGte != nil {
		w = append(w, EventsV2026H1s.OccurredAt().Gte(*f.OccurredAtGte))
	}
	if f.OccurredAtLte != nil {
		w = append(w, EventsV2026H1s.OccurredAt().Lte(*f.OccurredAtLte))
	}
	w = append(w, f.Extra...)
	return w
}

// EventsV2026H1Set is the three-state UPDATE payload: a zero Set field
// skips its column, SetOf writes a value, SetNull writes NULL.
type EventsV2026H1Set struct {
	UserID     Set[int64]
	Kind       Set[string]
	Payload    Set[[]byte]
	OccurredAt Set[pgtype.Timestamptz]
}

// InsertEventsV2026H1Params carries the INSERT column values: generated
// and serial columns are out, default-bearing columns join only with
// the include_defaults option.
type InsertEventsV2026H1Params struct {
	UserID     int64
	Kind       string
	Payload    []byte
	OccurredAt pgtype.Timestamptz
}

// scanEventsV2026H1 scans one row positionally over every column in
// catalog order — the single scan path for all generated reads.
func scanEventsV2026H1(row pgx.CollectableRow) (EventsV2026H1, error) {
	var m EventsV2026H1
	if err := row.Scan(&m.ID, &m.UserID, &m.Kind, &m.Payload, &m.OccurredAt); err != nil {
		return EventsV2026H1{}, err
	}
	return m, nil
}

// GetEventsV2026H1 returns one row by id; pgb.ErrNotFound when absent
// (pgx.ErrNoRows mapped — errors.Is keeps working for both).
func GetEventsV2026H1(ctx context.Context, exec pgb.DBTX, id int64) (EventsV2026H1, error) {
	sql, args := EventsV2026H1s.Select().Where(EventsV2026H1s.ID().Eq(id)).SQL()
	var m EventsV2026H1
	err := exec.QueryRow(ctx, sql, args...).Scan(&m.ID, &m.UserID, &m.Kind, &m.Payload, &m.OccurredAt)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return EventsV2026H1{}, pgb.ErrNotFound
		}
		return EventsV2026H1{}, err
	}
	return m, nil
}

// ListEventsV2026H1s returns the rows matching f; limit <= 0 means no LIMIT.
func ListEventsV2026H1s(ctx context.Context, exec pgb.DBTX, f EventsV2026H1Filter, opts ...pgb.ListOpt) ([]EventsV2026H1, error) {
	sel := EventsV2026H1s.Select().Where(eventsV2026H1sFilterWhere(f)...).ApplyList(opts...)
	rows, err := sel.Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanEventsV2026H1)
}

// CountEventsV2026H1s counts the rows matching f.
func CountEventsV2026H1s(ctx context.Context, exec pgb.DBTX, f EventsV2026H1Filter) (int64, error) {
	sql, args := pgb.NewSelect("public.events_2026h1", pgb.Raw{SQL: "count(*)"}).Where(eventsV2026H1sFilterWhere(f)...).SQL()
	var n int64
	if err := exec.QueryRow(ctx, sql, args...).Scan(&n); err != nil {
		return 0, err
	}
	return n, nil
}

// InsertEventsV2026H1 inserts one row and returns it (RETURNING every
// column, defaults included).
func InsertEventsV2026H1(ctx context.Context, exec pgb.DBTX, p InsertEventsV2026H1Params) (EventsV2026H1, error) {
	rows, err := pgb.NewInsert("public.events_2026h1",
		[]string{"user_id", "kind", "payload", "occurred_at"},
		[]pgb.Expr{pgb.Lit{V: p.UserID}, pgb.Lit{V: p.Kind}, pgb.Lit{V: p.Payload, Cast: "jsonb"}, pgb.Lit{V: p.OccurredAt}},
	).Returning(pgb.Col{Table: "events_2026h1", Name: "id"}, pgb.Col{Table: "events_2026h1", Name: "user_id"}, pgb.Col{Table: "events_2026h1", Name: "kind"}, pgb.Col{Table: "events_2026h1", Name: "payload"}, pgb.Col{Table: "events_2026h1", Name: "occurred_at"}).Run(ctx, exec)
	if err != nil {
		return EventsV2026H1{}, err
	}
	us, err := pgx.CollectRows(rows, scanEventsV2026H1)
	if err != nil {
		return EventsV2026H1{}, err
	}
	if len(us) == 0 {
		return EventsV2026H1{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// UpdateEventsV2026H1 applies the non-zero fields of s to one row and
// returns the updated row; pgb.ErrNotFound when absent.
func UpdateEventsV2026H1(ctx context.Context, exec pgb.DBTX, id int64, s EventsV2026H1Set) (EventsV2026H1, error) {
	u := EventsV2026H1s.Update()
	n := 0
	if s.UserID.Valid {
		n++
		if s.UserID.Null {
			u.Set("user_id", pgb.Lit{V: nil})
		} else {
			u.Set("user_id", pgb.Lit{V: s.UserID.V})
		}
	}
	if s.Kind.Valid {
		n++
		if s.Kind.Null {
			u.Set("kind", pgb.Lit{V: nil})
		} else {
			u.Set("kind", pgb.Lit{V: s.Kind.V})
		}
	}
	if s.Payload.Valid {
		n++
		if s.Payload.Null {
			u.Set("payload", pgb.Lit{V: nil})
		} else {
			u.Set("payload", pgb.Lit{V: s.Payload.V, Cast: "jsonb"})
		}
	}
	if s.OccurredAt.Valid {
		n++
		if s.OccurredAt.Null {
			u.Set("occurred_at", pgb.Lit{V: nil})
		} else {
			u.Set("occurred_at", pgb.Lit{V: s.OccurredAt.V})
		}
	}
	if n == 0 {
		return GetEventsV2026H1(ctx, exec, id)
	}
	u.Where(EventsV2026H1s.ID().Eq(id)).Returning(pgb.Col{Table: "events_2026h1", Name: "id"}, pgb.Col{Table: "events_2026h1", Name: "user_id"}, pgb.Col{Table: "events_2026h1", Name: "kind"}, pgb.Col{Table: "events_2026h1", Name: "payload"}, pgb.Col{Table: "events_2026h1", Name: "occurred_at"})
	rows, err := u.Run(ctx, exec)
	if err != nil {
		return EventsV2026H1{}, err
	}
	us, err := pgx.CollectRows(rows, scanEventsV2026H1)
	if err != nil {
		return EventsV2026H1{}, err
	}
	if len(us) == 0 {
		return EventsV2026H1{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// UpdateEventsV2026H1s applies s to every row matching where and
// returns the affected count; an empty where is refused with
// pgb.ErrNoWhere before any SQL is sent.
func UpdateEventsV2026H1s(ctx context.Context, exec pgb.DBTX, where []pgb.Expr, s EventsV2026H1Set) (int64, error) {
	u := EventsV2026H1s.Update()
	n := 0
	if s.UserID.Valid {
		n++
		if s.UserID.Null {
			u.Set("user_id", pgb.Lit{V: nil})
		} else {
			u.Set("user_id", pgb.Lit{V: s.UserID.V})
		}
	}
	if s.Kind.Valid {
		n++
		if s.Kind.Null {
			u.Set("kind", pgb.Lit{V: nil})
		} else {
			u.Set("kind", pgb.Lit{V: s.Kind.V})
		}
	}
	if s.Payload.Valid {
		n++
		if s.Payload.Null {
			u.Set("payload", pgb.Lit{V: nil})
		} else {
			u.Set("payload", pgb.Lit{V: s.Payload.V, Cast: "jsonb"})
		}
	}
	if s.OccurredAt.Valid {
		n++
		if s.OccurredAt.Null {
			u.Set("occurred_at", pgb.Lit{V: nil})
		} else {
			u.Set("occurred_at", pgb.Lit{V: s.OccurredAt.V})
		}
	}
	if n == 0 {
		return 0, nil
	}
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	u.Where(where...)
	tag, err := u.Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// UpsertEventsV2026H1 inserts p under id, or on conflict updates
// every settable column from the proposed row (EXCLUDED.*) and returns
// the resulting row; pgb.ErrNotFound when DO NOTHING matched.
func UpsertEventsV2026H1(ctx context.Context, exec pgb.DBTX, id int64, p InsertEventsV2026H1Params) (EventsV2026H1, error) {
	rows, err := pgb.NewInsert("public.events_2026h1",
		[]string{"id", "user_id", "kind", "payload", "occurred_at"},
		[]pgb.Expr{pgb.Lit{V: id}, pgb.Lit{V: p.UserID}, pgb.Lit{V: p.Kind}, pgb.Lit{V: p.Payload, Cast: "jsonb"}, pgb.Lit{V: p.OccurredAt}},
	).OnConflict(pgb.OnConflict{
		Target: []string{"id"},
		Sets: []pgb.SetClause{
			{Col: "user_id", E: pgb.Col{Table: "excluded", Name: "user_id"}},
			{Col: "kind", E: pgb.Col{Table: "excluded", Name: "kind"}},
			{Col: "payload", E: pgb.Col{Table: "excluded", Name: "payload"}},
			{Col: "occurred_at", E: pgb.Col{Table: "excluded", Name: "occurred_at"}},
		},
	}).Returning(pgb.Col{Table: "events_2026h1", Name: "id"}, pgb.Col{Table: "events_2026h1", Name: "user_id"}, pgb.Col{Table: "events_2026h1", Name: "kind"}, pgb.Col{Table: "events_2026h1", Name: "payload"}, pgb.Col{Table: "events_2026h1", Name: "occurred_at"}).Run(ctx, exec)
	if err != nil {
		return EventsV2026H1{}, err
	}
	us, err := pgx.CollectRows(rows, scanEventsV2026H1)
	if err != nil {
		return EventsV2026H1{}, err
	}
	if len(us) == 0 {
		return EventsV2026H1{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// DeleteEventsV2026H1 removes one row by id.
func DeleteEventsV2026H1(ctx context.Context, exec pgb.DBTX, id int64) error {
	_, err := EventsV2026H1s.Delete().Where(EventsV2026H1s.ID().Eq(id)).Exec(ctx, exec)
	return err
}

// DeleteEventsV2026H1s removes every row matching where and returns the
// affected count; an empty where is refused with pgb.ErrNoWhere.
func DeleteEventsV2026H1s(ctx context.Context, exec pgb.DBTX, where []pgb.Expr) (int64, error) {
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	tag, err := EventsV2026H1s.Delete().Where(where...).Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
