// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgb "github.com/khoale-2804/pgb/core"
)

// KeywordCols is the table descriptor for public.keyword_cols; immutable, safe for
// concurrent use.
var KeywordCols = KeywordColTable{pgb.NewTableMeta("public", "keyword_cols")}

// KeywordColTable provides typed column accessors and statement entry points.
type KeywordColTable struct{ pgb.TableMeta }

// ID returns the typed accessor for column id.
func (t KeywordColTable) ID() KeywordColIDCol {
	return KeywordColIDCol{pgb.Col{Table: "keyword_cols", Name: "id"}}
}

// KeywordColIDCol is the typed column keyword_cols.id.
type KeywordColIDCol struct{ pgb.Col }

func (c KeywordColIDCol) Eq(v int64) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColIDCol) Ne(v int64) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColIDCol) In(vs ...int64) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "int8[]" + ")", Args: []any{vs}}
}

func (c KeywordColIDCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c KeywordColIDCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c KeywordColIDCol) Gt(v int64) pgb.Expr {
	return pgb.Bin{Op: ">", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColIDCol) Lt(v int64) pgb.Expr {
	return pgb.Bin{Op: "<", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColIDCol) Gte(v int64) pgb.Expr {
	return pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColIDCol) Lte(v int64) pgb.Expr {
	return pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColIDCol) Between(a, b int64) pgb.Expr {
	return pgb.And{Parts: []pgb.Expr{
		pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: a}},
		pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: b}},
	}}
}

// Type returns the typed accessor for column type.
func (t KeywordColTable) Type() KeywordColTypeCol {
	return KeywordColTypeCol{pgb.Col{Table: "keyword_cols", Name: "type"}}
}

// KeywordColTypeCol is the typed column keyword_cols.type.
type KeywordColTypeCol struct{ pgb.Col }

func (c KeywordColTypeCol) Eq(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColTypeCol) Ne(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColTypeCol) In(vs ...pgtype.Text) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c KeywordColTypeCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c KeywordColTypeCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c KeywordColTypeCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColTypeCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColTypeCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColTypeCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// Range returns the typed accessor for column range.
func (t KeywordColTable) Range() KeywordColRangeCol {
	return KeywordColRangeCol{pgb.Col{Table: "keyword_cols", Name: "range"}}
}

// KeywordColRangeCol is the typed column keyword_cols.range.
type KeywordColRangeCol struct{ pgb.Col }

func (c KeywordColRangeCol) Eq(v pgtype.Int4) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColRangeCol) Ne(v pgtype.Int4) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColRangeCol) In(vs ...pgtype.Int4) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "int4[]" + ")", Args: []any{vs}}
}

func (c KeywordColRangeCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c KeywordColRangeCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c KeywordColRangeCol) Gt(v pgtype.Int4) pgb.Expr {
	return pgb.Bin{Op: ">", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColRangeCol) Lt(v pgtype.Int4) pgb.Expr {
	return pgb.Bin{Op: "<", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColRangeCol) Gte(v pgtype.Int4) pgb.Expr {
	return pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColRangeCol) Lte(v pgtype.Int4) pgb.Expr {
	return pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColRangeCol) Between(a, b pgtype.Int4) pgb.Expr {
	return pgb.And{Parts: []pgb.Expr{
		pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: a}},
		pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: b}},
	}}
}

// SelectCol returns the typed accessor for column select.
func (t KeywordColTable) SelectCol() KeywordColSelectCol {
	return KeywordColSelectCol{pgb.Col{Table: "keyword_cols", Name: "select"}}
}

// KeywordColSelectCol is the typed column keyword_cols.select.
type KeywordColSelectCol struct{ pgb.Col }

func (c KeywordColSelectCol) Eq(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColSelectCol) Ne(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColSelectCol) In(vs ...pgtype.Text) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c KeywordColSelectCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c KeywordColSelectCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c KeywordColSelectCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColSelectCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColSelectCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColSelectCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// Class returns the typed accessor for column class.
func (t KeywordColTable) Class() KeywordColClassCol {
	return KeywordColClassCol{pgb.Col{Table: "keyword_cols", Name: "class"}}
}

// KeywordColClassCol is the typed column keyword_cols.class.
type KeywordColClassCol struct{ pgb.Col }

func (c KeywordColClassCol) Eq(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColClassCol) Ne(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColClassCol) In(vs ...pgtype.Text) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c KeywordColClassCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c KeywordColClassCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c KeywordColClassCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColClassCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColClassCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColClassCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// Interface returns the typed accessor for column interface.
func (t KeywordColTable) Interface() KeywordColInterfaceCol {
	return KeywordColInterfaceCol{pgb.Col{Table: "keyword_cols", Name: "interface"}}
}

// KeywordColInterfaceCol is the typed column keyword_cols.interface.
type KeywordColInterfaceCol struct{ pgb.Col }

func (c KeywordColInterfaceCol) Eq(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColInterfaceCol) Ne(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColInterfaceCol) In(vs ...pgtype.Text) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c KeywordColInterfaceCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c KeywordColInterfaceCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c KeywordColInterfaceCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColInterfaceCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColInterfaceCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColInterfaceCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// Map returns the typed accessor for column map.
func (t KeywordColTable) Map() KeywordColMapCol {
	return KeywordColMapCol{pgb.Col{Table: "keyword_cols", Name: "map"}}
}

// KeywordColMapCol is the typed column keyword_cols.map.
type KeywordColMapCol struct{ pgb.Col }

func (c KeywordColMapCol) Eq(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColMapCol) Ne(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColMapCol) In(vs ...pgtype.Text) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c KeywordColMapCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c KeywordColMapCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c KeywordColMapCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColMapCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColMapCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColMapCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// Func returns the typed accessor for column func.
func (t KeywordColTable) Func() KeywordColFuncCol {
	return KeywordColFuncCol{pgb.Col{Table: "keyword_cols", Name: "func"}}
}

// KeywordColFuncCol is the typed column keyword_cols.func.
type KeywordColFuncCol struct{ pgb.Col }

func (c KeywordColFuncCol) Eq(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColFuncCol) Ne(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColFuncCol) In(vs ...pgtype.Text) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c KeywordColFuncCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c KeywordColFuncCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c KeywordColFuncCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColFuncCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColFuncCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColFuncCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// Return returns the typed accessor for column return.
func (t KeywordColTable) Return() KeywordColReturnCol {
	return KeywordColReturnCol{pgb.Col{Table: "keyword_cols", Name: "return"}}
}

// KeywordColReturnCol is the typed column keyword_cols.return.
type KeywordColReturnCol struct{ pgb.Col }

func (c KeywordColReturnCol) Eq(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColReturnCol) Ne(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColReturnCol) In(vs ...pgtype.Text) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c KeywordColReturnCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c KeywordColReturnCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c KeywordColReturnCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColReturnCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColReturnCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColReturnCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// Chan returns the typed accessor for column chan.
func (t KeywordColTable) Chan() KeywordColChanCol {
	return KeywordColChanCol{pgb.Col{Table: "keyword_cols", Name: "chan"}}
}

// KeywordColChanCol is the typed column keyword_cols.chan.
type KeywordColChanCol struct{ pgb.Col }

func (c KeywordColChanCol) Eq(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColChanCol) Ne(v pgtype.Text) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c KeywordColChanCol) In(vs ...pgtype.Text) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "text[]" + ")", Args: []any{vs}}
}

func (c KeywordColChanCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c KeywordColChanCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c KeywordColChanCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColChanCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColChanCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c KeywordColChanCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// Select starts a SELECT of every column; chain Where/OrderBy/Limit/...
// and terminate with Run (or a static function).
func (t KeywordColTable) Select() *pgb.Select {
	return pgb.NewSelect("public.keyword_cols", pgb.Col{Table: "keyword_cols", Name: "id"}, pgb.Col{Table: "keyword_cols", Name: "type"}, pgb.Col{Table: "keyword_cols", Name: "range"}, pgb.Col{Table: "keyword_cols", Name: "select"}, pgb.Col{Table: "keyword_cols", Name: "class"}, pgb.Col{Table: "keyword_cols", Name: "interface"}, pgb.Col{Table: "keyword_cols", Name: "map"}, pgb.Col{Table: "keyword_cols", Name: "func"}, pgb.Col{Table: "keyword_cols", Name: "return"}, pgb.Col{Table: "keyword_cols", Name: "chan"})
}

// Update starts an UPDATE; an empty WHERE fails with pgb.ErrNoWhere.
func (t KeywordColTable) Update() *pgb.Update { return pgb.NewUpdate("public.keyword_cols") }

// Delete starts a DELETE; an empty WHERE fails with pgb.ErrNoWhere.
func (t KeywordColTable) Delete() *pgb.Delete { return pgb.NewDelete("public.keyword_cols") }
