// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
	"net"
	"net/netip"
)

type UserStatus string

const (
	UserStatusActive        UserStatus = "active"
	UserStatusInactive      UserStatus = "inactive"
	UserStatusBanned        UserStatus = "banned"
	UserStatusPasswordReset UserStatus = "password reset"
)

type OrderChannel string

const (
	OrderChannelWeb    OrderChannel = "web"
	OrderChannelMobile OrderChannel = "mobile"
	OrderChannelPhone  OrderChannel = "phone"
	OrderChannelStore  OrderChannel = "store"
)

type User struct {
	ID                                                     int64              `json:"id"`
	Email                                                  string             `json:"email"`
	Password                                               string             `json:"password"`
	Name                                                   string             `json:"name"`
	Bio                                                    pgtype.Text        `json:"bio"`
	Age                                                    pgtype.Int2        `json:"age"`
	Balance                                                pgtype.Numeric     `json:"balance"`
	Rating                                                 pgtype.Float4      `json:"rating"`
	Score                                                  float64            `json:"score"`
	IsActive                                               bool               `json:"is_active"`
	CreatedAt                                              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                                              pgtype.Timestamptz `json:"updated_at"`
	BirthDate                                              pgtype.Date        `json:"birth_date"`
	LastSeen                                               pgtype.Time        `json:"last_seen"`
	Avatar                                                 []byte             `json:"avatar"`
	Metadata                                               []byte             `json:"metadata"`
	Settings                                               map[string]any     `json:"settings"`
	Homepage                                               netip.Prefix       `json:"homepage"`
	Lan                                                    netip.Prefix       `json:"lan"`
	Mac                                                    net.HardwareAddr   `json:"mac"`
	Mac8                                                   net.HardwareAddr   `json:"mac8"`
	Bitfield                                               any                `json:"bitfield"`
	Flags                                                  any                `json:"flags"`
	Tags                                                   []string           `json:"tags"`
	Scores                                                 []int32            `json:"scores"`
	Grid                                                   []int32            `json:"grid"`
	Homesite                                               pgtype.Point       `json:"homesite"`
	Seg                                                    pgtype.Lseg        `json:"seg"`
	BoxCol                                                 pgtype.Box         `json:"box_col"`
	PathCol                                                pgtype.Path        `json:"path_col"`
	Poly                                                   pgtype.Polygon     `json:"poly"`
	CircleCol                                              pgtype.Circle      `json:"circle_col"`
	LineCol                                                pgtype.Line        `json:"line_col"`
	Tsv                                                    any                `json:"tsv"`
	Tsq                                                    any                `json:"tsq"`
	XMLDoc                                                 pgtype.Text        `json:"xml_doc"`
	LogLsn                                                 any                `json:"log_lsn"`
	LastXid                                                pgtype.Uint64      `json:"last_xid"`
	SlotTid                                                pgtype.TID         `json:"slot_tid"`
	Cash                                                   pgtype.Numeric     `json:"cash"`
	Status                                                 UserStatus         `json:"status"`
	Addr                                                   any                `json:"addr"`
	EmailDomain                                            any                `json:"email_domain"`
	Positive                                               any                `json:"positive"`
	UUIDCol                                                uuid.UUID          `json:"uuid_col"`
	LoginCi                                                string             `json:"login_ci"`
	CollateCol                                             pgtype.Text        `json:"collate_col"`
	SearchSlug                                             pgtype.Text        `json:"search_slug"`
	NameUpper                                              pgtype.Text        `json:"name_upper"`
	DeletedAt                                              pgtype.Timestamptz `json:"deleted_at"`
	VeryLongColumnIdentifierExactlySixtyThreeCharactersInL pgtype.Text        `json:"very_long_column_identifier_exactly_sixty_three_characters_in_l"`
}

type Product struct {
	ID          int64              `json:"id"`
	Sku         string             `json:"sku"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Category    string             `json:"category"`
	Rating      pgtype.Numeric     `json:"rating"`
	Price       pgtype.Numeric     `json:"price"`
	InStock     bool               `json:"in_stock"`
	Metadata    []byte             `json:"metadata"`
	Embedding   pgvector.Vector    `json:"embedding"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID         int64                                               `json:"id"`
	ShopID     int32                                               `json:"shop_id"`
	UserID     int64                                               `json:"user_id"`
	Channel    OrderChannel                                        `json:"channel"`
	Total      pgtype.Numeric                                      `json:"total"`
	PlacedAt   pgtype.Timestamptz                                  `json:"placed_at"`
	ShipWindow pgtype.Range[pgtype.Date]                           `json:"ship_window"`
	Schedule   pgtype.Multirange[pgtype.Range[pgtype.Timestamptz]] `json:"schedule"`
	Notes      pgtype.Text                                         `json:"notes"`
}

type OrderItem struct {
	OrderShopID int32          `json:"order_shop_id"`
	OrderID     int64          `json:"order_id"`
	ProductID   int64          `json:"product_id"`
	Quantity    int32          `json:"quantity"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	GiftWrap    bool           `json:"gift_wrap"`
}

type Shift struct {
	ID         int64                            `json:"id"`
	EmployeeID int32                            `json:"employee_id"`
	During     pgtype.Range[pgtype.Timestamptz] `json:"during"`
}

type Event struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Kind       string             `json:"kind"`
	Payload    []byte             `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type EventsV2026H1 struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Kind       string             `json:"kind"`
	Payload    []byte             `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type EventsV2026H2 struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Kind       string             `json:"kind"`
	Payload    []byte             `json:"payload"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type ActiveUser struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OrderStat struct {
	UserID        int64 `json:"user_id"`
	OrderCount    int64 `json:"order_count"`
	LifetimeValue int64 `json:"lifetime_value"`
}

type Category struct {
	ID       int64       `json:"id"`
	Name     string      `json:"name"`
	ParentID pgtype.Int8 `json:"parent_id"`
}

type CacheBlob struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Ticket struct {
	ID        int64              `json:"id"`
	Number    int64              `json:"number"`
	Subject   string             `json:"subject"`
	Priority  string             `json:"priority"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Inventory struct {
	ItemID    int64              `json:"item_id"`
	Qty       int32              `json:"qty"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type KeywordCol struct {
	ID        int64       `json:"id"`
	Type      pgtype.Text `json:"type"`
	Range     pgtype.Int4 `json:"range"`
	Select    pgtype.Text `json:"select"`
	Class     pgtype.Text `json:"class"`
	Interface pgtype.Text `json:"interface"`
	Map       pgtype.Text `json:"map"`
	Func      pgtype.Text `json:"func"`
	Return    pgtype.Text `json:"return"`
	Chan      pgtype.Text `json:"chan"`
}

type CaseCol struct {
	ID        int64       `json:"id"`
	Email     pgtype.Text `json:"Email"`
	Mixedcase pgtype.Int4 `json:"mixedcase"`
	Caf       pgtype.Text `json:"café"`
	PlainCol  pgtype.Text `json:"plain_col"`
}

type SkippablePartner struct {
	ID    int64  `json:"id"`
	Label string `json:"label"`
}

type Doc struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
	Body  string    `json:"body"`
}

type AppUser struct {
	ID       int64       `json:"id"`
	Login    string      `json:"login"`
	PersonID pgtype.Int8 `json:"person_id"`
	Display  pgtype.Text `json:"display"`
}

type AppAuditLog struct {
	ID       int64              `json:"id"`
	Entity   string             `json:"entity"`
	EntityID int64              `json:"entity_id"`
	Payload  []byte             `json:"payload"`
	At       pgtype.Timestamptz `json:"at"`
}
