// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"github.com/jackc/pgx/v5"
	pgb "github.com/khoale-2804/pgb/core"
)

// OrderStatFilter narrows ListOrderStats and CountOrderStats:
// nil / zero fields are ignored; Extra composes raw predicates.
type OrderStatFilter struct {
	UserID           *int64
	UserIDIn         []int64
	UserIDGt         *int64
	UserIDLt         *int64
	UserIDGte        *int64
	UserIDLte        *int64
	OrderCount       *int64
	OrderCountIn     []int64
	OrderCountGt     *int64
	OrderCountLt     *int64
	OrderCountGte    *int64
	OrderCountLte    *int64
	LifetimeValue    *int64
	LifetimeValueIn  []int64
	LifetimeValueGt  *int64
	LifetimeValueLt  *int64
	LifetimeValueGte *int64
	LifetimeValueLte *int64
	Extra            []pgb.Expr
}

// orderStatsFilterWhere compiles f into the ANDed predicate list; an empty
// filter yields an empty list (no WHERE).
func orderStatsFilterWhere(f OrderStatFilter) []pgb.Expr {
	var w []pgb.Expr
	if f.UserID != nil {
		w = append(w, OrderStats.UserID().Eq(*f.UserID))
	}
	if len(f.UserIDIn) > 0 {
		w = append(w, OrderStats.UserID().In(f.UserIDIn...))
	}
	if f.UserIDGt != nil {
		w = append(w, OrderStats.UserID().Gt(*f.UserIDGt))
	}
	if f.UserIDLt != nil {
		w = append(w, OrderStats.UserID().Lt(*f.UserIDLt))
	}
	if f.UserIDGte != nil {
		w = append(w, OrderStats.UserID().Gte(*f.UserIDGte))
	}
	if f.UserIDLte != nil {
		w = append(w, OrderStats.UserID().Lte(*f.UserIDLte))
	}
	if f.OrderCount != nil {
		w = append(w, OrderStats.OrderCount().Eq(*f.OrderCount))
	}
	if len(f.OrderCountIn) > 0 {
		w = append(w, OrderStats.OrderCount().In(f.OrderCountIn...))
	}
	if f.OrderCountGt != nil {
		w = append(w, OrderStats.OrderCount().Gt(*f.OrderCountGt))
	}
	if f.OrderCountLt != nil {
		w = append(w, OrderStats.OrderCount().Lt(*f.OrderCountLt))
	}
	if f.OrderCountGte != nil {
		w = append(w, OrderStats.OrderCount().Gte(*f.OrderCountGte))
	}
	if f.OrderCountLte != nil {
		w = append(w, OrderStats.OrderCount().Lte(*f.OrderCountLte))
	}
	if f.LifetimeValue != nil {
		w = append(w, OrderStats.LifetimeValue().Eq(*f.LifetimeValue))
	}
	if len(f.LifetimeValueIn) > 0 {
		w = append(w, OrderStats.LifetimeValue().In(f.LifetimeValueIn...))
	}
	if f.LifetimeValueGt != nil {
		w = append(w, OrderStats.LifetimeValue().Gt(*f.LifetimeValueGt))
	}
	if f.LifetimeValueLt != nil {
		w = append(w, OrderStats.LifetimeValue().Lt(*f.LifetimeValueLt))
	}
	if f.LifetimeValueGte != nil {
		w = append(w, OrderStats.LifetimeValue().Gte(*f.LifetimeValueGte))
	}
	if f.LifetimeValueLte != nil {
		w = append(w, OrderStats.LifetimeValue().Lte(*f.LifetimeValueLte))
	}
	w = append(w, f.Extra...)
	return w
}

// InsertOrderStatParams carries the INSERT column values: generated
// and serial columns are out, default-bearing columns join only with
// the include_defaults option.
type InsertOrderStatParams struct {
}

// scanOrderStat scans one row positionally over every column in
// catalog order — the single scan path for all generated reads.
func scanOrderStat(row pgx.CollectableRow) (OrderStat, error) {
	var m OrderStat
	if err := row.Scan(&m.UserID, &m.OrderCount, &m.LifetimeValue); err != nil {
		return OrderStat{}, err
	}
	return m, nil
}

// ListOrderStats returns the rows matching f; limit <= 0 means no LIMIT.
func ListOrderStats(ctx context.Context, exec pgb.DBTX, f OrderStatFilter, opts ...pgb.ListOpt) ([]OrderStat, error) {
	sel := OrderStats.Select().Where(orderStatsFilterWhere(f)...).ApplyList(opts...)
	rows, err := sel.Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanOrderStat)
}

// CountOrderStats counts the rows matching f.
func CountOrderStats(ctx context.Context, exec pgb.DBTX, f OrderStatFilter) (int64, error) {
	sql, args := pgb.NewSelect("public.order_stats", pgb.Raw{SQL: "count(*)"}).Where(orderStatsFilterWhere(f)...).SQL()
	var n int64
	if err := exec.QueryRow(ctx, sql, args...).Scan(&n); err != nil {
		return 0, err
	}
	return n, nil
}
