// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	pgb "github.com/khoale-2804/pgb/core"
)

// OrderFilter narrows ListOrders and CountOrders:
// nil / zero fields are ignored; Extra composes raw predicates.
type OrderFilter struct {
	ID          *int64
	IDIn        []int64
	IDGt        *int64
	IDLt        *int64
	IDGte       *int64
	IDLte       *int64
	ShopID      *int32
	ShopIDIn    []int32
	ShopIDGt    *int32
	ShopIDLt    *int32
	ShopIDGte   *int32
	ShopIDLte   *int32
	UserID      *int64
	UserIDIn    []int64
	UserIDGt    *int64
	UserIDLt    *int64
	UserIDGte   *int64
	UserIDLte   *int64
	Channel     *OrderChannel
	Total       *pgtype.Numeric
	TotalIn     []pgtype.Numeric
	TotalGt     *pgtype.Numeric
	TotalLt     *pgtype.Numeric
	TotalGte    *pgtype.Numeric
	TotalLte    *pgtype.Numeric
	PlacedAt    *pgtype.Timestamptz
	PlacedAtIn  []pgtype.Timestamptz
	PlacedAtGt  *pgtype.Timestamptz
	PlacedAtLt  *pgtype.Timestamptz
	PlacedAtGte *pgtype.Timestamptz
	PlacedAtLte *pgtype.Timestamptz
	ShipWindow  *pgtype.Range[pgtype.Date]
	Schedule    *pgtype.Multirange[pgtype.Range[pgtype.Timestamptz]]
	Notes       *pgtype.Text
	NotesIn     []pgtype.Text
	NotesLike   *string
	NotesILike  *string
	Extra       []pgb.Expr
}

// ordersFilterWhere compiles f into the ANDed predicate list; an empty
// filter yields an empty list (no WHERE).
func ordersFilterWhere(f OrderFilter) []pgb.Expr {
	var w []pgb.Expr
	if f.ID != nil {
		w = append(w, Orders.ID().Eq(*f.ID))
	}
	if len(f.IDIn) > 0 {
		w = append(w, Orders.ID().In(f.IDIn...))
	}
	if f.IDGt != nil {
		w = append(w, Orders.ID().Gt(*f.IDGt))
	}
	if f.IDLt != nil {
		w = append(w, Orders.ID().Lt(*f.IDLt))
	}
	if f.IDGte != nil {
		w = append(w, Orders.ID().Gte(*f.IDGte))
	}
	if f.IDLte != nil {
		w = append(w, Orders.ID().Lte(*f.IDLte))
	}
	if f.ShopID != nil {
		w = append(w, Orders.ShopID().Eq(*f.ShopID))
	}
	if len(f.ShopIDIn) > 0 {
		w = append(w, Orders.ShopID().In(f.ShopIDIn...))
	}
	if f.ShopIDGt != nil {
		w = append(w, Orders.ShopID().Gt(*f.ShopIDGt))
	}
	if f.ShopIDLt != nil {
		w = append(w, Orders.ShopID().Lt(*f.ShopIDLt))
	}
	if f.ShopIDGte != nil {
		w = append(w, Orders.ShopID().Gte(*f.ShopIDGte))
	}
	if f.ShopIDLte != nil {
		w = append(w, Orders.ShopID().Lte(*f.ShopIDLte))
	}
	if f.UserID != nil {
		w = append(w, Orders.UserID().Eq(*f.UserID))
	}
	if len(f.UserIDIn) > 0 {
		w = append(w, Orders.UserID().In(f.UserIDIn...))
	}
	if f.UserIDGt != nil {
		w = append(w, Orders.UserID().Gt(*f.UserIDGt))
	}
	if f.UserIDLt != nil {
		w = append(w, Orders.UserID().Lt(*f.UserIDLt))
	}
	if f.UserIDGte != nil {
		w = append(w, Orders.UserID().Gte(*f.UserIDGte))
	}
	if f.UserIDLte != nil {
		w = append(w, Orders.UserID().Lte(*f.UserIDLte))
	}
	if f.Channel != nil {
		w = append(w, Orders.Channel().Eq(*f.Channel))
	}
	if f.Total != nil {
		w = append(w, Orders.Total().Eq(*f.Total))
	}
	if len(f.TotalIn) > 0 {
		w = append(w, Orders.Total().In(f.TotalIn...))
	}
	if f.TotalGt != nil {
		w = append(w, Orders.Total().Gt(*f.TotalGt))
	}
	if f.TotalLt != nil {
		w = append(w, Orders.Total().Lt(*f.TotalLt))
	}
	if f.TotalGte != nil {
		w = append(w, Orders.Total().Gte(*f.TotalGte))
	}
	if f.TotalLte != nil {
		w = append(w, Orders.Total().Lte(*f.TotalLte))
	}
	if f.PlacedAt != nil {
		w = append(w, Orders.PlacedAt().Eq(*f.PlacedAt))
	}
	if len(f.PlacedAtIn) > 0 {
		w = append(w, Orders.PlacedAt().In(f.PlacedAtIn...))
	}
	if f.PlacedAtGt != nil {
		w = append(w, Orders.PlacedAt().Gt(*f.PlacedAtGt))
	}
	if f.PlacedAtLt != nil {
		w = append(w, Orders.PlacedAt().Lt(*f.PlacedAtLt))
	}
	if f.PlacedAtGte != nil {
		w = append(w, Orders.PlacedAt().Gte(*f.PlacedAtGte))
	}
	if f.PlacedAtLte != nil {
		w = append(w, Orders.PlacedAt().Lte(*f.PlacedAtLte))
	}
	if f.ShipWindow != nil {
		w = append(w, Orders.ShipWindow().Eq(*f.ShipWindow))
	}
	if f.Schedule != nil {
		w = append(w, Orders.Schedule().Eq(*f.Schedule))
	}
	if f.Notes != nil {
		w = append(w, Orders.Notes().Eq(*f.Notes))
	}
	if len(f.NotesIn) > 0 {
		w = append(w, Orders.Notes().In(f.NotesIn...))
	}
	if f.NotesLike != nil {
		w = append(w, Orders.Notes().Like(*f.NotesLike))
	}
	if f.NotesILike != nil {
		w = append(w, Orders.Notes().ILike(*f.NotesILike))
	}
	w = append(w, f.Extra...)
	return w
}

// OrderSet is the three-state UPDATE payload: a zero Set field
// skips its column, SetOf writes a value, SetNull writes NULL.
type OrderSet struct {
	ID         Set[int64]
	ShopID     Set[int32]
	UserID     Set[int64]
	Channel    Set[OrderChannel]
	Total      Set[pgtype.Numeric]
	PlacedAt   Set[pgtype.Timestamptz]
	ShipWindow Set[pgtype.Range[pgtype.Date]]
	Schedule   Set[pgtype.Multirange[pgtype.Range[pgtype.Timestamptz]]]
	Notes      Set[pgtype.Text]
}

// InsertOrderParams carries the INSERT column values: generated
// and serial columns are out, default-bearing columns join only with
// the include_defaults option.
type InsertOrderParams struct {
	ShopID     int32
	UserID     int64
	Channel    OrderChannel
	Total      pgtype.Numeric
	ShipWindow pgtype.Range[pgtype.Date]
	Schedule   pgtype.Multirange[pgtype.Range[pgtype.Timestamptz]]
	Notes      pgtype.Text
}

// scanOrder scans one row positionally over every column in
// catalog order — the single scan path for all generated reads.
func scanOrder(row pgx.CollectableRow) (Order, error) {
	var m Order
	if err := row.Scan(&m.ID, &m.ShopID, &m.UserID, &m.Channel, &m.Total, &m.PlacedAt, &m.ShipWindow, &m.Schedule, &m.Notes); err != nil {
		return Order{}, err
	}
	return m, nil
}

// ListOrders returns the rows matching f; limit <= 0 means no LIMIT.
func ListOrders(ctx context.Context, exec pgb.DBTX, f OrderFilter, opts ...pgb.ListOpt) ([]Order, error) {
	sel := Orders.Select().Where(ordersFilterWhere(f)...).ApplyList(opts...)
	rows, err := sel.Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanOrder)
}

// CountOrders counts the rows matching f.
func CountOrders(ctx context.Context, exec pgb.DBTX, f OrderFilter) (int64, error) {
	sql, args := pgb.NewSelect("public.orders", pgb.Raw{SQL: "count(*)"}).Where(ordersFilterWhere(f)...).SQL()
	var n int64
	if err := exec.QueryRow(ctx, sql, args...).Scan(&n); err != nil {
		return 0, err
	}
	return n, nil
}

// InsertOrder inserts one row and returns it (RETURNING every
// column, defaults included).
func InsertOrder(ctx context.Context, exec pgb.DBTX, p InsertOrderParams) (Order, error) {
	rows, err := pgb.NewInsert("public.orders",
		[]string{"shop_id", "user_id", "channel", "total", "ship_window", "schedule", "notes"},
		[]pgb.Expr{pgb.Lit{V: p.ShopID}, pgb.Lit{V: p.UserID}, pgb.Lit{V: p.Channel, Cast: "order_channel"}, pgb.Lit{V: p.Total}, pgb.Lit{V: p.ShipWindow}, pgb.Lit{V: p.Schedule}, pgb.Lit{V: p.Notes}},
	).Returning(pgb.Col{Table: "orders", Name: "id"}, pgb.Col{Table: "orders", Name: "shop_id"}, pgb.Col{Table: "orders", Name: "user_id"}, pgb.Col{Table: "orders", Name: "channel"}, pgb.Col{Table: "orders", Name: "total"}, pgb.Col{Table: "orders", Name: "placed_at"}, pgb.Col{Table: "orders", Name: "ship_window"}, pgb.Col{Table: "orders", Name: "schedule"}, pgb.Col{Table: "orders", Name: "notes"}).Run(ctx, exec)
	if err != nil {
		return Order{}, err
	}
	us, err := pgx.CollectRows(rows, scanOrder)
	if err != nil {
		return Order{}, err
	}
	if len(us) == 0 {
		return Order{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// UpdateOrders applies s to every row matching where and
// returns the affected count; an empty where is refused with
// pgb.ErrNoWhere before any SQL is sent.
func UpdateOrders(ctx context.Context, exec pgb.DBTX, where []pgb.Expr, s OrderSet) (int64, error) {
	u := Orders.Update()
	n := 0
	if s.ID.Valid {
		n++
		if s.ID.Null {
			u.Set("id", pgb.Lit{V: nil})
		} else {
			u.Set("id", pgb.Lit{V: s.ID.V})
		}
	}
	if s.ShopID.Valid {
		n++
		if s.ShopID.Null {
			u.Set("shop_id", pgb.Lit{V: nil})
		} else {
			u.Set("shop_id", pgb.Lit{V: s.ShopID.V})
		}
	}
	if s.UserID.Valid {
		n++
		if s.UserID.Null {
			u.Set("user_id", pgb.Lit{V: nil})
		} else {
			u.Set("user_id", pgb.Lit{V: s.UserID.V})
		}
	}
	if s.Channel.Valid {
		n++
		if s.Channel.Null {
			u.Set("channel", pgb.Lit{V: nil})
		} else {
			u.Set("channel", pgb.Lit{V: s.Channel.V, Cast: "order_channel"})
		}
	}
	if s.Total.Valid {
		n++
		if s.Total.Null {
			u.Set("total", pgb.Lit{V: nil})
		} else {
			u.Set("total", pgb.Lit{V: s.Total.V})
		}
	}
	if s.PlacedAt.Valid {
		n++
		if s.PlacedAt.Null {
			u.Set("placed_at", pgb.Lit{V: nil})
		} else {
			u.Set("placed_at", pgb.Lit{V: s.PlacedAt.V})
		}
	}
	if s.ShipWindow.Valid {
		n++
		if s.ShipWindow.Null {
			u.Set("ship_window", pgb.Lit{V: nil})
		} else {
			u.Set("ship_window", pgb.Lit{V: s.ShipWindow.V})
		}
	}
	if s.Schedule.Valid {
		n++
		if s.Schedule.Null {
			u.Set("schedule", pgb.Lit{V: nil})
		} else {
			u.Set("schedule", pgb.Lit{V: s.Schedule.V})
		}
	}
	if s.Notes.Valid {
		n++
		if s.Notes.Null {
			u.Set("notes", pgb.Lit{V: nil})
		} else {
			u.Set("notes", pgb.Lit{V: s.Notes.V})
		}
	}
	if n == 0 {
		return 0, nil
	}
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	u.Where(where...)
	tag, err := u.Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// DeleteOrders removes every row matching where and returns the
// affected count; an empty where is refused with pgb.ErrNoWhere.
func DeleteOrders(ctx context.Context, exec pgb.DBTX, where []pgb.Expr) (int64, error) {
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	tag, err := Orders.Delete().Where(where...).Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
