// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	core "github.com/khoale-2804/pgb/core"
)

// OrderStats is the table descriptor for public.order_stats; immutable, safe for
// concurrent use.
var OrderStats = OrderStatTable{core.NewTableMeta("public", "order_stats")}

// OrderStatTable provides typed column accessors and statement entry points.
type OrderStatTable struct{ core.TableMeta }

// UserID returns the typed accessor for column user_id.
func (t OrderStatTable) UserID() OrderStatUserIDCol {
	return OrderStatUserIDCol{core.Col{Table: "order_stats", Name: "user_id"}}
}

// OrderStatUserIDCol is the typed column order_stats.user_id.
type OrderStatUserIDCol struct{ core.Col }

func (c OrderStatUserIDCol) Eq(v int64) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatUserIDCol) Ne(v int64) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatUserIDCol) In(vs ...int64) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "int8[]"}}
}

func (c OrderStatUserIDCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c OrderStatUserIDCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c OrderStatUserIDCol) Gt(v int64) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatUserIDCol) Lt(v int64) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatUserIDCol) Gte(v int64) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatUserIDCol) Lte(v int64) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatUserIDCol) Between(a, b int64) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// OrderCount returns the typed accessor for column order_count.
func (t OrderStatTable) OrderCount() OrderStatOrderCountCol {
	return OrderStatOrderCountCol{core.Col{Table: "order_stats", Name: "order_count"}}
}

// OrderStatOrderCountCol is the typed column order_stats.order_count.
type OrderStatOrderCountCol struct{ core.Col }

func (c OrderStatOrderCountCol) Eq(v int64) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatOrderCountCol) Ne(v int64) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatOrderCountCol) In(vs ...int64) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "bigint[]"}}
}

func (c OrderStatOrderCountCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c OrderStatOrderCountCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c OrderStatOrderCountCol) Gt(v int64) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatOrderCountCol) Lt(v int64) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatOrderCountCol) Gte(v int64) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatOrderCountCol) Lte(v int64) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatOrderCountCol) Between(a, b int64) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// LifetimeValue returns the typed accessor for column lifetime_value.
func (t OrderStatTable) LifetimeValue() OrderStatLifetimeValueCol {
	return OrderStatLifetimeValueCol{core.Col{Table: "order_stats", Name: "lifetime_value"}}
}

// OrderStatLifetimeValueCol is the typed column order_stats.lifetime_value.
type OrderStatLifetimeValueCol struct{ core.Col }

func (c OrderStatLifetimeValueCol) Eq(v int64) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatLifetimeValueCol) Ne(v int64) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatLifetimeValueCol) In(vs ...int64) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "bigint[]"}}
}

func (c OrderStatLifetimeValueCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c OrderStatLifetimeValueCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c OrderStatLifetimeValueCol) Gt(v int64) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatLifetimeValueCol) Lt(v int64) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatLifetimeValueCol) Gte(v int64) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatLifetimeValueCol) Lte(v int64) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c OrderStatLifetimeValueCol) Between(a, b int64) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// Select starts a SELECT of every column; chain Where/OrderBy/Limit/...
// and terminate with Run (or a static function).
func (t OrderStatTable) Select() *core.Select {
	return core.NewSelect("public.order_stats", core.Col{Table: "order_stats", Name: "user_id"}, core.Col{Table: "order_stats", Name: "order_count"}, core.Col{Table: "order_stats", Name: "lifetime_value"})
}
