// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	pgb "github.com/khoale-2804/pgb/core"
)

// OrderItemFilter narrows ListOrderItems and CountOrderItems:
// nil / zero fields are ignored; Extra composes raw predicates.
type OrderItemFilter struct {
	OrderShopID    *int32
	OrderShopIDIn  []int32
	OrderShopIDGt  *int32
	OrderShopIDLt  *int32
	OrderShopIDGte *int32
	OrderShopIDLte *int32
	OrderID        *int64
	OrderIDIn      []int64
	OrderIDGt      *int64
	OrderIDLt      *int64
	OrderIDGte     *int64
	OrderIDLte     *int64
	ProductID      *int64
	ProductIDIn    []int64
	ProductIDGt    *int64
	ProductIDLt    *int64
	ProductIDGte   *int64
	ProductIDLte   *int64
	Quantity       *int32
	QuantityIn     []int32
	QuantityGt     *int32
	QuantityLt     *int32
	QuantityGte    *int32
	QuantityLte    *int32
	UnitPrice      *pgtype.Numeric
	UnitPriceIn    []pgtype.Numeric
	UnitPriceGt    *pgtype.Numeric
	UnitPriceLt    *pgtype.Numeric
	UnitPriceGte   *pgtype.Numeric
	UnitPriceLte   *pgtype.Numeric
	GiftWrap       *bool
	GiftWrapIn     []bool
	Extra          []pgb.Expr
}

// orderItemsFilterWhere compiles f into the ANDed predicate list; an empty
// filter yields an empty list (no WHERE).
func orderItemsFilterWhere(f OrderItemFilter) []pgb.Expr {
	var w []pgb.Expr
	if f.OrderShopID != nil {
		w = append(w, OrderItems.OrderShopID().Eq(*f.OrderShopID))
	}
	if len(f.OrderShopIDIn) > 0 {
		w = append(w, OrderItems.OrderShopID().In(f.OrderShopIDIn...))
	}
	if f.OrderShopIDGt != nil {
		w = append(w, OrderItems.OrderShopID().Gt(*f.OrderShopIDGt))
	}
	if f.OrderShopIDLt != nil {
		w = append(w, OrderItems.OrderShopID().Lt(*f.OrderShopIDLt))
	}
	if f.OrderShopIDGte != nil {
		w = append(w, OrderItems.OrderShopID().Gte(*f.OrderShopIDGte))
	}
	if f.OrderShopIDLte != nil {
		w = append(w, OrderItems.OrderShopID().Lte(*f.OrderShopIDLte))
	}
	if f.OrderID != nil {
		w = append(w, OrderItems.OrderID().Eq(*f.OrderID))
	}
	if len(f.OrderIDIn) > 0 {
		w = append(w, OrderItems.OrderID().In(f.OrderIDIn...))
	}
	if f.OrderIDGt != nil {
		w = append(w, OrderItems.OrderID().Gt(*f.OrderIDGt))
	}
	if f.OrderIDLt != nil {
		w = append(w, OrderItems.OrderID().Lt(*f.OrderIDLt))
	}
	if f.OrderIDGte != nil {
		w = append(w, OrderItems.OrderID().Gte(*f.OrderIDGte))
	}
	if f.OrderIDLte != nil {
		w = append(w, OrderItems.OrderID().Lte(*f.OrderIDLte))
	}
	if f.ProductID != nil {
		w = append(w, OrderItems.ProductID().Eq(*f.ProductID))
	}
	if len(f.ProductIDIn) > 0 {
		w = append(w, OrderItems.ProductID().In(f.ProductIDIn...))
	}
	if f.ProductIDGt != nil {
		w = append(w, OrderItems.ProductID().Gt(*f.ProductIDGt))
	}
	if f.ProductIDLt != nil {
		w = append(w, OrderItems.ProductID().Lt(*f.ProductIDLt))
	}
	if f.ProductIDGte != nil {
		w = append(w, OrderItems.ProductID().Gte(*f.ProductIDGte))
	}
	if f.ProductIDLte != nil {
		w = append(w, OrderItems.ProductID().Lte(*f.ProductIDLte))
	}
	if f.Quantity != nil {
		w = append(w, OrderItems.Quantity().Eq(*f.Quantity))
	}
	if len(f.QuantityIn) > 0 {
		w = append(w, OrderItems.Quantity().In(f.QuantityIn...))
	}
	if f.QuantityGt != nil {
		w = append(w, OrderItems.Quantity().Gt(*f.QuantityGt))
	}
	if f.QuantityLt != nil {
		w = append(w, OrderItems.Quantity().Lt(*f.QuantityLt))
	}
	if f.QuantityGte != nil {
		w = append(w, OrderItems.Quantity().Gte(*f.QuantityGte))
	}
	if f.QuantityLte != nil {
		w = append(w, OrderItems.Quantity().Lte(*f.QuantityLte))
	}
	if f.UnitPrice != nil {
		w = append(w, OrderItems.UnitPrice().Eq(*f.UnitPrice))
	}
	if len(f.UnitPriceIn) > 0 {
		w = append(w, OrderItems.UnitPrice().In(f.UnitPriceIn...))
	}
	if f.UnitPriceGt != nil {
		w = append(w, OrderItems.UnitPrice().Gt(*f.UnitPriceGt))
	}
	if f.UnitPriceLt != nil {
		w = append(w, OrderItems.UnitPrice().Lt(*f.UnitPriceLt))
	}
	if f.UnitPriceGte != nil {
		w = append(w, OrderItems.UnitPrice().Gte(*f.UnitPriceGte))
	}
	if f.UnitPriceLte != nil {
		w = append(w, OrderItems.UnitPrice().Lte(*f.UnitPriceLte))
	}
	if f.GiftWrap != nil {
		w = append(w, OrderItems.GiftWrap().Eq(*f.GiftWrap))
	}
	if len(f.GiftWrapIn) > 0 {
		w = append(w, OrderItems.GiftWrap().In(f.GiftWrapIn...))
	}
	w = append(w, f.Extra...)
	return w
}

// OrderItemSet is the three-state UPDATE payload: a zero Set field
// skips its column, SetOf writes a value, SetNull writes NULL.
type OrderItemSet struct {
	OrderShopID Set[int32]
	OrderID     Set[int64]
	ProductID   Set[int64]
	Quantity    Set[int32]
	UnitPrice   Set[pgtype.Numeric]
	GiftWrap    Set[bool]
}

// InsertOrderItemParams carries the INSERT column values: generated
// and serial columns are out, default-bearing columns join only with
// the include_defaults option.
type InsertOrderItemParams struct {
	OrderShopID int32
	OrderID     int64
	ProductID   int64
	Quantity    int32
	UnitPrice   pgtype.Numeric
}

// scanOrderItem scans one row positionally over every column in
// catalog order — the single scan path for all generated reads.
func scanOrderItem(row pgx.CollectableRow) (OrderItem, error) {
	var m OrderItem
	if err := row.Scan(&m.OrderShopID, &m.OrderID, &m.ProductID, &m.Quantity, &m.UnitPrice, &m.GiftWrap); err != nil {
		return OrderItem{}, err
	}
	return m, nil
}

// ListOrderItems returns the rows matching f; limit <= 0 means no LIMIT.
func ListOrderItems(ctx context.Context, exec pgb.DBTX, f OrderItemFilter, opts ...pgb.ListOpt) ([]OrderItem, error) {
	sel := OrderItems.Select().Where(orderItemsFilterWhere(f)...).ApplyList(opts...)
	rows, err := sel.Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanOrderItem)
}

// CountOrderItems counts the rows matching f.
func CountOrderItems(ctx context.Context, exec pgb.DBTX, f OrderItemFilter) (int64, error) {
	sql, args := pgb.NewSelect("public.order_items", pgb.Raw{SQL: "count(*)"}).Where(orderItemsFilterWhere(f)...).SQL()
	var n int64
	if err := exec.QueryRow(ctx, sql, args...).Scan(&n); err != nil {
		return 0, err
	}
	return n, nil
}

// InsertOrderItem inserts one row and returns it (RETURNING every
// column, defaults included).
func InsertOrderItem(ctx context.Context, exec pgb.DBTX, p InsertOrderItemParams) (OrderItem, error) {
	rows, err := pgb.NewInsert("public.order_items",
		[]string{"order_shop_id", "order_id", "product_id", "quantity", "unit_price"},
		[]pgb.Expr{pgb.Lit{V: p.OrderShopID}, pgb.Lit{V: p.OrderID}, pgb.Lit{V: p.ProductID}, pgb.Lit{V: p.Quantity}, pgb.Lit{V: p.UnitPrice}},
	).Returning(pgb.Col{Table: "order_items", Name: "order_shop_id"}, pgb.Col{Table: "order_items", Name: "order_id"}, pgb.Col{Table: "order_items", Name: "product_id"}, pgb.Col{Table: "order_items", Name: "quantity"}, pgb.Col{Table: "order_items", Name: "unit_price"}, pgb.Col{Table: "order_items", Name: "gift_wrap"}).Run(ctx, exec)
	if err != nil {
		return OrderItem{}, err
	}
	us, err := pgx.CollectRows(rows, scanOrderItem)
	if err != nil {
		return OrderItem{}, err
	}
	if len(us) == 0 {
		return OrderItem{}, pgb.ErrNotFound
	}
	return us[0], nil
}

const insertOrderItemsSQL = "INSERT INTO public.order_items (order_shop_id, order_id, product_id, quantity, unit_price) SELECT * FROM unnest($1::int4[], $2::int8[], $3::int8[], $4::int4[], $5::numeric[]) RETURNING order_shop_id, order_id, product_id, quantity, unit_price, gift_wrap"

// InsertOrderItems inserts a whole batch in one round trip via
// unnest and returns every inserted row.
func InsertOrderItems(ctx context.Context, exec pgb.DBTX, ps []InsertOrderItemParams) ([]OrderItem, error) {
	if len(ps) == 0 {
		return nil, nil
	}
	colOrderShopID := make([]int32, len(ps))
	colOrderID := make([]int64, len(ps))
	colProductID := make([]int64, len(ps))
	colQuantity := make([]int32, len(ps))
	colUnitPrice := make([]pgtype.Numeric, len(ps))
	for i, p := range ps {
		colOrderShopID[i] = p.OrderShopID
		colOrderID[i] = p.OrderID
		colProductID[i] = p.ProductID
		colQuantity[i] = p.Quantity
		colUnitPrice[i] = p.UnitPrice
	}
	args := make([]any, 0, 5*len(ps))
	args = append(args, colOrderShopID, colOrderID, colProductID, colQuantity, colUnitPrice)
	rows, err := exec.Query(ctx, insertOrderItemsSQL, args...)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanOrderItem)
}

// UpdateOrderItems applies s to every row matching where and
// returns the affected count; an empty where is refused with
// pgb.ErrNoWhere before any SQL is sent.
func UpdateOrderItems(ctx context.Context, exec pgb.DBTX, where []pgb.Expr, s OrderItemSet) (int64, error) {
	u := OrderItems.Update()
	n := 0
	if s.OrderShopID.Valid {
		n++
		if s.OrderShopID.Null {
			u.Set("order_shop_id", pgb.Lit{V: nil})
		} else {
			u.Set("order_shop_id", pgb.Lit{V: s.OrderShopID.V})
		}
	}
	if s.OrderID.Valid {
		n++
		if s.OrderID.Null {
			u.Set("order_id", pgb.Lit{V: nil})
		} else {
			u.Set("order_id", pgb.Lit{V: s.OrderID.V})
		}
	}
	if s.ProductID.Valid {
		n++
		if s.ProductID.Null {
			u.Set("product_id", pgb.Lit{V: nil})
		} else {
			u.Set("product_id", pgb.Lit{V: s.ProductID.V})
		}
	}
	if s.Quantity.Valid {
		n++
		if s.Quantity.Null {
			u.Set("quantity", pgb.Lit{V: nil})
		} else {
			u.Set("quantity", pgb.Lit{V: s.Quantity.V})
		}
	}
	if s.UnitPrice.Valid {
		n++
		if s.UnitPrice.Null {
			u.Set("unit_price", pgb.Lit{V: nil})
		} else {
			u.Set("unit_price", pgb.Lit{V: s.UnitPrice.V})
		}
	}
	if s.GiftWrap.Valid {
		n++
		if s.GiftWrap.Null {
			u.Set("gift_wrap", pgb.Lit{V: nil})
		} else {
			u.Set("gift_wrap", pgb.Lit{V: s.GiftWrap.V})
		}
	}
	if n == 0 {
		return 0, nil
	}
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	u.Where(where...)
	tag, err := u.Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// DeleteOrderItems removes every row matching where and returns the
// affected count; an empty where is refused with pgb.ErrNoWhere.
func DeleteOrderItems(ctx context.Context, exec pgb.DBTX, where []pgb.Expr) (int64, error) {
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	tag, err := OrderItems.Delete().Where(where...).Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
