// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	core "github.com/khoale-2804/pgb/core"
	"github.com/pgvector/pgvector-go"
)

// Products is the table descriptor for public.products; immutable, safe for
// concurrent use.
var Products = ProductTable{core.NewTableMeta("public", "products")}

// ProductTable provides typed column accessors and statement entry points.
type ProductTable struct{ core.TableMeta }

// ID returns the typed accessor for column id.
func (t ProductTable) ID() ProductIDCol {
	return ProductIDCol{core.Col{Table: "products", Name: "id"}}
}

// ProductIDCol is the typed column products.id.
type ProductIDCol struct{ core.Col }

func (c ProductIDCol) Eq(v int64) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductIDCol) Ne(v int64) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductIDCol) In(vs ...int64) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "bigserial[]"}}
}

func (c ProductIDCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ProductIDCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ProductIDCol) Gt(v int64) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductIDCol) Lt(v int64) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductIDCol) Gte(v int64) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductIDCol) Lte(v int64) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductIDCol) Between(a, b int64) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// Sku returns the typed accessor for column sku.
func (t ProductTable) Sku() ProductSkuCol {
	return ProductSkuCol{core.Col{Table: "products", Name: "sku"}}
}

// ProductSkuCol is the typed column products.sku.
type ProductSkuCol struct{ core.Col }

func (c ProductSkuCol) Eq(v string) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductSkuCol) Ne(v string) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductSkuCol) In(vs ...string) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "text[]"}}
}

func (c ProductSkuCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ProductSkuCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ProductSkuCol) Like(p string) core.Expr {
	return core.Bin{Op: "LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ProductSkuCol) ILike(p string) core.Expr {
	return core.Bin{Op: "ILIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ProductSkuCol) NotLike(p string) core.Expr {
	return core.Bin{Op: "NOT LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ProductSkuCol) NotILike(p string) core.Expr {
	return core.Bin{Op: "NOT ILIKE", L: c.Col, R: core.Lit{V: p}}
}

// Title returns the typed accessor for column title.
func (t ProductTable) Title() ProductTitleCol {
	return ProductTitleCol{core.Col{Table: "products", Name: "title"}}
}

// ProductTitleCol is the typed column products.title.
type ProductTitleCol struct{ core.Col }

func (c ProductTitleCol) Eq(v string) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductTitleCol) Ne(v string) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductTitleCol) In(vs ...string) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "text[]"}}
}

func (c ProductTitleCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ProductTitleCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ProductTitleCol) Like(p string) core.Expr {
	return core.Bin{Op: "LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ProductTitleCol) ILike(p string) core.Expr {
	return core.Bin{Op: "ILIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ProductTitleCol) NotLike(p string) core.Expr {
	return core.Bin{Op: "NOT LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ProductTitleCol) NotILike(p string) core.Expr {
	return core.Bin{Op: "NOT ILIKE", L: c.Col, R: core.Lit{V: p}}
}

// Description returns the typed accessor for column description.
func (t ProductTable) Description() ProductDescriptionCol {
	return ProductDescriptionCol{core.Col{Table: "products", Name: "description"}}
}

// ProductDescriptionCol is the typed column products.description.
type ProductDescriptionCol struct{ core.Col }

func (c ProductDescriptionCol) Eq(v string) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductDescriptionCol) Ne(v string) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductDescriptionCol) In(vs ...string) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "text[]"}}
}

func (c ProductDescriptionCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ProductDescriptionCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ProductDescriptionCol) Like(p string) core.Expr {
	return core.Bin{Op: "LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ProductDescriptionCol) ILike(p string) core.Expr {
	return core.Bin{Op: "ILIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ProductDescriptionCol) NotLike(p string) core.Expr {
	return core.Bin{Op: "NOT LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ProductDescriptionCol) NotILike(p string) core.Expr {
	return core.Bin{Op: "NOT ILIKE", L: c.Col, R: core.Lit{V: p}}
}

// Category returns the typed accessor for column category.
func (t ProductTable) Category() ProductCategoryCol {
	return ProductCategoryCol{core.Col{Table: "products", Name: "category"}}
}

// ProductCategoryCol is the typed column products.category.
type ProductCategoryCol struct{ core.Col }

func (c ProductCategoryCol) Eq(v string) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductCategoryCol) Ne(v string) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductCategoryCol) In(vs ...string) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "text[]"}}
}

func (c ProductCategoryCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ProductCategoryCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ProductCategoryCol) Like(p string) core.Expr {
	return core.Bin{Op: "LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ProductCategoryCol) ILike(p string) core.Expr {
	return core.Bin{Op: "ILIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ProductCategoryCol) NotLike(p string) core.Expr {
	return core.Bin{Op: "NOT LIKE", L: c.Col, R: core.Lit{V: p}}
}

func (c ProductCategoryCol) NotILike(p string) core.Expr {
	return core.Bin{Op: "NOT ILIKE", L: c.Col, R: core.Lit{V: p}}
}

// Rating returns the typed accessor for column rating.
func (t ProductTable) Rating() ProductRatingCol {
	return ProductRatingCol{core.Col{Table: "products", Name: "rating"}}
}

// ProductRatingCol is the typed column products.rating.
type ProductRatingCol struct{ core.Col }

func (c ProductRatingCol) Eq(v pgtype.Numeric) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductRatingCol) Ne(v pgtype.Numeric) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductRatingCol) In(vs ...pgtype.Numeric) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "numeric[]"}}
}

func (c ProductRatingCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ProductRatingCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ProductRatingCol) Gt(v pgtype.Numeric) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductRatingCol) Lt(v pgtype.Numeric) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductRatingCol) Gte(v pgtype.Numeric) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductRatingCol) Lte(v pgtype.Numeric) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductRatingCol) Between(a, b pgtype.Numeric) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// Price returns the typed accessor for column price.
func (t ProductTable) Price() ProductPriceCol {
	return ProductPriceCol{core.Col{Table: "products", Name: "price"}}
}

// ProductPriceCol is the typed column products.price.
type ProductPriceCol struct{ core.Col }

func (c ProductPriceCol) Eq(v pgtype.Numeric) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductPriceCol) Ne(v pgtype.Numeric) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductPriceCol) In(vs ...pgtype.Numeric) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "numeric[]"}}
}

func (c ProductPriceCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ProductPriceCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ProductPriceCol) Gt(v pgtype.Numeric) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductPriceCol) Lt(v pgtype.Numeric) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductPriceCol) Gte(v pgtype.Numeric) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductPriceCol) Lte(v pgtype.Numeric) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductPriceCol) Between(a, b pgtype.Numeric) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// InStock returns the typed accessor for column in_stock.
func (t ProductTable) InStock() ProductInStockCol {
	return ProductInStockCol{core.Col{Table: "products", Name: "in_stock"}}
}

// ProductInStockCol is the typed column products.in_stock.
type ProductInStockCol struct{ core.Col }

func (c ProductInStockCol) Eq(v bool) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductInStockCol) Ne(v bool) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductInStockCol) In(vs ...bool) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "bool[]"}}
}

func (c ProductInStockCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ProductInStockCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

// Metadata returns the typed accessor for column metadata.
func (t ProductTable) Metadata() ProductMetadataCol {
	return ProductMetadataCol{core.Col{Table: "products", Name: "metadata"}}
}

// ProductMetadataCol is the typed column products.metadata.
type ProductMetadataCol struct{ core.Col }

func (c ProductMetadataCol) Eq(v []byte) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v, Cast: "jsonb"}}
}

func (c ProductMetadataCol) Ne(v []byte) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v, Cast: "jsonb"}}
}

func (c ProductMetadataCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ProductMetadataCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ProductMetadataCol) KeyEq(path string, v any) core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " ->> ?", Args: []any{path, v}}
}

// Embedding returns the typed accessor for column embedding.
func (t ProductTable) Embedding() ProductEmbeddingCol {
	return ProductEmbeddingCol{core.Col{Table: "products", Name: "embedding"}}
}

// ProductEmbeddingCol is the typed column products.embedding.
type ProductEmbeddingCol struct{ core.Col }

func (c ProductEmbeddingCol) Eq(v pgvector.Vector) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductEmbeddingCol) Ne(v pgvector.Vector) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductEmbeddingCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ProductEmbeddingCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

// CreatedAt returns the typed accessor for column created_at.
func (t ProductTable) CreatedAt() ProductCreatedAtCol {
	return ProductCreatedAtCol{core.Col{Table: "products", Name: "created_at"}}
}

// ProductCreatedAtCol is the typed column products.created_at.
type ProductCreatedAtCol struct{ core.Col }

func (c ProductCreatedAtCol) Eq(v pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: "=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductCreatedAtCol) Ne(v pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: "!=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductCreatedAtCol) In(vs ...pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: "= ANY", L: c.Col, R: core.Lit{V: vs, Cast: "timestamptz[]"}}
}

func (c ProductCreatedAtCol) IsNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ProductCreatedAtCol) NotNull() core.Expr {
	return core.Raw{SQL: core.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ProductCreatedAtCol) Gt(v pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: ">", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductCreatedAtCol) Lt(v pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: "<", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductCreatedAtCol) Gte(v pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductCreatedAtCol) Lte(v pgtype.Timestamptz) core.Expr {
	return core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: v}}
}

func (c ProductCreatedAtCol) Between(a, b pgtype.Timestamptz) core.Expr {
	return core.And{Parts: []core.Expr{
		core.Bin{Op: ">=", L: c.Col, R: core.Lit{V: a}},
		core.Bin{Op: "<=", L: c.Col, R: core.Lit{V: b}},
	}}
}

// Select starts a SELECT of every column; chain Where/OrderBy/Limit/...
// and terminate with Run (or a static function).
func (t ProductTable) Select() *core.Select {
	return core.NewSelect("public.products", core.Col{Table: "products", Name: "id"}, core.Col{Table: "products", Name: "sku"}, core.Col{Table: "products", Name: "title"}, core.Col{Table: "products", Name: "description"}, core.Col{Table: "products", Name: "category"}, core.Col{Table: "products", Name: "rating"}, core.Col{Table: "products", Name: "price"}, core.Col{Table: "products", Name: "in_stock"}, core.Col{Table: "products", Name: "metadata"}, core.Col{Table: "products", Name: "embedding"}, core.Col{Table: "products", Name: "created_at"})
}

// Update starts an UPDATE; an empty WHERE fails with core.ErrNoWhere.
func (t ProductTable) Update() *core.Update { return core.NewUpdate("public.products") }

// Delete starts a DELETE; an empty WHERE fails with core.ErrNoWhere.
func (t ProductTable) Delete() *core.Delete { return core.NewDelete("public.products") }
