// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	core "github.com/khoale-2804/pgb/core"
)

// Search surface for public.products (index products_search, key field id): predicate methods only
// on the columns the USING paradedb index covers, plus the scored document
// query. Every value stays a bound parameter; operator shapes live in
// core/search.go (the pg_search canon).
// Score ranks by the index key field: pdb.score(products.id).
func (t ProductTable) Score() core.Expr {
	return core.Score(core.Col{Table: "products", Name: "id"})
}

func (c ProductIDCol) Match(q string) core.Expr {
	return core.Match(c.Col, q)
}

func (c ProductIDCol) MatchAll(q string) core.Expr {
	return core.MatchAll(c.Col, q)
}

func (c ProductIDCol) Phrase(q string, slop int) core.Expr {
	return core.Phrase(c.Col, q, slop)
}

func (c ProductIDCol) Exact(v any) core.Expr {
	return core.Exact(c.Col, v)
}

func (c ProductIDCol) Fuzzy(q string, dist int, prefix bool) core.Expr {
	return core.Fuzzy(c.Col, q, dist, prefix)
}

func (c ProductIDCol) Regex(pattern string) core.Expr {
	return core.Regex(c.Col, pattern)
}

func (c ProductIDCol) Parse(q string) core.Expr {
	return core.Parse(c.Col, q, false)
}

func (c ProductIDCol) MatchB(q string, b float64) core.Expr {
	return core.Boost(core.Match(c.Col, q), b)
}

func (c ProductIDCol) RangeTerm(r any, mode string) core.Expr {
	return core.RangeTerm(c.Col, r, "int8range", mode)
}

func (c ProductIDCol) Snippet(startTag, endTag string, maxChars int) core.Expr {
	return core.Snippet(c.Col, startTag, endTag, maxChars)
}

func (c ProductIDCol) Snippets(limitN, offsetN int, sortBy string) core.Expr {
	return core.Snippets(c.Col, limitN, offsetN, sortBy)
}

func (c ProductIDCol) Highlight() core.Expr {
	return core.Highlight(c.Col)
}

func (c ProductTitleCol) Match(q string) core.Expr {
	return core.Match(c.Col, q)
}

func (c ProductTitleCol) MatchAll(q string) core.Expr {
	return core.MatchAll(c.Col, q)
}

func (c ProductTitleCol) Phrase(q string, slop int) core.Expr {
	return core.Phrase(c.Col, q, slop)
}

func (c ProductTitleCol) Exact(v any) core.Expr {
	return core.Exact(c.Col, v)
}

func (c ProductTitleCol) ExactAny(vs []string) core.Expr {
	return core.ExactAny(c.Col, vs, "text")
}

func (c ProductTitleCol) Fuzzy(q string, dist int, prefix bool) core.Expr {
	return core.Fuzzy(c.Col, q, dist, prefix)
}

func (c ProductTitleCol) Regex(pattern string) core.Expr {
	return core.Regex(c.Col, pattern)
}

func (c ProductTitleCol) Parse(q string) core.Expr {
	return core.Parse(c.Col, q, false)
}

func (c ProductTitleCol) MatchB(q string, b float64) core.Expr {
	return core.Boost(core.Match(c.Col, q), b)
}

func (c ProductTitleCol) Snippet(startTag, endTag string, maxChars int) core.Expr {
	return core.Snippet(c.Col, startTag, endTag, maxChars)
}

func (c ProductTitleCol) Snippets(limitN, offsetN int, sortBy string) core.Expr {
	return core.Snippets(c.Col, limitN, offsetN, sortBy)
}

func (c ProductTitleCol) Highlight() core.Expr {
	return core.Highlight(c.Col)
}

func (c ProductDescriptionCol) Match(q string) core.Expr {
	return core.Match(c.Col, q)
}

func (c ProductDescriptionCol) MatchAll(q string) core.Expr {
	return core.MatchAll(c.Col, q)
}

func (c ProductDescriptionCol) Phrase(q string, slop int) core.Expr {
	return core.Phrase(c.Col, q, slop)
}

func (c ProductDescriptionCol) Exact(v any) core.Expr {
	return core.Exact(c.Col, v)
}

func (c ProductDescriptionCol) ExactAny(vs []string) core.Expr {
	return core.ExactAny(c.Col, vs, "text")
}

func (c ProductDescriptionCol) Fuzzy(q string, dist int, prefix bool) core.Expr {
	return core.Fuzzy(c.Col, q, dist, prefix)
}

func (c ProductDescriptionCol) Regex(pattern string) core.Expr {
	return core.Regex(c.Col, pattern)
}

func (c ProductDescriptionCol) Parse(q string) core.Expr {
	return core.Parse(c.Col, q, false)
}

func (c ProductDescriptionCol) MatchB(q string, b float64) core.Expr {
	return core.Boost(core.Match(c.Col, q), b)
}

func (c ProductDescriptionCol) Snippet(startTag, endTag string, maxChars int) core.Expr {
	return core.Snippet(c.Col, startTag, endTag, maxChars)
}

func (c ProductDescriptionCol) Snippets(limitN, offsetN int, sortBy string) core.Expr {
	return core.Snippets(c.Col, limitN, offsetN, sortBy)
}

func (c ProductDescriptionCol) Highlight() core.Expr {
	return core.Highlight(c.Col)
}

// ProductMetadataColorCol carries the pg_search surface for the indexed JSON path
// products.metadata->'color' (index alias json_color): the path is re-emitted exactly as indexed,
// through core.Raw. No Boost composition (MatchB) or snippets on path
// fields.
type ProductMetadataColorCol struct{ core.Col }

func (c ProductMetadataColorCol) Match(q string) core.Expr {
	return core.Raw{SQL: "products.metadata->'color' ||| ?", Args: []any{q}}
}

func (c ProductMetadataColorCol) MatchAll(q string) core.Expr {
	return core.Raw{SQL: "products.metadata->'color' &&& ?", Args: []any{q}}
}

func (c ProductMetadataColorCol) Exact(v any) core.Expr {
	return core.Raw{SQL: "products.metadata->'color' === ?", Args: []any{v}}
}

func (c ProductMetadataColorCol) ExactAny(vs []string) core.Expr {
	return core.Raw{SQL: "products.metadata->'color' === ?::text[]", Args: []any{vs}}
}

func (c ProductMetadataColorCol) Regex(pattern string) core.Expr {
	return core.Raw{SQL: "products.metadata->'color' @@@ pdb.regex(?)", Args: []any{pattern}}
}

func (c ProductMetadataColorCol) Parse(q string) core.Expr {
	return core.Raw{SQL: "products.metadata->'color' @@@ pdb.parse(?)", Args: []any{q}}
}

func (c ProductRatingCol) Match(q string) core.Expr {
	return core.Match(c.Col, q)
}

func (c ProductRatingCol) MatchAll(q string) core.Expr {
	return core.MatchAll(c.Col, q)
}

func (c ProductRatingCol) Phrase(q string, slop int) core.Expr {
	return core.Phrase(c.Col, q, slop)
}

func (c ProductRatingCol) Exact(v any) core.Expr {
	return core.Exact(c.Col, v)
}

func (c ProductRatingCol) Fuzzy(q string, dist int, prefix bool) core.Expr {
	return core.Fuzzy(c.Col, q, dist, prefix)
}

func (c ProductRatingCol) Regex(pattern string) core.Expr {
	return core.Regex(c.Col, pattern)
}

func (c ProductRatingCol) Parse(q string) core.Expr {
	return core.Parse(c.Col, q, false)
}

func (c ProductRatingCol) MatchB(q string, b float64) core.Expr {
	return core.Boost(core.Match(c.Col, q), b)
}

func (c ProductRatingCol) RangeTerm(r any, mode string) core.Expr {
	return core.RangeTerm(c.Col, r, "numrange", mode)
}

func (c ProductRatingCol) Snippet(startTag, endTag string, maxChars int) core.Expr {
	return core.Snippet(c.Col, startTag, endTag, maxChars)
}

func (c ProductRatingCol) Snippets(limitN, offsetN int, sortBy string) core.Expr {
	return core.Snippets(c.Col, limitN, offsetN, sortBy)
}

func (c ProductRatingCol) Highlight() core.Expr {
	return core.Highlight(c.Col)
}

// SearchProductsOpts keeps the search entry surface small: Limit caps the
// result (<= 0 falls back to 20 — every generated search ends in an
// ordered LIMIT so ParadeDB can push Top-K down); SnippetCol optionally
// names one indexed column to project a pdb.snippet fragment for.
type SearchProductsOpts struct {
	Limit      int
	SnippetCol string
}

// ProductHit is one SearchProducts result row: the full model, the BM25 score,
// and the snippet fragment (populated only when SearchProductsOpts.SnippetCol
// selected one, NULL/zero otherwise).
type ProductHit struct {
	Product Product
	Score   float64
	Snippet pgtype.Text
}

// ScanProducts scans one SearchProducts row positionally: every products column
// in catalog order, then the score. Rows requested with a snippet
// projection carry one extra trailing column — SearchProducts scans those
// rows itself.
func ScanProducts(row pgx.CollectableRow) (ProductHit, error) {
	var h ProductHit
	var p Product
	if err := row.Scan(&p.ID, &p.Sku, &p.Title, &p.Description, &p.Category, &p.Rating, &p.Price, &p.InStock, &p.Metadata, &p.Embedding, &p.CreatedAt, &h.Score); err != nil {
		return ProductHit{}, err
	}
	h.Product = p
	return h, nil
}

// SearchProducts runs the generic document query against the index key
// field: WHERE id @@@ pdb.parse($1) — pdb.parse carries ParadeDB's full
// query-string syntax — selecting every column plus pdb.score(id),
// optionally one pdb.snippet fragment, ordered pdb.score(id) DESC,
// id ASC and LIMIT-bounded.
func SearchProducts(ctx context.Context, exec core.DBTX, q string, o SearchProductsOpts) ([]ProductHit, error) {
	limit := o.Limit
	if limit <= 0 {
		limit = 20
	}
	key := core.Col{Table: "products", Name: "id"}
	cols := []core.Expr{core.Col{Table: "products", Name: "id"}, core.Col{Table: "products", Name: "sku"}, core.Col{Table: "products", Name: "title"}, core.Col{Table: "products", Name: "description"}, core.Col{Table: "products", Name: "category"}, core.Col{Table: "products", Name: "rating"}, core.Col{Table: "products", Name: "price"}, core.Col{Table: "products", Name: "in_stock"}, core.Col{Table: "products", Name: "metadata"}, core.Col{Table: "products", Name: "embedding"}, core.Col{Table: "products", Name: "created_at"}, core.Score(key)}
	if o.SnippetCol != "" {
		cols = append(cols, core.Snippet(core.Col{Table: "products", Name: o.SnippetCol}, "", "", 0))
	}
	rows, err := core.NewSelect("public.products", cols...).
		WhereExpr(core.Parse(key, q, false)).
		OrderBy(core.Desc(core.Score(key)), core.Asc(key)).
		Limit(limit).
		Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	if o.SnippetCol == "" {
		return pgx.CollectRows(rows, ScanProducts)
	}
	return pgx.CollectRows(rows, func(row pgx.CollectableRow) (ProductHit, error) {
		var h ProductHit
		var p Product
		if err := row.Scan(&p.ID, &p.Sku, &p.Title, &p.Description, &p.Category, &p.Rating, &p.Price, &p.InStock, &p.Metadata, &p.Embedding, &p.CreatedAt, &h.Score, &h.Snippet); err != nil {
			return ProductHit{}, err
		}
		h.Product = p
		return h, nil
	})
}
