// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"errors"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	core "github.com/khoale-2804/pgb/core"
	"github.com/pgvector/pgvector-go"
)

// ProductFilter narrows ListProducts and CountProducts:
// nil / zero fields are ignored; Extra composes raw predicates.
type ProductFilter struct {
	ID               *int64
	IDIn             []int64
	IDGt             *int64
	IDLt             *int64
	IDGte            *int64
	IDLte            *int64
	Sku              *string
	SkuIn            []string
	SkuLike          *string
	SkuILike         *string
	Title            *string
	TitleIn          []string
	TitleLike        *string
	TitleILike       *string
	Description      *string
	DescriptionIn    []string
	DescriptionLike  *string
	DescriptionILike *string
	Category         *string
	CategoryIn       []string
	CategoryLike     *string
	CategoryILike    *string
	Rating           *pgtype.Numeric
	RatingIn         []pgtype.Numeric
	RatingGt         *pgtype.Numeric
	RatingLt         *pgtype.Numeric
	RatingGte        *pgtype.Numeric
	RatingLte        *pgtype.Numeric
	Price            *pgtype.Numeric
	PriceIn          []pgtype.Numeric
	PriceGt          *pgtype.Numeric
	PriceLt          *pgtype.Numeric
	PriceGte         *pgtype.Numeric
	PriceLte         *pgtype.Numeric
	InStock          *bool
	InStockIn        []bool
	Metadata         *[]byte
	Embedding        *pgvector.Vector
	CreatedAt        *pgtype.Timestamptz
	CreatedAtIn      []pgtype.Timestamptz
	CreatedAtGt      *pgtype.Timestamptz
	CreatedAtLt      *pgtype.Timestamptz
	CreatedAtGte     *pgtype.Timestamptz
	CreatedAtLte     *pgtype.Timestamptz
	Extra            []core.Expr
}

// productsFilterWhere compiles f into the ANDed predicate list; an empty
// filter yields an empty list (no WHERE).
func productsFilterWhere(f ProductFilter) []core.Expr {
	var w []core.Expr
	if f.ID != nil {
		w = append(w, Products.ID().Eq(*f.ID))
	}
	if len(f.IDIn) > 0 {
		w = append(w, Products.ID().In(f.IDIn...))
	}
	if f.IDGt != nil {
		w = append(w, Products.ID().Gt(*f.IDGt))
	}
	if f.IDLt != nil {
		w = append(w, Products.ID().Lt(*f.IDLt))
	}
	if f.IDGte != nil {
		w = append(w, Products.ID().Gte(*f.IDGte))
	}
	if f.IDLte != nil {
		w = append(w, Products.ID().Lte(*f.IDLte))
	}
	if f.Sku != nil {
		w = append(w, Products.Sku().Eq(*f.Sku))
	}
	if len(f.SkuIn) > 0 {
		w = append(w, Products.Sku().In(f.SkuIn...))
	}
	if f.SkuLike != nil {
		w = append(w, Products.Sku().Like(*f.SkuLike))
	}
	if f.SkuILike != nil {
		w = append(w, Products.Sku().ILike(*f.SkuILike))
	}
	if f.Title != nil {
		w = append(w, Products.Title().Eq(*f.Title))
	}
	if len(f.TitleIn) > 0 {
		w = append(w, Products.Title().In(f.TitleIn...))
	}
	if f.TitleLike != nil {
		w = append(w, Products.Title().Like(*f.TitleLike))
	}
	if f.TitleILike != nil {
		w = append(w, Products.Title().ILike(*f.TitleILike))
	}
	if f.Description != nil {
		w = append(w, Products.Description().Eq(*f.Description))
	}
	if len(f.DescriptionIn) > 0 {
		w = append(w, Products.Description().In(f.DescriptionIn...))
	}
	if f.DescriptionLike != nil {
		w = append(w, Products.Description().Like(*f.DescriptionLike))
	}
	if f.DescriptionILike != nil {
		w = append(w, Products.Description().ILike(*f.DescriptionILike))
	}
	if f.Category != nil {
		w = append(w, Products.Category().Eq(*f.Category))
	}
	if len(f.CategoryIn) > 0 {
		w = append(w, Products.Category().In(f.CategoryIn...))
	}
	if f.CategoryLike != nil {
		w = append(w, Products.Category().Like(*f.CategoryLike))
	}
	if f.CategoryILike != nil {
		w = append(w, Products.Category().ILike(*f.CategoryILike))
	}
	if f.Rating != nil {
		w = append(w, Products.Rating().Eq(*f.Rating))
	}
	if len(f.RatingIn) > 0 {
		w = append(w, Products.Rating().In(f.RatingIn...))
	}
	if f.RatingGt != nil {
		w = append(w, Products.Rating().Gt(*f.RatingGt))
	}
	if f.RatingLt != nil {
		w = append(w, Products.Rating().Lt(*f.RatingLt))
	}
	if f.RatingGte != nil {
		w = append(w, Products.Rating().Gte(*f.RatingGte))
	}
	if f.RatingLte != nil {
		w = append(w, Products.Rating().Lte(*f.RatingLte))
	}
	if f.Price != nil {
		w = append(w, Products.Price().Eq(*f.Price))
	}
	if len(f.PriceIn) > 0 {
		w = append(w, Products.Price().In(f.PriceIn...))
	}
	if f.PriceGt != nil {
		w = append(w, Products.Price().Gt(*f.PriceGt))
	}
	if f.PriceLt != nil {
		w = append(w, Products.Price().Lt(*f.PriceLt))
	}
	if f.PriceGte != nil {
		w = append(w, Products.Price().Gte(*f.PriceGte))
	}
	if f.PriceLte != nil {
		w = append(w, Products.Price().Lte(*f.PriceLte))
	}
	if f.InStock != nil {
		w = append(w, Products.InStock().Eq(*f.InStock))
	}
	if len(f.InStockIn) > 0 {
		w = append(w, Products.InStock().In(f.InStockIn...))
	}
	if f.Metadata != nil {
		w = append(w, Products.Metadata().Eq(*f.Metadata))
	}
	if f.Embedding != nil {
		w = append(w, Products.Embedding().Eq(*f.Embedding))
	}
	if f.CreatedAt != nil {
		w = append(w, Products.CreatedAt().Eq(*f.CreatedAt))
	}
	if len(f.CreatedAtIn) > 0 {
		w = append(w, Products.CreatedAt().In(f.CreatedAtIn...))
	}
	if f.CreatedAtGt != nil {
		w = append(w, Products.CreatedAt().Gt(*f.CreatedAtGt))
	}
	if f.CreatedAtLt != nil {
		w = append(w, Products.CreatedAt().Lt(*f.CreatedAtLt))
	}
	if f.CreatedAtGte != nil {
		w = append(w, Products.CreatedAt().Gte(*f.CreatedAtGte))
	}
	if f.CreatedAtLte != nil {
		w = append(w, Products.CreatedAt().Lte(*f.CreatedAtLte))
	}
	w = append(w, f.Extra...)
	return w
}

// ProductSet is the three-state UPDATE payload: a zero Set field
// skips its column, SetOf writes a value, SetNull writes NULL.
type ProductSet struct {
	Sku         Set[string]
	Title       Set[string]
	Description Set[string]
	Category    Set[string]
	Rating      Set[pgtype.Numeric]
	Price       Set[pgtype.Numeric]
	InStock     Set[bool]
	Metadata    Set[[]byte]
	Embedding   Set[pgvector.Vector]
	CreatedAt   Set[pgtype.Timestamptz]
}

// InsertProductParams carries the INSERT column values: generated
// and serial columns are out, default-bearing columns join only with
// the include_defaults option.
type InsertProductParams struct {
	Sku         string
	Title       string
	Description string
	Category    string
	Rating      pgtype.Numeric
	Price       pgtype.Numeric
	InStock     bool
	Metadata    []byte
	Embedding   pgvector.Vector
	CreatedAt   pgtype.Timestamptz
}

// scanProduct scans one row positionally over every column in
// catalog order — the single scan path for all generated reads.
func scanProduct(row pgx.CollectableRow) (Product, error) {
	var m Product
	if err := row.Scan(&m.ID, &m.Sku, &m.Title, &m.Description, &m.Category, &m.Rating, &m.Price, &m.InStock, &m.Metadata, &m.Embedding, &m.CreatedAt); err != nil {
		return Product{}, err
	}
	return m, nil
}

// GetProduct returns one row by id; core.ErrNotFound when absent
// (pgx.ErrNoRows mapped — errors.Is keeps working for both).
func GetProduct(ctx context.Context, exec core.DBTX, id int64) (Product, error) {
	sql, args := Products.Select().Where(Products.ID().Eq(id)).SQL()
	var m Product
	err := exec.QueryRow(ctx, sql, args...).Scan(&m.ID, &m.Sku, &m.Title, &m.Description, &m.Category, &m.Rating, &m.Price, &m.InStock, &m.Metadata, &m.Embedding, &m.CreatedAt)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Product{}, core.ErrNotFound
		}
		return Product{}, err
	}
	return m, nil
}

// ListProducts returns the rows matching f; limit <= 0 means no LIMIT.
func ListProducts(ctx context.Context, exec core.DBTX, f ProductFilter, limit int) ([]Product, error) {
	rows, err := Products.Select().Where(productsFilterWhere(f)...).Limit(limit).Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanProduct)
}

// CountProducts counts the rows matching f.
func CountProducts(ctx context.Context, exec core.DBTX, f ProductFilter) (int64, error) {
	sql, args := core.NewSelect("public.products", core.Raw{SQL: "count(*)"}).Where(productsFilterWhere(f)...).SQL()
	var n int64
	if err := exec.QueryRow(ctx, sql, args...).Scan(&n); err != nil {
		return 0, err
	}
	return n, nil
}

// InsertProduct inserts one row and returns it (RETURNING every
// column, defaults included).
func InsertProduct(ctx context.Context, exec core.DBTX, p InsertProductParams) (Product, error) {
	rows, err := core.NewInsert("public.products",
		[]string{"sku", "title", "description", "category", "rating", "price", "in_stock", "metadata", "embedding", "created_at"},
		[]core.Expr{core.Lit{V: p.Sku}, core.Lit{V: p.Title}, core.Lit{V: p.Description}, core.Lit{V: p.Category}, core.Lit{V: p.Rating}, core.Lit{V: p.Price}, core.Lit{V: p.InStock}, core.Lit{V: p.Metadata, Cast: "jsonb"}, core.Lit{V: p.Embedding}, core.Lit{V: p.CreatedAt}},
	).Returning(core.Col{Table: "products", Name: "id"}, core.Col{Table: "products", Name: "sku"}, core.Col{Table: "products", Name: "title"}, core.Col{Table: "products", Name: "description"}, core.Col{Table: "products", Name: "category"}, core.Col{Table: "products", Name: "rating"}, core.Col{Table: "products", Name: "price"}, core.Col{Table: "products", Name: "in_stock"}, core.Col{Table: "products", Name: "metadata"}, core.Col{Table: "products", Name: "embedding"}, core.Col{Table: "products", Name: "created_at"}).Run(ctx, exec)
	if err != nil {
		return Product{}, err
	}
	us, err := pgx.CollectRows(rows, scanProduct)
	if err != nil {
		return Product{}, err
	}
	if len(us) == 0 {
		return Product{}, core.ErrNotFound
	}
	return us[0], nil
}

const insertProductsSQL = "INSERT INTO public.products (sku, title, description, category, rating, price, in_stock, metadata, embedding, created_at) SELECT * FROM unnest($1::text[], $2::text[], $3::text[], $4::text[], $5::numeric[], $6::numeric[], $7::bool[], $8::jsonb[], $9::vector[], $10::timestamptz[]) RETURNING id, sku, title, description, category, rating, price, in_stock, metadata, embedding, created_at"

// InsertProducts inserts a whole batch in one round trip via
// unnest and returns every inserted row.
func InsertProducts(ctx context.Context, exec core.DBTX, ps []InsertProductParams) ([]Product, error) {
	if len(ps) == 0 {
		return nil, nil
	}
	colSku := make([]string, len(ps))
	colTitle := make([]string, len(ps))
	colDescription := make([]string, len(ps))
	colCategory := make([]string, len(ps))
	colRating := make([]pgtype.Numeric, len(ps))
	colPrice := make([]pgtype.Numeric, len(ps))
	colInStock := make([]bool, len(ps))
	colMetadata := make([][]byte, len(ps))
	colEmbedding := make([]pgvector.Vector, len(ps))
	colCreatedAt := make([]pgtype.Timestamptz, len(ps))
	for i, p := range ps {
		colSku[i] = p.Sku
		colTitle[i] = p.Title
		colDescription[i] = p.Description
		colCategory[i] = p.Category
		colRating[i] = p.Rating
		colPrice[i] = p.Price
		colInStock[i] = p.InStock
		colMetadata[i] = p.Metadata
		colEmbedding[i] = p.Embedding
		colCreatedAt[i] = p.CreatedAt
	}
	args := make([]any, 0, 10*len(ps))
	args = append(args, colSku, colTitle, colDescription, colCategory, colRating, colPrice, colInStock, colMetadata, colEmbedding, colCreatedAt)
	rows, err := exec.Query(ctx, insertProductsSQL, args...)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanProduct)
}

// UpdateProduct applies the non-zero fields of s to one row and
// returns the updated row; core.ErrNotFound when absent.
func UpdateProduct(ctx context.Context, exec core.DBTX, id int64, s ProductSet) (Product, error) {
	u := Products.Update()
	n := 0
	if s.Sku.Valid {
		n++
		if s.Sku.Null {
			u.Set("sku", core.Lit{V: nil})
		} else {
			u.Set("sku", core.Lit{V: s.Sku.V})
		}
	}
	if s.Title.Valid {
		n++
		if s.Title.Null {
			u.Set("title", core.Lit{V: nil})
		} else {
			u.Set("title", core.Lit{V: s.Title.V})
		}
	}
	if s.Description.Valid {
		n++
		if s.Description.Null {
			u.Set("description", core.Lit{V: nil})
		} else {
			u.Set("description", core.Lit{V: s.Description.V})
		}
	}
	if s.Category.Valid {
		n++
		if s.Category.Null {
			u.Set("category", core.Lit{V: nil})
		} else {
			u.Set("category", core.Lit{V: s.Category.V})
		}
	}
	if s.Rating.Valid {
		n++
		if s.Rating.Null {
			u.Set("rating", core.Lit{V: nil})
		} else {
			u.Set("rating", core.Lit{V: s.Rating.V})
		}
	}
	if s.Price.Valid {
		n++
		if s.Price.Null {
			u.Set("price", core.Lit{V: nil})
		} else {
			u.Set("price", core.Lit{V: s.Price.V})
		}
	}
	if s.InStock.Valid {
		n++
		if s.InStock.Null {
			u.Set("in_stock", core.Lit{V: nil})
		} else {
			u.Set("in_stock", core.Lit{V: s.InStock.V})
		}
	}
	if s.Metadata.Valid {
		n++
		if s.Metadata.Null {
			u.Set("metadata", core.Lit{V: nil})
		} else {
			u.Set("metadata", core.Lit{V: s.Metadata.V, Cast: "jsonb"})
		}
	}
	if s.Embedding.Valid {
		n++
		if s.Embedding.Null {
			u.Set("embedding", core.Lit{V: nil})
		} else {
			u.Set("embedding", core.Lit{V: s.Embedding.V})
		}
	}
	if s.CreatedAt.Valid {
		n++
		if s.CreatedAt.Null {
			u.Set("created_at", core.Lit{V: nil})
		} else {
			u.Set("created_at", core.Lit{V: s.CreatedAt.V})
		}
	}
	if n == 0 {
		return GetProduct(ctx, exec, id)
	}
	u.Where(Products.ID().Eq(id)).Returning(core.Col{Table: "products", Name: "id"}, core.Col{Table: "products", Name: "sku"}, core.Col{Table: "products", Name: "title"}, core.Col{Table: "products", Name: "description"}, core.Col{Table: "products", Name: "category"}, core.Col{Table: "products", Name: "rating"}, core.Col{Table: "products", Name: "price"}, core.Col{Table: "products", Name: "in_stock"}, core.Col{Table: "products", Name: "metadata"}, core.Col{Table: "products", Name: "embedding"}, core.Col{Table: "products", Name: "created_at"})
	rows, err := u.Run(ctx, exec)
	if err != nil {
		return Product{}, err
	}
	us, err := pgx.CollectRows(rows, scanProduct)
	if err != nil {
		return Product{}, err
	}
	if len(us) == 0 {
		return Product{}, core.ErrNotFound
	}
	return us[0], nil
}

// UpdateProducts applies s to every row matching where and
// returns the affected count; an empty where is refused with
// core.ErrNoWhere before any SQL is sent.
func UpdateProducts(ctx context.Context, exec core.DBTX, where []core.Expr, s ProductSet) (int64, error) {
	u := Products.Update()
	n := 0
	if s.Sku.Valid {
		n++
		if s.Sku.Null {
			u.Set("sku", core.Lit{V: nil})
		} else {
			u.Set("sku", core.Lit{V: s.Sku.V})
		}
	}
	if s.Title.Valid {
		n++
		if s.Title.Null {
			u.Set("title", core.Lit{V: nil})
		} else {
			u.Set("title", core.Lit{V: s.Title.V})
		}
	}
	if s.Description.Valid {
		n++
		if s.Description.Null {
			u.Set("description", core.Lit{V: nil})
		} else {
			u.Set("description", core.Lit{V: s.Description.V})
		}
	}
	if s.Category.Valid {
		n++
		if s.Category.Null {
			u.Set("category", core.Lit{V: nil})
		} else {
			u.Set("category", core.Lit{V: s.Category.V})
		}
	}
	if s.Rating.Valid {
		n++
		if s.Rating.Null {
			u.Set("rating", core.Lit{V: nil})
		} else {
			u.Set("rating", core.Lit{V: s.Rating.V})
		}
	}
	if s.Price.Valid {
		n++
		if s.Price.Null {
			u.Set("price", core.Lit{V: nil})
		} else {
			u.Set("price", core.Lit{V: s.Price.V})
		}
	}
	if s.InStock.Valid {
		n++
		if s.InStock.Null {
			u.Set("in_stock", core.Lit{V: nil})
		} else {
			u.Set("in_stock", core.Lit{V: s.InStock.V})
		}
	}
	if s.Metadata.Valid {
		n++
		if s.Metadata.Null {
			u.Set("metadata", core.Lit{V: nil})
		} else {
			u.Set("metadata", core.Lit{V: s.Metadata.V, Cast: "jsonb"})
		}
	}
	if s.Embedding.Valid {
		n++
		if s.Embedding.Null {
			u.Set("embedding", core.Lit{V: nil})
		} else {
			u.Set("embedding", core.Lit{V: s.Embedding.V})
		}
	}
	if s.CreatedAt.Valid {
		n++
		if s.CreatedAt.Null {
			u.Set("created_at", core.Lit{V: nil})
		} else {
			u.Set("created_at", core.Lit{V: s.CreatedAt.V})
		}
	}
	if n == 0 {
		return 0, nil
	}
	if len(where) == 0 {
		return 0, core.ErrNoWhere
	}
	u.Where(where...)
	tag, err := u.Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// UpsertProduct inserts p under id, or on conflict updates
// every settable column from the proposed row (EXCLUDED.*) and returns
// the resulting row; core.ErrNotFound when DO NOTHING matched.
func UpsertProduct(ctx context.Context, exec core.DBTX, id int64, p InsertProductParams) (Product, error) {
	rows, err := core.NewInsert("public.products",
		[]string{"id", "sku", "title", "description", "category", "rating", "price", "in_stock", "metadata", "embedding", "created_at"},
		[]core.Expr{core.Lit{V: id}, core.Lit{V: p.Sku}, core.Lit{V: p.Title}, core.Lit{V: p.Description}, core.Lit{V: p.Category}, core.Lit{V: p.Rating}, core.Lit{V: p.Price}, core.Lit{V: p.InStock}, core.Lit{V: p.Metadata, Cast: "jsonb"}, core.Lit{V: p.Embedding}, core.Lit{V: p.CreatedAt}},
	).OnConflict(core.OnConflict{
		Target: []string{"id"},
		Sets: []core.SetClause{
			{Col: "sku", E: core.Col{Table: "excluded", Name: "sku"}},
			{Col: "title", E: core.Col{Table: "excluded", Name: "title"}},
			{Col: "description", E: core.Col{Table: "excluded", Name: "description"}},
			{Col: "category", E: core.Col{Table: "excluded", Name: "category"}},
			{Col: "rating", E: core.Col{Table: "excluded", Name: "rating"}},
			{Col: "price", E: core.Col{Table: "excluded", Name: "price"}},
			{Col: "in_stock", E: core.Col{Table: "excluded", Name: "in_stock"}},
			{Col: "metadata", E: core.Col{Table: "excluded", Name: "metadata"}},
			{Col: "embedding", E: core.Col{Table: "excluded", Name: "embedding"}},
			{Col: "created_at", E: core.Col{Table: "excluded", Name: "created_at"}},
		},
	}).Returning(core.Col{Table: "products", Name: "id"}, core.Col{Table: "products", Name: "sku"}, core.Col{Table: "products", Name: "title"}, core.Col{Table: "products", Name: "description"}, core.Col{Table: "products", Name: "category"}, core.Col{Table: "products", Name: "rating"}, core.Col{Table: "products", Name: "price"}, core.Col{Table: "products", Name: "in_stock"}, core.Col{Table: "products", Name: "metadata"}, core.Col{Table: "products", Name: "embedding"}, core.Col{Table: "products", Name: "created_at"}).Run(ctx, exec)
	if err != nil {
		return Product{}, err
	}
	us, err := pgx.CollectRows(rows, scanProduct)
	if err != nil {
		return Product{}, err
	}
	if len(us) == 0 {
		return Product{}, core.ErrNotFound
	}
	return us[0], nil
}

// DeleteProduct removes one row by id.
func DeleteProduct(ctx context.Context, exec core.DBTX, id int64) error {
	_, err := Products.Delete().Where(Products.ID().Eq(id)).Exec(ctx, exec)
	return err
}

// DeleteProducts removes every row matching where and returns the
// affected count; an empty where is refused with core.ErrNoWhere.
func DeleteProducts(ctx context.Context, exec core.DBTX, where []core.Expr) (int64, error) {
	if len(where) == 0 {
		return 0, core.ErrNoWhere
	}
	tag, err := Products.Delete().Where(where...).Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
