// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	pgb "github.com/khoale-2804/pgb/core"
)

// Search surface for public.products (index products_search, key field id): predicate methods only
// on the columns the USING paradedb index covers, plus the scored document
// query. Every value stays a bound parameter; operator shapes live in
// core/search.go (the pg_search canon).
// Score ranks by the index key field: pdb.score(products.id).
func (t ProductTable) Score() pgb.Expr {
	return pgb.Score(pgb.Col{Table: "products", Name: "id"})
}

func (c ProductIDCol) Match(q string) pgb.Expr {
	return pgb.Match(c.Col, q)
}

func (c ProductIDCol) MatchAll(q string) pgb.Expr {
	return pgb.MatchAll(c.Col, q)
}

func (c ProductIDCol) Phrase(q string, slop int) pgb.Expr {
	return pgb.Phrase(c.Col, q, slop)
}

func (c ProductIDCol) Exact(v any) pgb.Expr {
	return pgb.Exact(c.Col, v)
}

func (c ProductIDCol) Fuzzy(q string, dist int, prefix bool) pgb.Expr {
	return pgb.Fuzzy(c.Col, q, dist, prefix)
}

func (c ProductIDCol) Regex(pattern string) pgb.Expr {
	return pgb.Regex(c.Col, pattern)
}

func (c ProductIDCol) Parse(q string) pgb.Expr {
	return pgb.Parse(c.Col, q, false)
}

func (c ProductIDCol) MatchB(q string, b float64) pgb.Expr {
	return pgb.Boost(pgb.Match(c.Col, q), b)
}

func (c ProductIDCol) RangeTerm(r any, mode string) pgb.Expr {
	return pgb.RangeTerm(c.Col, r, "int8range", mode)
}

func (c ProductIDCol) Snippet(startTag, endTag string, maxChars int) pgb.Expr {
	return pgb.Snippet(c.Col, startTag, endTag, maxChars)
}

func (c ProductIDCol) Snippets(limitN, offsetN int, sortBy string) pgb.Expr {
	return pgb.Snippets(c.Col, limitN, offsetN, sortBy)
}

func (c ProductIDCol) Highlight() pgb.Expr {
	return pgb.Highlight(c.Col)
}

func (c ProductTitleCol) Match(q string) pgb.Expr {
	return pgb.Match(c.Col, q)
}

func (c ProductTitleCol) MatchAll(q string) pgb.Expr {
	return pgb.MatchAll(c.Col, q)
}

func (c ProductTitleCol) Phrase(q string, slop int) pgb.Expr {
	return pgb.Phrase(c.Col, q, slop)
}

func (c ProductTitleCol) Exact(v any) pgb.Expr {
	return pgb.Exact(c.Col, v)
}

func (c ProductTitleCol) ExactAny(vs []string) pgb.Expr {
	return pgb.ExactAny(c.Col, vs, "text")
}

func (c ProductTitleCol) Fuzzy(q string, dist int, prefix bool) pgb.Expr {
	return pgb.Fuzzy(c.Col, q, dist, prefix)
}

func (c ProductTitleCol) Regex(pattern string) pgb.Expr {
	return pgb.Regex(c.Col, pattern)
}

func (c ProductTitleCol) Parse(q string) pgb.Expr {
	return pgb.Parse(c.Col, q, false)
}

func (c ProductTitleCol) MatchB(q string, b float64) pgb.Expr {
	return pgb.Boost(pgb.Match(c.Col, q), b)
}

func (c ProductTitleCol) Snippet(startTag, endTag string, maxChars int) pgb.Expr {
	return pgb.Snippet(c.Col, startTag, endTag, maxChars)
}

func (c ProductTitleCol) Snippets(limitN, offsetN int, sortBy string) pgb.Expr {
	return pgb.Snippets(c.Col, limitN, offsetN, sortBy)
}

func (c ProductTitleCol) Highlight() pgb.Expr {
	return pgb.Highlight(c.Col)
}

func (c ProductDescriptionCol) Match(q string) pgb.Expr {
	return pgb.Match(c.Col, q)
}

func (c ProductDescriptionCol) MatchAll(q string) pgb.Expr {
	return pgb.MatchAll(c.Col, q)
}

func (c ProductDescriptionCol) Phrase(q string, slop int) pgb.Expr {
	return pgb.Phrase(c.Col, q, slop)
}

func (c ProductDescriptionCol) Exact(v any) pgb.Expr {
	return pgb.Exact(c.Col, v)
}

func (c ProductDescriptionCol) ExactAny(vs []string) pgb.Expr {
	return pgb.ExactAny(c.Col, vs, "text")
}

func (c ProductDescriptionCol) Fuzzy(q string, dist int, prefix bool) pgb.Expr {
	return pgb.Fuzzy(c.Col, q, dist, prefix)
}

func (c ProductDescriptionCol) Regex(pattern string) pgb.Expr {
	return pgb.Regex(c.Col, pattern)
}

func (c ProductDescriptionCol) Parse(q string) pgb.Expr {
	return pgb.Parse(c.Col, q, false)
}

func (c ProductDescriptionCol) MatchB(q string, b float64) pgb.Expr {
	return pgb.Boost(pgb.Match(c.Col, q), b)
}

func (c ProductDescriptionCol) Snippet(startTag, endTag string, maxChars int) pgb.Expr {
	return pgb.Snippet(c.Col, startTag, endTag, maxChars)
}

func (c ProductDescriptionCol) Snippets(limitN, offsetN int, sortBy string) pgb.Expr {
	return pgb.Snippets(c.Col, limitN, offsetN, sortBy)
}

func (c ProductDescriptionCol) Highlight() pgb.Expr {
	return pgb.Highlight(c.Col)
}

// ProductMetadataColorCol carries the pg_search surface for the indexed JSON path
// products.metadata->'color' (index alias json_color): the path is re-emitted exactly as indexed,
// through pgb.Raw. No Boost composition (MatchB) or snippets on path
// fields.
type ProductMetadataColorCol struct{ pgb.Col }

func (c ProductMetadataColorCol) Match(q string) pgb.Expr {
	return pgb.Raw{SQL: "products.metadata->'color' ||| ?", Args: []any{q}}
}

func (c ProductMetadataColorCol) MatchAll(q string) pgb.Expr {
	return pgb.Raw{SQL: "products.metadata->'color' &&& ?", Args: []any{q}}
}

func (c ProductMetadataColorCol) Exact(v any) pgb.Expr {
	return pgb.Raw{SQL: "products.metadata->'color' === ?", Args: []any{v}}
}

func (c ProductMetadataColorCol) ExactAny(vs []string) pgb.Expr {
	return pgb.Raw{SQL: "products.metadata->'color' === ?::text[]", Args: []any{vs}}
}

func (c ProductMetadataColorCol) Regex(pattern string) pgb.Expr {
	return pgb.Raw{SQL: "products.metadata->'color' @@@ pdb.regex(?)", Args: []any{pattern}}
}

func (c ProductMetadataColorCol) Parse(q string) pgb.Expr {
	return pgb.Raw{SQL: "products.metadata->'color' @@@ pdb.parse(?)", Args: []any{q}}
}

func (c ProductRatingCol) Match(q string) pgb.Expr {
	return pgb.Match(c.Col, q)
}

func (c ProductRatingCol) MatchAll(q string) pgb.Expr {
	return pgb.MatchAll(c.Col, q)
}

func (c ProductRatingCol) Phrase(q string, slop int) pgb.Expr {
	return pgb.Phrase(c.Col, q, slop)
}

func (c ProductRatingCol) Exact(v any) pgb.Expr {
	return pgb.Exact(c.Col, v)
}

func (c ProductRatingCol) Fuzzy(q string, dist int, prefix bool) pgb.Expr {
	return pgb.Fuzzy(c.Col, q, dist, prefix)
}

func (c ProductRatingCol) Regex(pattern string) pgb.Expr {
	return pgb.Regex(c.Col, pattern)
}

func (c ProductRatingCol) Parse(q string) pgb.Expr {
	return pgb.Parse(c.Col, q, false)
}

func (c ProductRatingCol) MatchB(q string, b float64) pgb.Expr {
	return pgb.Boost(pgb.Match(c.Col, q), b)
}

func (c ProductRatingCol) RangeTerm(r any, mode string) pgb.Expr {
	return pgb.RangeTerm(c.Col, r, "numrange", mode)
}

func (c ProductRatingCol) Snippet(startTag, endTag string, maxChars int) pgb.Expr {
	return pgb.Snippet(c.Col, startTag, endTag, maxChars)
}

func (c ProductRatingCol) Snippets(limitN, offsetN int, sortBy string) pgb.Expr {
	return pgb.Snippets(c.Col, limitN, offsetN, sortBy)
}

func (c ProductRatingCol) Highlight() pgb.Expr {
	return pgb.Highlight(c.Col)
}

// SearchProductsOpts keeps the search entry surface small: Limit caps the
// result (<= 0 falls back to 20 — every generated search ends in an
// ordered LIMIT so ParadeDB can push Top-K down); SnippetCol optionally
// names one indexed column to project a pdb.snippet fragment for.
type SearchProductsOpts struct {
	Limit      int
	SnippetCol string
}

// ProductHit is one SearchProducts result row: the full model, the BM25 score,
// and the snippet fragment (populated only when SearchProductsOpts.SnippetCol
// selected one, NULL/zero otherwise).
type ProductHit struct {
	Product Product
	Score   float64
	Snippet pgtype.Text
}

// ScanProducts scans one SearchProducts row positionally: every products column
// in catalog order, then the spgb. Rows requested with a snippet
// projection carry one extra trailing column — SearchProducts scans those
// rows itself.
func ScanProducts(row pgx.CollectableRow) (ProductHit, error) {
	var h ProductHit
	var p Product
	if err := row.Scan(&p.ID, &p.Sku, &p.Title, &p.Description, &p.Category, &p.Rating, &p.Price, &p.InStock, &p.Metadata, &p.Embedding, &p.CreatedAt, &h.Score); err != nil {
		return ProductHit{}, err
	}
	h.Product = p
	return h, nil
}

// SearchProducts runs the generic document query against the index key
// field: WHERE id @@@ pdb.parse($1) — pdb.parse carries ParadeDB's full
// query-string syntax — selecting every column plus pdb.score(id),
// optionally one pdb.snippet fragment, ordered pdb.score(id) DESC,
// id ASC and LIMIT-bounded.
func SearchProducts(ctx context.Context, exec pgb.DBTX, q string, o SearchProductsOpts) ([]ProductHit, error) {
	limit := o.Limit
	if limit <= 0 {
		limit = 20
	}
	key := pgb.Col{Table: "products", Name: "id"}
	cols := []pgb.Expr{pgb.Col{Table: "products", Name: "id"}, pgb.Col{Table: "products", Name: "sku"}, pgb.Col{Table: "products", Name: "title"}, pgb.Col{Table: "products", Name: "description"}, pgb.Col{Table: "products", Name: "category"}, pgb.Col{Table: "products", Name: "rating"}, pgb.Col{Table: "products", Name: "price"}, pgb.Col{Table: "products", Name: "in_stock"}, pgb.Col{Table: "products", Name: "metadata"}, pgb.Col{Table: "products", Name: "embedding"}, pgb.Col{Table: "products", Name: "created_at"}, pgb.Score(key)}
	if o.SnippetCol != "" {
		cols = append(cols, pgb.Snippet(pgb.Col{Table: "products", Name: o.SnippetCol}, "", "", 0))
	}
	rows, err := pgb.NewSelect("public.products", cols...).
		WhereExpr(pgb.Parse(key, q, false)).
		OrderBy(pgb.Desc(pgb.Score(key)), pgb.Asc(key)).
		Limit(limit).
		Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	if o.SnippetCol == "" {
		return pgx.CollectRows(rows, ScanProducts)
	}
	return pgx.CollectRows(rows, func(row pgx.CollectableRow) (ProductHit, error) {
		var h ProductHit
		var p Product
		if err := row.Scan(&p.ID, &p.Sku, &p.Title, &p.Description, &p.Category, &p.Rating, &p.Price, &p.InStock, &p.Metadata, &p.Embedding, &p.CreatedAt, &h.Score, &h.Snippet); err != nil {
			return ProductHit{}, err
		}
		h.Product = p
		return h, nil
	})
}
