// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	pgb "github.com/khoale-2804/pgb/core"
)

// Shifts is the table descriptor for public.shifts; immutable, safe for
// concurrent use.
var Shifts = ShiftTable{pgb.NewTableMeta("public", "shifts")}

// ShiftTable provides typed column accessors and statement entry points.
type ShiftTable struct{ pgb.TableMeta }

// ID returns the typed accessor for column id.
func (t ShiftTable) ID() ShiftIDCol {
	return ShiftIDCol{pgb.Col{Table: "shifts", Name: "id"}}
}

// ShiftIDCol is the typed column shifts.id.
type ShiftIDCol struct{ pgb.Col }

func (c ShiftIDCol) Eq(v int64) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftIDCol) Ne(v int64) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftIDCol) In(vs ...int64) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "int8[]" + ")", Args: []any{vs}}
}

func (c ShiftIDCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ShiftIDCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ShiftIDCol) Gt(v int64) pgb.Expr {
	return pgb.Bin{Op: ">", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftIDCol) Lt(v int64) pgb.Expr {
	return pgb.Bin{Op: "<", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftIDCol) Gte(v int64) pgb.Expr {
	return pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftIDCol) Lte(v int64) pgb.Expr {
	return pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftIDCol) Between(a, b int64) pgb.Expr {
	return pgb.And{Parts: []pgb.Expr{
		pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: a}},
		pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: b}},
	}}
}

// EmployeeID returns the typed accessor for column employee_id.
func (t ShiftTable) EmployeeID() ShiftEmployeeIDCol {
	return ShiftEmployeeIDCol{pgb.Col{Table: "shifts", Name: "employee_id"}}
}

// ShiftEmployeeIDCol is the typed column shifts.employee_id.
type ShiftEmployeeIDCol struct{ pgb.Col }

func (c ShiftEmployeeIDCol) Eq(v int32) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftEmployeeIDCol) Ne(v int32) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftEmployeeIDCol) In(vs ...int32) pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " = ANY(?::" + "int4[]" + ")", Args: []any{vs}}
}

func (c ShiftEmployeeIDCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ShiftEmployeeIDCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c ShiftEmployeeIDCol) Gt(v int32) pgb.Expr {
	return pgb.Bin{Op: ">", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftEmployeeIDCol) Lt(v int32) pgb.Expr {
	return pgb.Bin{Op: "<", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftEmployeeIDCol) Gte(v int32) pgb.Expr {
	return pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftEmployeeIDCol) Lte(v int32) pgb.Expr {
	return pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftEmployeeIDCol) Between(a, b int32) pgb.Expr {
	return pgb.And{Parts: []pgb.Expr{
		pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: a}},
		pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: b}},
	}}
}

// During returns the typed accessor for column during.
func (t ShiftTable) During() ShiftDuringCol {
	return ShiftDuringCol{pgb.Col{Table: "shifts", Name: "during"}}
}

// ShiftDuringCol is the typed column shifts.during.
type ShiftDuringCol struct{ pgb.Col }

func (c ShiftDuringCol) Eq(v pgtype.Range[pgtype.Timestamptz]) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftDuringCol) Ne(v pgtype.Range[pgtype.Timestamptz]) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c ShiftDuringCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c ShiftDuringCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

// Select starts a SELECT of every column; chain Where/OrderBy/Limit/...
// and terminate with Run (or a static function).
func (t ShiftTable) Select() *pgb.Select {
	return pgb.NewSelect("public.shifts", pgb.Col{Table: "shifts", Name: "id"}, pgb.Col{Table: "shifts", Name: "employee_id"}, pgb.Col{Table: "shifts", Name: "during"})
}

// Update starts an UPDATE; an empty WHERE fails with pgb.ErrNoWhere.
func (t ShiftTable) Update() *pgb.Update { return pgb.NewUpdate("public.shifts") }

// Delete starts a DELETE; an empty WHERE fails with pgb.ErrNoWhere.
func (t ShiftTable) Delete() *pgb.Delete { return pgb.NewDelete("public.shifts") }
