// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"errors"
	"github.com/jackc/pgx/v5"
	pgb "github.com/khoale-2804/pgb/core"
)

// SkippablePartnerFilter narrows ListSkippablePartners and CountSkippablePartners:
// nil / zero fields are ignored; Extra composes raw predicates.
type SkippablePartnerFilter struct {
	ID         *int64
	IDIn       []int64
	IDGt       *int64
	IDLt       *int64
	IDGte      *int64
	IDLte      *int64
	Label      *string
	LabelIn    []string
	LabelLike  *string
	LabelILike *string
	Extra      []pgb.Expr
}

// skippablePartnersFilterWhere compiles f into the ANDed predicate list; an empty
// filter yields an empty list (no WHERE).
func skippablePartnersFilterWhere(f SkippablePartnerFilter) []pgb.Expr {
	var w []pgb.Expr
	if f.ID != nil {
		w = append(w, SkippablePartners.ID().Eq(*f.ID))
	}
	if len(f.IDIn) > 0 {
		w = append(w, SkippablePartners.ID().In(f.IDIn...))
	}
	if f.IDGt != nil {
		w = append(w, SkippablePartners.ID().Gt(*f.IDGt))
	}
	if f.IDLt != nil {
		w = append(w, SkippablePartners.ID().Lt(*f.IDLt))
	}
	if f.IDGte != nil {
		w = append(w, SkippablePartners.ID().Gte(*f.IDGte))
	}
	if f.IDLte != nil {
		w = append(w, SkippablePartners.ID().Lte(*f.IDLte))
	}
	if f.Label != nil {
		w = append(w, SkippablePartners.Label().Eq(*f.Label))
	}
	if len(f.LabelIn) > 0 {
		w = append(w, SkippablePartners.Label().In(f.LabelIn...))
	}
	if f.LabelLike != nil {
		w = append(w, SkippablePartners.Label().Like(*f.LabelLike))
	}
	if f.LabelILike != nil {
		w = append(w, SkippablePartners.Label().ILike(*f.LabelILike))
	}
	w = append(w, f.Extra...)
	return w
}

// SkippablePartnerSet is the three-state UPDATE payload: a zero Set field
// skips its column, SetOf writes a value, SetNull writes NULL.
type SkippablePartnerSet struct {
	Label Set[string]
}

// InsertSkippablePartnerParams carries the INSERT column values: generated
// and serial columns are out, default-bearing columns join only with
// the include_defaults option.
type InsertSkippablePartnerParams struct {
	Label string
}

// scanSkippablePartner scans one row positionally over every column in
// catalog order — the single scan path for all generated reads.
func scanSkippablePartner(row pgx.CollectableRow) (SkippablePartner, error) {
	var m SkippablePartner
	if err := row.Scan(&m.ID, &m.Label); err != nil {
		return SkippablePartner{}, err
	}
	return m, nil
}

// GetSkippablePartner returns one row by id; pgb.ErrNotFound when absent
// (pgx.ErrNoRows mapped — errors.Is keeps working for both).
func GetSkippablePartner(ctx context.Context, exec pgb.DBTX, id int64) (SkippablePartner, error) {
	sql, args := SkippablePartners.Select().Where(SkippablePartners.ID().Eq(id)).SQL()
	var m SkippablePartner
	err := exec.QueryRow(ctx, sql, args...).Scan(&m.ID, &m.Label)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return SkippablePartner{}, pgb.ErrNotFound
		}
		return SkippablePartner{}, err
	}
	return m, nil
}

// ListSkippablePartners returns the rows matching f; limit <= 0 means no LIMIT.
func ListSkippablePartners(ctx context.Context, exec pgb.DBTX, f SkippablePartnerFilter, opts ...pgb.ListOpt) ([]SkippablePartner, error) {
	sel := SkippablePartners.Select().Where(skippablePartnersFilterWhere(f)...).ApplyList(opts...)
	rows, err := sel.Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanSkippablePartner)
}

// CountSkippablePartners counts the rows matching f.
func CountSkippablePartners(ctx context.Context, exec pgb.DBTX, f SkippablePartnerFilter) (int64, error) {
	sql, args := pgb.NewSelect("public.skippable_partner", pgb.Raw{SQL: "count(*)"}).Where(skippablePartnersFilterWhere(f)...).SQL()
	var n int64
	if err := exec.QueryRow(ctx, sql, args...).Scan(&n); err != nil {
		return 0, err
	}
	return n, nil
}

// InsertSkippablePartner inserts one row and returns it (RETURNING every
// column, defaults included).
func InsertSkippablePartner(ctx context.Context, exec pgb.DBTX, p InsertSkippablePartnerParams) (SkippablePartner, error) {
	rows, err := pgb.NewInsert("public.skippable_partner",
		[]string{"label"},
		[]pgb.Expr{pgb.Lit{V: p.Label}},
	).Returning(pgb.Col{Table: "skippable_partner", Name: "id"}, pgb.Col{Table: "skippable_partner", Name: "label"}).Run(ctx, exec)
	if err != nil {
		return SkippablePartner{}, err
	}
	us, err := pgx.CollectRows(rows, scanSkippablePartner)
	if err != nil {
		return SkippablePartner{}, err
	}
	if len(us) == 0 {
		return SkippablePartner{}, pgb.ErrNotFound
	}
	return us[0], nil
}

const insertSkippablePartnersSQL = "INSERT INTO public.skippable_partner (label) SELECT * FROM unnest($1::text[]) RETURNING id, label"

// InsertSkippablePartners inserts a whole batch in one round trip via
// unnest and returns every inserted row.
func InsertSkippablePartners(ctx context.Context, exec pgb.DBTX, ps []InsertSkippablePartnerParams) ([]SkippablePartner, error) {
	if len(ps) == 0 {
		return nil, nil
	}
	colLabel := make([]string, len(ps))
	for i, p := range ps {
		colLabel[i] = p.Label
	}
	args := make([]any, 0, 1*len(ps))
	args = append(args, colLabel)
	rows, err := exec.Query(ctx, insertSkippablePartnersSQL, args...)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanSkippablePartner)
}

// UpdateSkippablePartner applies the non-zero fields of s to one row and
// returns the updated row; pgb.ErrNotFound when absent.
func UpdateSkippablePartner(ctx context.Context, exec pgb.DBTX, id int64, s SkippablePartnerSet) (SkippablePartner, error) {
	u := SkippablePartners.Update()
	n := 0
	if s.Label.Valid {
		n++
		if s.Label.Null {
			u.Set("label", pgb.Lit{V: nil})
		} else {
			u.Set("label", pgb.Lit{V: s.Label.V})
		}
	}
	if n == 0 {
		return GetSkippablePartner(ctx, exec, id)
	}
	u.Where(SkippablePartners.ID().Eq(id)).Returning(pgb.Col{Table: "skippable_partner", Name: "id"}, pgb.Col{Table: "skippable_partner", Name: "label"})
	rows, err := u.Run(ctx, exec)
	if err != nil {
		return SkippablePartner{}, err
	}
	us, err := pgx.CollectRows(rows, scanSkippablePartner)
	if err != nil {
		return SkippablePartner{}, err
	}
	if len(us) == 0 {
		return SkippablePartner{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// UpdateSkippablePartners applies s to every row matching where and
// returns the affected count; an empty where is refused with
// pgb.ErrNoWhere before any SQL is sent.
func UpdateSkippablePartners(ctx context.Context, exec pgb.DBTX, where []pgb.Expr, s SkippablePartnerSet) (int64, error) {
	u := SkippablePartners.Update()
	n := 0
	if s.Label.Valid {
		n++
		if s.Label.Null {
			u.Set("label", pgb.Lit{V: nil})
		} else {
			u.Set("label", pgb.Lit{V: s.Label.V})
		}
	}
	if n == 0 {
		return 0, nil
	}
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	u.Where(where...)
	tag, err := u.Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// UpsertSkippablePartner inserts p under id, or on conflict updates
// every settable column from the proposed row (EXCLUDED.*) and returns
// the resulting row; pgb.ErrNotFound when DO NOTHING matched.
func UpsertSkippablePartner(ctx context.Context, exec pgb.DBTX, id int64, p InsertSkippablePartnerParams) (SkippablePartner, error) {
	rows, err := pgb.NewInsert("public.skippable_partner",
		[]string{"id", "label"},
		[]pgb.Expr{pgb.Lit{V: id}, pgb.Lit{V: p.Label}},
	).OnConflict(pgb.OnConflict{
		Target: []string{"id"},
		Sets: []pgb.SetClause{
			{Col: "label", E: pgb.Col{Table: "excluded", Name: "label"}},
		},
	}).Returning(pgb.Col{Table: "skippable_partner", Name: "id"}, pgb.Col{Table: "skippable_partner", Name: "label"}).Run(ctx, exec)
	if err != nil {
		return SkippablePartner{}, err
	}
	us, err := pgx.CollectRows(rows, scanSkippablePartner)
	if err != nil {
		return SkippablePartner{}, err
	}
	if len(us) == 0 {
		return SkippablePartner{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// DeleteSkippablePartner removes one row by id.
func DeleteSkippablePartner(ctx context.Context, exec pgb.DBTX, id int64) error {
	_, err := SkippablePartners.Delete().Where(SkippablePartners.ID().Eq(id)).Exec(ctx, exec)
	return err
}

// DeleteSkippablePartners removes every row matching where and returns the
// affected count; an empty where is refused with pgb.ErrNoWhere.
func DeleteSkippablePartners(ctx context.Context, exec pgb.DBTX, where []pgb.Expr) (int64, error) {
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	tag, err := SkippablePartners.Delete().Where(where...).Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
