// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	pgb "github.com/khoale-2804/pgb/core"
)

// SkippablePartners is the table descriptor for public.skippable_partner; immutable, safe for
// concurrent use.
var SkippablePartners = SkippablePartnerTable{pgb.NewTableMeta("public", "skippable_partner")}

// SkippablePartnerTable provides typed column accessors and statement entry points.
type SkippablePartnerTable struct{ pgb.TableMeta }

// ID returns the typed accessor for column id.
func (t SkippablePartnerTable) ID() SkippablePartnerIDCol {
	return SkippablePartnerIDCol{pgb.Col{Table: "skippable_partner", Name: "id"}}
}

// SkippablePartnerIDCol is the typed column skippable_partner.id.
type SkippablePartnerIDCol struct{ pgb.Col }

func (c SkippablePartnerIDCol) Eq(v int64) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c SkippablePartnerIDCol) Ne(v int64) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c SkippablePartnerIDCol) In(vs ...int64) pgb.Expr {
	return pgb.Bin{Op: "= ANY", L: c.Col, R: pgb.Lit{V: vs, Cast: "int8[]"}}
}

func (c SkippablePartnerIDCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c SkippablePartnerIDCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c SkippablePartnerIDCol) Gt(v int64) pgb.Expr {
	return pgb.Bin{Op: ">", L: c.Col, R: pgb.Lit{V: v}}
}

func (c SkippablePartnerIDCol) Lt(v int64) pgb.Expr {
	return pgb.Bin{Op: "<", L: c.Col, R: pgb.Lit{V: v}}
}

func (c SkippablePartnerIDCol) Gte(v int64) pgb.Expr {
	return pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c SkippablePartnerIDCol) Lte(v int64) pgb.Expr {
	return pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c SkippablePartnerIDCol) Between(a, b int64) pgb.Expr {
	return pgb.And{Parts: []pgb.Expr{
		pgb.Bin{Op: ">=", L: c.Col, R: pgb.Lit{V: a}},
		pgb.Bin{Op: "<=", L: c.Col, R: pgb.Lit{V: b}},
	}}
}

// Label returns the typed accessor for column label.
func (t SkippablePartnerTable) Label() SkippablePartnerLabelCol {
	return SkippablePartnerLabelCol{pgb.Col{Table: "skippable_partner", Name: "label"}}
}

// SkippablePartnerLabelCol is the typed column skippable_partner.label.
type SkippablePartnerLabelCol struct{ pgb.Col }

func (c SkippablePartnerLabelCol) Eq(v string) pgb.Expr {
	return pgb.Bin{Op: "=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c SkippablePartnerLabelCol) Ne(v string) pgb.Expr {
	return pgb.Bin{Op: "!=", L: c.Col, R: pgb.Lit{V: v}}
}

func (c SkippablePartnerLabelCol) In(vs ...string) pgb.Expr {
	return pgb.Bin{Op: "= ANY", L: c.Col, R: pgb.Lit{V: vs, Cast: "text[]"}}
}

func (c SkippablePartnerLabelCol) IsNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NULL"}
}

func (c SkippablePartnerLabelCol) NotNull() pgb.Expr {
	return pgb.Raw{SQL: pgb.QuoteIdent(c.Col.Table, c.Col.Name) + " IS NOT NULL"}
}

func (c SkippablePartnerLabelCol) Like(p string) pgb.Expr {
	return pgb.Bin{Op: "LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c SkippablePartnerLabelCol) ILike(p string) pgb.Expr {
	return pgb.Bin{Op: "ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c SkippablePartnerLabelCol) NotLike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT LIKE", L: c.Col, R: pgb.Lit{V: p}}
}

func (c SkippablePartnerLabelCol) NotILike(p string) pgb.Expr {
	return pgb.Bin{Op: "NOT ILIKE", L: c.Col, R: pgb.Lit{V: p}}
}

// Select starts a SELECT of every column; chain Where/OrderBy/Limit/...
// and terminate with Run (or a static function).
func (t SkippablePartnerTable) Select() *pgb.Select {
	return pgb.NewSelect("public.skippable_partner", pgb.Col{Table: "skippable_partner", Name: "id"}, pgb.Col{Table: "skippable_partner", Name: "label"})
}

// Update starts an UPDATE; an empty WHERE fails with pgb.ErrNoWhere.
func (t SkippablePartnerTable) Update() *pgb.Update { return pgb.NewUpdate("public.skippable_partner") }

// Delete starts a DELETE; an empty WHERE fails with pgb.ErrNoWhere.
func (t SkippablePartnerTable) Delete() *pgb.Delete { return pgb.NewDelete("public.skippable_partner") }
