// Code generated by pgb. DO NOT EDIT.
// versions:
//   pgb v0.1.0
//   sqlc v1.31.1

package db

import (
	"context"
	"errors"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	pgb "github.com/khoale-2804/pgb/core"
)

// TicketFilter narrows ListTickets and CountTickets:
// nil / zero fields are ignored; Extra composes raw predicates.
type TicketFilter struct {
	ID            *int64
	IDIn          []int64
	IDGt          *int64
	IDLt          *int64
	IDGte         *int64
	IDLte         *int64
	Number        *int64
	NumberIn      []int64
	NumberGt      *int64
	NumberLt      *int64
	NumberGte     *int64
	NumberLte     *int64
	Subject       *string
	SubjectIn     []string
	SubjectLike   *string
	SubjectILike  *string
	Priority      *string
	PriorityIn    []string
	PriorityLike  *string
	PriorityILike *string
	Status        *string
	StatusIn      []string
	StatusLike    *string
	StatusILike   *string
	CreatedAt     *pgtype.Timestamptz
	CreatedAtIn   []pgtype.Timestamptz
	CreatedAtGt   *pgtype.Timestamptz
	CreatedAtLt   *pgtype.Timestamptz
	CreatedAtGte  *pgtype.Timestamptz
	CreatedAtLte  *pgtype.Timestamptz
	Extra         []pgb.Expr
}

// ticketsFilterWhere compiles f into the ANDed predicate list; an empty
// filter yields an empty list (no WHERE).
func ticketsFilterWhere(f TicketFilter) []pgb.Expr {
	var w []pgb.Expr
	if f.ID != nil {
		w = append(w, Tickets.ID().Eq(*f.ID))
	}
	if len(f.IDIn) > 0 {
		w = append(w, Tickets.ID().In(f.IDIn...))
	}
	if f.IDGt != nil {
		w = append(w, Tickets.ID().Gt(*f.IDGt))
	}
	if f.IDLt != nil {
		w = append(w, Tickets.ID().Lt(*f.IDLt))
	}
	if f.IDGte != nil {
		w = append(w, Tickets.ID().Gte(*f.IDGte))
	}
	if f.IDLte != nil {
		w = append(w, Tickets.ID().Lte(*f.IDLte))
	}
	if f.Number != nil {
		w = append(w, Tickets.Number().Eq(*f.Number))
	}
	if len(f.NumberIn) > 0 {
		w = append(w, Tickets.Number().In(f.NumberIn...))
	}
	if f.NumberGt != nil {
		w = append(w, Tickets.Number().Gt(*f.NumberGt))
	}
	if f.NumberLt != nil {
		w = append(w, Tickets.Number().Lt(*f.NumberLt))
	}
	if f.NumberGte != nil {
		w = append(w, Tickets.Number().Gte(*f.NumberGte))
	}
	if f.NumberLte != nil {
		w = append(w, Tickets.Number().Lte(*f.NumberLte))
	}
	if f.Subject != nil {
		w = append(w, Tickets.Subject().Eq(*f.Subject))
	}
	if len(f.SubjectIn) > 0 {
		w = append(w, Tickets.Subject().In(f.SubjectIn...))
	}
	if f.SubjectLike != nil {
		w = append(w, Tickets.Subject().Like(*f.SubjectLike))
	}
	if f.SubjectILike != nil {
		w = append(w, Tickets.Subject().ILike(*f.SubjectILike))
	}
	if f.Priority != nil {
		w = append(w, Tickets.Priority().Eq(*f.Priority))
	}
	if len(f.PriorityIn) > 0 {
		w = append(w, Tickets.Priority().In(f.PriorityIn...))
	}
	if f.PriorityLike != nil {
		w = append(w, Tickets.Priority().Like(*f.PriorityLike))
	}
	if f.PriorityILike != nil {
		w = append(w, Tickets.Priority().ILike(*f.PriorityILike))
	}
	if f.Status != nil {
		w = append(w, Tickets.Status().Eq(*f.Status))
	}
	if len(f.StatusIn) > 0 {
		w = append(w, Tickets.Status().In(f.StatusIn...))
	}
	if f.StatusLike != nil {
		w = append(w, Tickets.Status().Like(*f.StatusLike))
	}
	if f.StatusILike != nil {
		w = append(w, Tickets.Status().ILike(*f.StatusILike))
	}
	if f.CreatedAt != nil {
		w = append(w, Tickets.CreatedAt().Eq(*f.CreatedAt))
	}
	if len(f.CreatedAtIn) > 0 {
		w = append(w, Tickets.CreatedAt().In(f.CreatedAtIn...))
	}
	if f.CreatedAtGt != nil {
		w = append(w, Tickets.CreatedAt().Gt(*f.CreatedAtGt))
	}
	if f.CreatedAtLt != nil {
		w = append(w, Tickets.CreatedAt().Lt(*f.CreatedAtLt))
	}
	if f.CreatedAtGte != nil {
		w = append(w, Tickets.CreatedAt().Gte(*f.CreatedAtGte))
	}
	if f.CreatedAtLte != nil {
		w = append(w, Tickets.CreatedAt().Lte(*f.CreatedAtLte))
	}
	w = append(w, f.Extra...)
	return w
}

// TicketSet is the three-state UPDATE payload: a zero Set field
// skips its column, SetOf writes a value, SetNull writes NULL.
type TicketSet struct {
	Number    Set[int64]
	Subject   Set[string]
	Priority  Set[string]
	Status    Set[string]
	CreatedAt Set[pgtype.Timestamptz]
}

// InsertTicketParams carries the INSERT column values: generated
// and serial columns are out, default-bearing columns join only with
// the include_defaults option.
type InsertTicketParams struct {
	Subject string
}

// scanTicket scans one row positionally over every column in
// catalog order — the single scan path for all generated reads.
func scanTicket(row pgx.CollectableRow) (Ticket, error) {
	var m Ticket
	if err := row.Scan(&m.ID, &m.Number, &m.Subject, &m.Priority, &m.Status, &m.CreatedAt); err != nil {
		return Ticket{}, err
	}
	return m, nil
}

// GetTicket returns one row by id; pgb.ErrNotFound when absent
// (pgx.ErrNoRows mapped — errors.Is keeps working for both).
func GetTicket(ctx context.Context, exec pgb.DBTX, id int64) (Ticket, error) {
	sql, args := Tickets.Select().Where(Tickets.ID().Eq(id)).SQL()
	var m Ticket
	err := exec.QueryRow(ctx, sql, args...).Scan(&m.ID, &m.Number, &m.Subject, &m.Priority, &m.Status, &m.CreatedAt)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Ticket{}, pgb.ErrNotFound
		}
		return Ticket{}, err
	}
	return m, nil
}

// ListTickets returns the rows matching f; limit <= 0 means no LIMIT.
func ListTickets(ctx context.Context, exec pgb.DBTX, f TicketFilter, opts ...pgb.ListOpt) ([]Ticket, error) {
	sel := Tickets.Select().Where(ticketsFilterWhere(f)...).ApplyList(opts...)
	rows, err := sel.Run(ctx, exec)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanTicket)
}

// CountTickets counts the rows matching f.
func CountTickets(ctx context.Context, exec pgb.DBTX, f TicketFilter) (int64, error) {
	sql, args := pgb.NewSelect("public.tickets", pgb.Raw{SQL: "count(*)"}).Where(ticketsFilterWhere(f)...).SQL()
	var n int64
	if err := exec.QueryRow(ctx, sql, args...).Scan(&n); err != nil {
		return 0, err
	}
	return n, nil
}

// InsertTicket inserts one row and returns it (RETURNING every
// column, defaults included).
func InsertTicket(ctx context.Context, exec pgb.DBTX, p InsertTicketParams) (Ticket, error) {
	rows, err := pgb.NewInsert("public.tickets",
		[]string{"subject"},
		[]pgb.Expr{pgb.Lit{V: p.Subject}},
	).Returning(pgb.Col{Table: "tickets", Name: "id"}, pgb.Col{Table: "tickets", Name: "number"}, pgb.Col{Table: "tickets", Name: "subject"}, pgb.Col{Table: "tickets", Name: "priority"}, pgb.Col{Table: "tickets", Name: "status"}, pgb.Col{Table: "tickets", Name: "created_at"}).Run(ctx, exec)
	if err != nil {
		return Ticket{}, err
	}
	us, err := pgx.CollectRows(rows, scanTicket)
	if err != nil {
		return Ticket{}, err
	}
	if len(us) == 0 {
		return Ticket{}, pgb.ErrNotFound
	}
	return us[0], nil
}

const insertTicketsSQL = "INSERT INTO public.tickets (subject) SELECT * FROM unnest($1::text[]) RETURNING id, number, subject, priority, status, created_at"

// InsertTickets inserts a whole batch in one round trip via
// unnest and returns every inserted row.
func InsertTickets(ctx context.Context, exec pgb.DBTX, ps []InsertTicketParams) ([]Ticket, error) {
	if len(ps) == 0 {
		return nil, nil
	}
	colSubject := make([]string, len(ps))
	for i, p := range ps {
		colSubject[i] = p.Subject
	}
	args := make([]any, 0, 1*len(ps))
	args = append(args, colSubject)
	rows, err := exec.Query(ctx, insertTicketsSQL, args...)
	if err != nil {
		return nil, err
	}
	return pgx.CollectRows(rows, scanTicket)
}

// UpdateTicket applies the non-zero fields of s to one row and
// returns the updated row; pgb.ErrNotFound when absent.
func UpdateTicket(ctx context.Context, exec pgb.DBTX, id int64, s TicketSet) (Ticket, error) {
	u := Tickets.Update()
	n := 0
	if s.Number.Valid {
		n++
		if s.Number.Null {
			u.Set("number", pgb.Lit{V: nil})
		} else {
			u.Set("number", pgb.Lit{V: s.Number.V})
		}
	}
	if s.Subject.Valid {
		n++
		if s.Subject.Null {
			u.Set("subject", pgb.Lit{V: nil})
		} else {
			u.Set("subject", pgb.Lit{V: s.Subject.V})
		}
	}
	if s.Priority.Valid {
		n++
		if s.Priority.Null {
			u.Set("priority", pgb.Lit{V: nil})
		} else {
			u.Set("priority", pgb.Lit{V: s.Priority.V})
		}
	}
	if s.Status.Valid {
		n++
		if s.Status.Null {
			u.Set("status", pgb.Lit{V: nil})
		} else {
			u.Set("status", pgb.Lit{V: s.Status.V})
		}
	}
	if s.CreatedAt.Valid {
		n++
		if s.CreatedAt.Null {
			u.Set("created_at", pgb.Lit{V: nil})
		} else {
			u.Set("created_at", pgb.Lit{V: s.CreatedAt.V})
		}
	}
	if n == 0 {
		return GetTicket(ctx, exec, id)
	}
	u.Where(Tickets.ID().Eq(id)).Returning(pgb.Col{Table: "tickets", Name: "id"}, pgb.Col{Table: "tickets", Name: "number"}, pgb.Col{Table: "tickets", Name: "subject"}, pgb.Col{Table: "tickets", Name: "priority"}, pgb.Col{Table: "tickets", Name: "status"}, pgb.Col{Table: "tickets", Name: "created_at"})
	rows, err := u.Run(ctx, exec)
	if err != nil {
		return Ticket{}, err
	}
	us, err := pgx.CollectRows(rows, scanTicket)
	if err != nil {
		return Ticket{}, err
	}
	if len(us) == 0 {
		return Ticket{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// UpdateTickets applies s to every row matching where and
// returns the affected count; an empty where is refused with
// pgb.ErrNoWhere before any SQL is sent.
func UpdateTickets(ctx context.Context, exec pgb.DBTX, where []pgb.Expr, s TicketSet) (int64, error) {
	u := Tickets.Update()
	n := 0
	if s.Number.Valid {
		n++
		if s.Number.Null {
			u.Set("number", pgb.Lit{V: nil})
		} else {
			u.Set("number", pgb.Lit{V: s.Number.V})
		}
	}
	if s.Subject.Valid {
		n++
		if s.Subject.Null {
			u.Set("subject", pgb.Lit{V: nil})
		} else {
			u.Set("subject", pgb.Lit{V: s.Subject.V})
		}
	}
	if s.Priority.Valid {
		n++
		if s.Priority.Null {
			u.Set("priority", pgb.Lit{V: nil})
		} else {
			u.Set("priority", pgb.Lit{V: s.Priority.V})
		}
	}
	if s.Status.Valid {
		n++
		if s.Status.Null {
			u.Set("status", pgb.Lit{V: nil})
		} else {
			u.Set("status", pgb.Lit{V: s.Status.V})
		}
	}
	if s.CreatedAt.Valid {
		n++
		if s.CreatedAt.Null {
			u.Set("created_at", pgb.Lit{V: nil})
		} else {
			u.Set("created_at", pgb.Lit{V: s.CreatedAt.V})
		}
	}
	if n == 0 {
		return 0, nil
	}
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	u.Where(where...)
	tag, err := u.Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// UpsertTicket inserts p under id, or on conflict updates
// every settable column from the proposed row (EXCLUDED.*) and returns
// the resulting row; pgb.ErrNotFound when DO NOTHING matched.
func UpsertTicket(ctx context.Context, exec pgb.DBTX, id int64, p InsertTicketParams) (Ticket, error) {
	rows, err := pgb.NewInsert("public.tickets",
		[]string{"id", "subject"},
		[]pgb.Expr{pgb.Lit{V: id}, pgb.Lit{V: p.Subject}},
	).OnConflict(pgb.OnConflict{
		Target: []string{"id"},
		Sets: []pgb.SetClause{
			{Col: "number", E: pgb.Col{Table: "excluded", Name: "number"}},
			{Col: "subject", E: pgb.Col{Table: "excluded", Name: "subject"}},
			{Col: "priority", E: pgb.Col{Table: "excluded", Name: "priority"}},
			{Col: "status", E: pgb.Col{Table: "excluded", Name: "status"}},
			{Col: "created_at", E: pgb.Col{Table: "excluded", Name: "created_at"}},
		},
	}).Returning(pgb.Col{Table: "tickets", Name: "id"}, pgb.Col{Table: "tickets", Name: "number"}, pgb.Col{Table: "tickets", Name: "subject"}, pgb.Col{Table: "tickets", Name: "priority"}, pgb.Col{Table: "tickets", Name: "status"}, pgb.Col{Table: "tickets", Name: "created_at"}).Run(ctx, exec)
	if err != nil {
		return Ticket{}, err
	}
	us, err := pgx.CollectRows(rows, scanTicket)
	if err != nil {
		return Ticket{}, err
	}
	if len(us) == 0 {
		return Ticket{}, pgb.ErrNotFound
	}
	return us[0], nil
}

// DeleteTicket removes one row by id.
func DeleteTicket(ctx context.Context, exec pgb.DBTX, id int64) error {
	_, err := Tickets.Delete().Where(Tickets.ID().Eq(id)).Exec(ctx, exec)
	return err
}

// DeleteTickets removes every row matching where and returns the
// affected count; an empty where is refused with pgb.ErrNoWhere.
func DeleteTickets(ctx context.Context, exec pgb.DBTX, where []pgb.Expr) (int64, error) {
	if len(where) == 0 {
		return 0, pgb.ErrNoWhere
	}
	tag, err := Tickets.Delete().Where(where...).Exec(ctx, exec)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
